(()=>{'use strict';const $=id=>document.getElementById(id),D=CIRCUIT_DATA;let storage;try{storage=localStorage}catch{storage=null}const store=new CircuitSave.Store(storage,()=>{$('storage-warning').hidden=false}),profile=store.profile,settings=profile.settings;const renderer=new CircuitRenderer($('arena'),settings);let game=null,hero=0,menu='',lastSignature='',lastSave=0,lastHud=0,noticeUntil=0,keys=new Set(),joy={id:null,x:0,y:0};
 class Audio{
  constructor(){this.ctx=null;this.beat=0;this.next=0}
  unlock(){try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume()}catch{}}
  tone(freq,time=.08,type='sine',volume=.08,slide=0){if(!this.ctx||!settings.sound)return;const c=this.ctx,o=c.createOscillator(),a=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,c.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(slide,c.currentTime+time);a.gain.setValueAtTime(volume,c.currentTime);a.gain.exponentialRampToValueAtTime(.001,c.currentTime+time);o.connect(a).connect(c.destination);o.start();o.stop(c.currentTime+time)}
  effect(type){if(type==='seal'){this.tone(600,.16,'sawtooth',.07,80);this.tone(90,.2,'triangle',.15,40)}if(type==='capture')this.tone(650,.065,'sine',.06,1400);if(type==='echo')this.tone(180,.3,'triangle',.1,760);if(type==='hurt')this.tone(80,.16,'square',.055,30);if(type==='dash')this.tone(350,.08,'triangle',.05,100);if(type==='upgrade'||type==='waveClear'){this.tone(440,.12,'triangle');setTimeout(()=>this.tone(660,.16,'triangle'),90)}if(type==='overload')this.tone(70,.6,'sawtooth',.09,1000)}
  update(t){if(!settings.music||!settings.sound||!this.ctx)return;if(t<this.next)return;this.next=t+.24;this.beat++;const bass=[55,55,82.4,55,65.4,65.4,73.4,82.4][Math.floor(this.beat/4)%8];if(this.beat%2===0)this.tone(bass,.18,'triangle',.045);if(this.beat%4===0)this.tone(130,.06,'sine',.04,40);if(this.beat%8===6)this.tone(bass*8,.09,'triangle',.015)}
 }const sound=new Audio();
 const colors={geometry:'#c1ff35',capture:'#ff459a',echo:'#47e6f2',motion:'#aa55ff'},tutorial=[['01 / 移动挂线','用左侧摇杆或 WASD 移动，留下绿色轨迹。让追来的敌人穿过轨迹，看到挂线标记。','敌人被挂线后，收线会额外清算。'],['02 / 收线清算','走出三角或弧形轨迹，点「收线清算」或 J。系统自动连接末端与起点，清算圈内、边缘和挂线敌人。','虚线是即将闭合的接缝。'],['03 / 截获弹幕','移动留下线段，然后让红色弹丸穿过轨迹。捕获后，青色弹珠会留在线上。','弹丸属于你了，下次收线会返还它。'],['04 / 原位回声','点「回声」或 U：在上一条回路的原坐标重放。可以先把敌人引回旧回路。','紫色虚线显示旧回路，不会跟着角色移动。'],['05 / 无敌闪避','移动时点「闪避」或 K，快速穿过危险，并继续织线。','闪避冷却结束后可再次使用。'],['06 / 倒带脱身','先移动一段距离，再点「倒带」或 L，安全返回这卷轨迹的起点，并回收线能。','倒带取消当前轨迹。完成后返回大厅开始正式行动。']];
 function notify(text){$('notice').textContent=text;noticeUntil=performance.now()+2200;$('notice').classList.add('show')}
 function clearInput(){keys.clear();joy.x=joy.y=0;joy.id=null;$('stick').style.transform='translate(0,0)'}
 function checkpoint(){if(game)store.checkpoint(game);lastSave=performance.now()}
 function lobby(){clearInput();game=null;menu='';$('modal').hidden=true;$('hud').hidden=true;$('lobby').hidden=false;refreshLobby()}
 function refreshLobby(){document.documentElement.style.setProperty('--hero',D.heroes[hero].color);$('heroes').innerHTML=D.heroes.map((h,i)=>`<button data-hero="${i}" class="${hero===i?'selected':''}" style="--hero:${h.color}">${h.mark} / ${h.name}</button>`).join('');const h=D.heroes[hero];$('hero-info').innerHTML=`<b>${h.alias}</b>　生命 ${h.hp} / 捕弹 ${h.capture}<br>${h.desc}`;$('map-info').textContent=D.maps[Number($('map').value)].desc;$('wallet').textContent=`◇ ${profile.wallet}`;const saved=CircuitCore.Game.restore(store.run());$('continue').hidden=!saved;if(saved)$('continue').textContent=`续接第 ${saved.wave} 波 ↻`}
 $('map').innerHTML=D.maps.map((m,i)=>`<option value="${i}">${m.name}</option>`).join('');$('difficulty').innerHTML=D.difficulties.map((m,i)=>`<option value="${i}">${m.name}</option>`).join('');$('map').onchange=refreshLobby;$('heroes').onclick=e=>{const b=e.target.closest('[data-hero]');if(b){hero=Number(b.dataset.hero);refreshLobby()}};
 function start(training=false,resumed=null){
  sound.unlock();clearInput();
  game=resumed||new CircuitCore.Game({hero,map:Number($('map').value),difficulty:Number($('difficulty').value),endless:$('endless').checked,training,meta:training?{}:profile.meta,seed:profile.seed||undefined});
  renderer.cam={x:game.p.x,y:game.p.y};renderer.fx=[];renderer.text=[];menu='';lastSignature='';
  $('lobby').hidden=true;$('hud').hidden=false;$('modal').hidden=true;
  document.documentElement.style.setProperty('--hero',game.heroData.color);$('portrait').textContent=game.heroData.mark;$('objective').hidden=game.training;
  checkpoint();sync();updateHud();
  if(game.training){noticeUntil=0;$('notice').classList.remove('show')}else notify('移动织线，收线清算。你的走位就是武器。');
 }
 $('start').onclick=()=>{if(CircuitCore.Game.restore(store.run())){open('replace','重新剪辑？','新行动会替换尚未完成的行动。永久养成和历史记录仍会保留。','<p class="guide">也可以返回大厅，点击「续接行动」。</p>','NEW CUT',true);footer([['取消',()=>close()],['开始新行动',()=>start(),true]])}else start()};$('training').onclick=()=>start(true);$('continue').onclick=()=>{const g=CircuitCore.Game.restore(store.run());if(g)start(false,g);else{store.remove(CircuitSave.keys.RUN);refreshLobby()}};
 function open(id,title,sub,body,kicker='CIRCUIT SYSTEM',closable=true){menu=id;clearInput();$('modal').hidden=false;$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-sub').textContent=sub;$('modal-body').innerHTML=body;$('close').hidden=!closable;$('modal-footer').innerHTML='';setTimeout(()=>{const b=$('modal-body').querySelector('button:not(:disabled)')||$('modal-footer').querySelector('button')||$('close');b?.focus({preventScroll:true})},0)}
 function footer(items){$('modal-footer').innerHTML='';for(const [name,action,primary]of items){const b=document.createElement('button');b.textContent=name;if(primary)b.className='primary';b.onclick=()=>{sound.unlock();action()};$('modal-footer').append(b)}}
 function close(){if(game&&['upgrade','event','shop','result','trainingDone'].includes(game.phase)){menu='';sync(true);return}$('modal').hidden=true;menu='';if(game?.phase==='paused'){game.resume();clearInput();checkpoint()}}
 $('close').onclick=close;
 function stat(value,label){return`<div class="stat"><b>${value}</b><span>${label}</span></div>`}
 function upgradeCard(id){const u=D.upgrades.find(u=>u.id===id);return`<button class="choice ${u.requires?'advanced':''}" data-upgrade="${u.id}" style="--accent:${colors[u.group]}"><div class="glyph">${u.glyph}</div><span class="group">${D.groups[u.group]}${u.requires?' / 高阶':''}</span><b>${u.name}</b><p>${u.desc}</p><span class="level">${game.up(id)} → ${game.up(id)+1} / ${u.max}${u.requires?' · 规则改写':''}</span></button>`}
 function sync(force=false){if(!game)return;const signature=[game.phase,game.options.join(),game.eventChoices.join(),game.tutorialStep,game.pending].join('|');if(signature===lastSignature&&!force)return;lastSignature=signature;clearInput();if(game.phase==='playing'){menu='';$('modal').hidden=true;updateTutorial();return}
  if(game.phase==='paused'){showPause();return}
  if(game.phase==='upgrade'){open('upgrade','剪辑协议 / 三选一',`LV.${game.level}　剩余 ${Math.max(1,game.pending)} 次选择 · 当前战斗已暂停`,'<div class="cards">'+game.options.map(upgradeCard).join('')+'</div>','REWRITE THE RULES',false);$('modal-body').onclick=e=>{const b=e.target.closest('[data-upgrade]');if(b&&game.selectUpgrade(b.dataset.upgrade)){checkpoint();sync(true)}};footer([[`刷新候选 · 剩余 ${game.rerolls}`,()=>{if(game.reroll()){checkpoint();sync(true)}}]]);$('modal-footer').firstChild.disabled=game.rerolls<=0;return}
  if(game.phase==='event'){open('event','城市异常 / 选择代价','协议修改会在本局持续生效，未来两波的代价会明确记录。','<div class="cards">'+game.eventChoices.map(id=>{const e=D.events.find(e=>e.id===id);return`<button class="choice" data-event="${id}"><div class="glyph">${e.glyph}</div><span class="group">ANOMALY CONTRACT</span><b>${e.name}</b><p>${e.benefit}</p><span class="bad level">${e.cost}</span></button>`}).join('')+'</div>','CITY ANOMALY',false);$('modal-body').onclick=e=>{const b=e.target.closest('[data-event]');if(b&&game.selectEvent(b.dataset.event)){checkpoint();sync(true)}};return}
  if(game.phase==='shop'){const items=[['free','站点急救','恢复 20% 生命',0],['heal','深度修复','恢复 45% 生命',40],['kit','治疗针剂','战斗治疗次数 +1',50],['upgrade','协议数据','立刻选择一个协议',75],['energy','高压电池','补满线能，超载 +25%',25],['reroll','干扰器','协议刷新次数 +2',35]];open('shop',`第 ${game.wave} 波 / 已剪除`,`补给币 ◇ ${game.coins}　生命 ${Math.ceil(game.p.hp)} / ${game.maxHp}　治疗 ×${game.p.heals}`,'<div class="shop-grid">'+items.map(([id,name,desc,cost])=>`<button data-buy="${id}" ${game.shopUsed.includes(id)||game.coins<cost||id==='kit'&&game.p.heals>=5?'disabled':''}><b>${name}</b><p>${desc}</p><small>${game.shopUsed.includes(id)?'已使用':cost?`◇ ${cost}`:'每波免费一次'}</small></button>`).join('')+'</div>','SUPPLY STATION',false);$('modal-body').onclick=e=>{const b=e.target.closest('[data-buy]');if(b&&game.buy(b.dataset.buy)){checkpoint();sync(true)}};footer([['查看构筑',()=>showBuild()],['进入下一波 ↗',()=>{game.nextWave();checkpoint();sync(true)},true]]);return}
  if(game.phase==='trainingDone'){profile.tutorial=true;store.save();open('trainingDone','训练完成 / 可以开工了','真正的武器是路线、接缝和上一条回路。训练不会覆盖正式行动。','<div class="guide"><p>你已掌握：织线、收线、夺弹、原位回声、闪避与倒带。</p><p>正式行动中积累超载能量，用 <b>I / 超载</b> 获得 7 秒免费收线。用 <b>H / 治疗</b> 及时恢复；每波补给都有一次免费急救。</p></div>','TRAINING COMPLETE',false);footer([['返回大厅',lobby,true]]);return}
  if(game.phase==='result'){checkpoint();const s=game.stats,total=Object.values(s.damage).reduce((a,b)=>a+b,0)||1;open('result',game.won?'封锁解除 / 城市重写':'剪辑中断 / 下次再暴走',`${D.maps[game.map].name} · ${game.heroData.name} · ${D.difficulties[game.difficulty].name} · 种子 ${game.seed}`,`<div class="stats">${stat(game.kills,'清算敌人')}${stat(s.burst,'单次最高连斩')}${stat(s.captures,'截获弹幕')}${stat(game.reward,'获得义体碎片')}</div><div class="guide">行动 ${Math.floor(game.time/60)}:${String(Math.floor(game.time%60)).padStart(2,'0')} / 第 ${game.wave} 波 · 收线 ${s.seals} · 回声 ${s.echoes} · 高阶协议 ${s.advanced}<p>伤害构成：回路 ${Math.round(s.damage.circuit/total*100)}%　回声 ${Math.round(s.damage.echo/total*100)}%　夺弹 ${Math.round(s.damage.returned/total*100)}%</p></div>`,'ACTION REPORT',false);footer([['查看构筑',showBuild],['返回大厅',lobby],['同种子再战',retry,true]]);return}
 }
 function retry(){
  const previousSeed=profile.seed,previous=game;
  hero=previous.hero;$('map').value=String(previous.endless?(previous.map-Math.floor((previous.wave-1)/8)%3+3)%3:previous.map);$('difficulty').value=String(previous.difficulty);$('endless').checked=previous.endless;
  profile.seed=previous.seed;start();profile.seed=previousSeed;store.save();
 }
 function showPause(){
  open('pause','暂停剪辑','进度已经保存。页面切到后台时，战斗也会暂停。','<div class="guide">◇ 补给币 '+game.coins+'　/　种子 '+game.seed+'<p>绕群 → 收线 → 把敌群引入紫色旧回路 → 回声。捕获弹幕能补充线能与超载。</p></div>','PAUSED');
  const buttons=[['设置',showSettings],['查看构筑',showBuild],['保存并回大厅',()=>{checkpoint();lobby()}]];
  if(!game.training)buttons.push(['结束并结算',()=>{open('retire','封存这次剪辑？','将按当前进度领取碎片，结束这次行动。未完成第八波不计入地图胜利。','<p class="guide">已经清算 '+game.kills+' 个敌人，抵达第 '+game.wave+' 波。也可以返回继续战斗，或保存进度稍后再玩。</p>','END ACTION');footer([['返回暂停',showPause],['确认结算',()=>{game.finish(false);checkpoint();sync(true)},true]])}]);
  buttons.push(['继续行动',close,true]);footer(buttons);
 }
 function pause(){if(!game)return;if(game.phase==='playing'){game.pause();checkpoint();sync(true)}else if(game.phase==='paused')close()}
 function showBuild(){if(!game)return;if(game.phase==='playing'){game.pause();checkpoint()}const entries=Object.entries(game.build);open('build','当前底稿 / 构筑',`共 ${entries.reduce((s,e)=>s+e[1],0)} 个协议层级 · 超载 ${Math.floor(game.p.charge)}%`,entries.length?'<div class="build-grid">'+entries.map(([id,lv])=>{const u=D.upgrades.find(u=>u.id===id);return`<div style="border-left:2px solid ${colors[u.group]}">${u.glyph} ${u.name} <b>×${lv}</b><small>${u.desc}</small></div>`}).join('')+'</div>':'<p class="guide">尚未获得协议。拾取紫色资料，或在波间购买协议数据。</p>','YOUR BUILD');const ev=game.events.map(id=>D.events.find(e=>e.id===id).name).join(' / ');if(ev)$('modal-body').insertAdjacentHTML('beforeend',`<p class="muted">异常合约：${ev}</p>`);if(game.wave<=game.mutations.rushUntil)$('modal-body').insertAdjacentHTML('beforeend',`<p class="bad muted">敌人加速持续至第 ${game.mutations.rushUntil} 波</p>`);if(game.wave<=game.mutations.dangerUntil)$('modal-body').insertAdjacentHTML('beforeend',`<p class="bad muted">敌人伤害提高持续至第 ${game.mutations.dangerUntil} 波</p>`);footer([['返回',()=>{if(['shop','result'].includes(game.phase))sync(true);else close()},true]])}
 function showMeta(){open('meta','义体工坊',`可用碎片 ◇ ${profile.wallet} · 强化在下一次新行动生效。`,'<div class="meta-grid">'+D.meta.map(m=>{const lv=profile.meta[m.id],cost=Math.round(m.cost*(1+lv*.65));return`<div class="row-card"><b>${m.glyph} ${m.name}　${lv}/${m.max}</b><p>${m.desc}</p><button data-meta="${m.id}" ${lv>=m.max||profile.wallet<cost?'disabled':''}>${lv>=m.max?'已经满级':`强化 · ◇ ${cost}`}</button></div>`}).join('')+'</div>','AUGMENT WORKSHOP');$('modal-body').onclick=e=>{const b=e.target.closest('[data-meta]');if(b&&store.upgrade(b.dataset.meta)){showMeta();refreshLobby()}};footer([['返回大厅',close,true]])}
 function showAchievements(){const s=profile.stats;open('achievements','城市档案',`行动 ${s.runs} 次 · 完成 ${s.wins} 次 · 清算 ${s.kills} 个敌人`,'<div class="meta-grid">'+D.achievements.map(a=>{const v=s[a.stat]||0,claimed=profile.claimed.includes(a.id);return`<div class="row-card ${claimed?'completed':''}"><b>${a.name}　${claimed?'✓':''}</b><p>${a.desc}　${Math.min(v,a.target)}/${a.target}</p><button data-claim="${a.id}" ${claimed||v<a.target?'disabled':''}>${claimed?'已领取':`领取 ◇ ${a.reward}`}</button></div>`}).join('')+'</div><p class="muted">'+D.maps.map((m,i)=>`${m.name} / 最高清算 ${profile.records[i]||0} / ${profile.maps.includes(i)?'已完成':'未完成'}`).join('<br>')+'<br>'+D.heroes.map(h=>`${h.name}完成 ${profile.heroes[h.id]||0} 次`).join(' · ')+'</p>','CITY ARCHIVE');$('modal-body').onclick=e=>{const b=e.target.closest('[data-claim]');if(b&&store.claim(b.dataset.claim)){showAchievements();refreshLobby()}};footer([['返回',close,true]])}
 function showGuide(){open('guide','规则研究 / 为什么这样玩','回路是实际坐标，闭环不是自动瞄准。','<div class="guide"><ol><li><b>织线：</b>移动留下轨迹。敌人穿过时挂线；弹丸碰到未烧损的轨迹时被截获。</li><li><b>收线：</b>末端与起点连接。圈内与边缘受到清算，圈外挂线敌人受到较低伤害。大面积、接缝命中与捕获弹珠提高输出。</li><li><b>回声：</b>上次回路在原来的位置重放。把敌人引回紫色旧影，再按 U。倒带回到本卷起点，取消当前轨迹并回收线能。</li><li><b>四种构筑：</b>大面积 + 线卷 → 镜像；刃宽 + 增幅 → 裂域；捕弹 + 充能 → 追踪弹幕；回声 + 记忆 → 双重曝光。</li><li><b>完成行动：</b>每波达到时间和击杀配额，并击败精英或首领。第 8 波解除封锁；无尽每八波换场景。首领半血进入二阶段。</li></ol><p>红圈与准星是敌人攻击预警，别站在圈里。粉色断线者会烧损旧线段，烧损处不再挂线或截获弹丸。轨迹达到容量时会自动尝试收线；可以开启自动收线辅助。</p><p>研究参考：<a href="https://store.steampowered.com/app/1942280/Brotato/" target="_blank" rel="noopener">Brotato</a> 的波次构筑、<a href="https://flanne.itch.io/10-minutes-till-dawn" target="_blank" rel="noopener">10 Minutes Till Dawn</a> 的主动射击，以及 <a href="https://www.ataricompendium.com/archives/manuals/5200/qix.pdf" target="_blank" rel="noopener">Qix</a> 的区域围合。本作探索“织线挂敌 + 截获返还 + 原位回声”的组合，没有宣称全球首创。</p><p class="muted">键盘：WASD / 方向键移动；J 或空格收线；K / Shift 闪避；U 回声；L 倒带；I 超载；H 治疗；P / Esc 暂停。手机支持八向摇杆与多指按钮，竖屏也可游玩。</p></div>','MECHANICS RESEARCH');footer([['返回',close,true]])}
 function showSettings(){if(game?.phase==='playing'){game.pause();checkpoint()}open('settings','剪辑设置','关闭音效也会静音配乐；低画质减少像素密度与碎片粒子。','<div class="settings">'+[['sound','战斗音效'],['music','原创电子节拍'],['vibrate','触控震动'],['numbers','伤害数字'],['auto','自动收线辅助']].map(([id,name])=>`<label>${name}<input data-setting="${id}" type="checkbox" ${settings[id]?'checked':''}></label>`).join('')+`<label>画质<select data-setting="quality"><option value="high" ${settings.quality==='high'?'selected':''}>高</option><option value="low" ${settings.quality==='low'?'selected':''}>省电</option></select></label></div><div class="seed-row"><label for="seed">下次行动种子</label><input id="seed" maxlength="32" placeholder="留空随机" value=""></div><p class="muted">同种子、角色、地图、难度与相同操作可以复现规则层随机结果。存档保存在此浏览器，与上一款游戏独立。</p>`,'PREFERENCES');$('seed').value=profile.seed||'';$('modal-body').onchange=e=>{if(e.target.dataset.setting){const id=e.target.dataset.setting;settings[id]=e.target.type==='checkbox'?e.target.checked:e.target.value;renderer.resize();store.save();updateHud()}if(e.target.id==='seed'){profile.seed=e.target.value;store.save()}};footer([['完成',close,true]])}
 document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{sound.unlock();({meta:showMeta,achievements:showAchievements,guide:showGuide,settings:showSettings})[b.dataset.menu]()});$('bag').onclick=showBuild;$('pause').onclick=pause;$('sound').onclick=()=>{sound.unlock();settings.sound=!settings.sound;store.save();updateHud()};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('shell').requestFullscreen();renderer.resize()}catch{notify('当前浏览器不支持全屏，可直接游玩')}};$('auto').onclick=()=>{settings.auto=!settings.auto;store.save();updateHud()};
 function action(id){if(!game||game.phase!=='playing')return;sound.unlock();const ok=game[id]();if(!ok){const p=game.p;const messages={echo:p.echoCd>0?'回声正在冷却':'先收线，留下一个旧回路',rewind:p.rewindCd>0?'倒带正在冷却':'先移动织出至少 80 长度',dash:'闪避正在冷却',overload:'击杀或捕弹，充满 100% 超载',heal:p.heals<=0?'治疗针剂已用完，波间可补给':'生命已满'};if(id!=='seal')notify(messages[id])}sync();updateHud()}
 document.querySelectorAll('[data-action]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);action(b.dataset.action)});b.onclick=e=>{if(e.detail===0)action(b.dataset.action)}});
 const joyEl=$('joystick');function joystick(e){const r=joyEl.getBoundingClientRect(),radius=r.width*.36,dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,n=Math.hypot(dx,dy)||1,f=Math.min(radius,n)/n;joy.x=dx*f/radius;joy.y=dy*f/radius;$('stick').style.transform=`translate(${joy.x*radius}px,${joy.y*radius}px)`}
 joyEl.addEventListener('pointerdown',e=>{if(joy.id!==null||game?.phase!=='playing')return;e.preventDefault();sound.unlock();joy.id=e.pointerId;joyEl.setPointerCapture(e.pointerId);joystick(e)});joyEl.addEventListener('pointermove',e=>{if(e.pointerId===joy.id)joystick(e)});for(const type of ['pointerup','pointercancel','lostpointercapture'])joyEl.addEventListener(type,e=>{if(e.pointerId===joy.id){joy.id=null;joy.x=joy.y=0;$('stick').style.transform='translate(0,0)'}});
 const actionKeys={j:'seal',' ':'seal',k:'dash',shift:'dash',u:'echo',l:'rewind',i:'overload',h:'heal'};window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(game&&(actionKeys[k]||['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','escape','p'].includes(k)))e.preventDefault();if(e.repeat)return;if(k==='escape'||k==='p'){if(menu&&game?.phase!=='playing')close();else pause();return}if(game?.phase!=='playing')return;keys.add(k);if(actionKeys[k])action(actionKeys[k])});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();if(game?.phase==='playing'){game.pause();checkpoint();sync(true)}});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden&&game){game.pause();checkpoint();sync(true)}});window.addEventListener('pagehide',checkpoint);
 function updateTutorial(){if(!game?.training){$('tutorial').hidden=true;return}const t=tutorial[game.tutorialStep];$('tutorial').hidden=!t;if(t)$('tutorial').innerHTML=`<b>${t[0]}</b>${t[1]}<br><small>${t[2]}</small>`}
 function updateHud(){if(!game)return;const p=game.p;$('hp-label').textContent=`${Math.ceil(p.hp)} / ${game.maxHp}　${game.heroData.name}`;$('hp-bar').style.width=p.hp/game.maxHp*100+'%';$('energy-bar').style.width=p.energy+'%';$('energy-label').textContent=`线能 ${Math.floor(p.energy)}　储弹 ${p.stored}/${game.capacity}`;$('wave-label').textContent=game.training?'TRAINING':`${String(game.wave).padStart(2,'0')} / ${game.endless?'∞':'08'}`;$('wave-progress').textContent=`${Math.min(Math.floor(game.waveTime),game.duration)}/${game.duration}s · ${game.waveKills}/${game.quota} 清算`;$('wave-bar').style.width=Math.min(1,Math.min(game.waveTime/game.duration,game.waveKills/game.quota))*100+'%';$('xp-bar').style.width=game.xp/game.xpNeed*100+'%';$('level').textContent=`LV.${game.level}　◇ ${game.coins}`;const v=game.preview();$('preview').textContent=`闭环 ${v.inside} 敌 / 挂线 ${v.marked}　·　线卷 ${Math.floor(v.length)}/${game.maxLength}`;$('auto').textContent='自动收线 '+(settings.auto?'ON':'OFF');$('auto').classList.toggle('active',settings.auto);$('sound').style.color=settings.sound?'#c1ff35':'#888';$('objective').querySelector('b').textContent=String(game.wave).padStart(2,'0');$('objective').querySelector('span').textContent=D.maps[game.map].name+' / '+(game.enemies.some(e=>e.boss||e.elite)?'击败封锁者':'时间与清算配额都要完成');const boss=game.enemies.find(e=>e.boss||e.elite);$('bossbar').hidden=!boss;if(boss){$('bossbar').querySelector('strong').textContent=(boss.boss?D.maps[game.map].boss:'断层守卫')+(boss.phase===2?' / 暴走':'' );$('bossbar').querySelector('i').style.width=Math.max(0,boss.hp/boss.maxHp)*100+'%'}
  for(const b of document.querySelectorAll('[data-action]')){const id=b.dataset.action,cd=p[`${id}Cd`]||0;let label={seal:`${game.sealCost()} 线能`,echo:'U',rewind:'L',dash:'K',heal:`× ${p.heals}`,overload:`${Math.floor(p.charge)}%`}[id];if(cd>0)label=cd.toFixed(1)+'s';b.querySelector('small').textContent=label;const max={seal:.48,echo:10,rewind:9,dash:2.5}[id];b.style.setProperty('--fill',(max?cd/max*100:id==='overload'?100-p.charge:0)+'%');b.classList.toggle('ready',id==='overload'&&p.charge>=100);b.disabled=game.phase!=='playing'}$('wave-progress').textContent=game.training?`步骤 ${Math.min(6,game.tutorialStep+1)} / 6 · 安全训练`:$('wave-progress').textContent;if(game.training){$('wave-bar').style.width=game.tutorialStep/6*100+'%';$('level').textContent='无损训练 / 正式存档独立';}updateTutorial();
 }
 let previous=performance.now();function frame(now){const dt=Math.min(.04,Math.max(0,(now-previous)/1000));previous=now;if(game){if(game.phase==='playing'&&!document.hidden){const x=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=joy.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);game.update(dt,{x,y},settings.auto);sound.update(game.time)}const signals=game.drain();renderer.handle(signals,game);for(const s of signals){sound.effect(s.type);if(s.type==='notice')notify(s.text);if(s.type==='boss')notify(s.name+' / 封锁接入');if(s.type==='bossPhase')notify(s.name+' / 二阶段暴走');if(s.type==='cut')notify('旧线被烧损，换一条路线');if(settings.vibrate&&['seal','hurt','overload'].includes(s.type)&&navigator.vibrate)navigator.vibrate(s.type==='hurt'?35:15)}sync();renderer.draw(game,document.hidden?0:dt);if(now-lastHud>100){updateHud();lastHud=now}if(now-lastSave>5000&&game.phase!=='result')checkpoint();if(signals.some(s=>s.type==='menu'||s.type==='wave'||s.type==='waveClear'||s.type==='result'))checkpoint()}
  if(now>noticeUntil)$('notice').classList.remove('show');requestAnimationFrame(frame)}
 refreshLobby();requestAnimationFrame(frame);
})();
