(function(){'use strict';const C={lime:'#c1ff35',violet:'#aa55ff',cyan:'#47e6f2',pink:'#ff459a'};
 class Renderer{
  constructor(canvas,settings){this.canvas=canvas;this.c=canvas.getContext('2d');this.settings=settings;this.fx=[];this.text=[];this.shake=0;this.cam={x:900,y:650};this.t=0;this.resize();window.addEventListener('resize',()=>this.resize())}
  resize(){this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;const ratio=Math.min(window.devicePixelRatio||1,this.settings.quality==='high'?2:1);this.canvas.width=Math.round(this.w*ratio);this.canvas.height=Math.round(this.h*ratio);this.ratio=ratio;this.zoom=this.w<700?.68:Math.min(1,Math.max(.68,this.h/820));}
  polygon(points,fill,stroke,width=1,close=true){if(!points.length)return;const c=this.c;c.beginPath();c.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))c.lineTo(p.x,p.y);if(close)c.closePath();if(fill){c.fillStyle=fill;c.fill('evenodd')}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke()}}
  circle(x,y,r,fill,stroke,width=1){const c=this.c;c.beginPath();c.arc(x,y,Math.max(0,r),0,Math.PI*2);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke()}}
  burst(x,y,color,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=70+Math.random()*220;this.fx.push({kind:'spark',x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.4+Math.random()*.3,max:.7,color})}}
  handle(signals,g){for(const s of signals){if(s.type==='loop'){this.fx.push({kind:'loop',loop:s.loop,life:.5,max:.5,color:s.source==='echo'?C.violet:g.heroData.color});this.shake=Math.max(this.shake,s.kills?5:2);if(s.kills>=4)this.text.push({x:s.loop.center.x,y:s.loop.center.y-60,label:`${s.kills} 连斩`,life:1.1,color:C.lime,big:true})}
   if(s.type==='hit'&&this.settings.numbers)this.text.push({x:s.x,y:s.y-25,label:String(s.value),life:.7,color:s.source==='echo'?C.violet:s.source==='returned'?C.cyan:'#e4f3c7'});
   if(s.type==='kill')this.burst(s.x,s.y,s.source==='returned'?C.cyan:g.heroData.color,this.settings.quality==='high'?14:6);
   if(s.type==='capture'){this.burst(s.x,s.y,C.cyan,5);this.fx.push({kind:'ring',x:s.x,y:s.y,r:25,life:.3,max:.3,color:C.cyan})}
   if(s.type==='mark')this.fx.push({kind:'ring',x:s.x,y:s.y,r:22,life:.25,max:.25,color:g.heroData.color});
   if(s.type==='hurt'){this.shake=9;this.fx.push({kind:'ring',x:s.x,y:s.y,r:50,life:.4,max:.4,color:C.pink})}
   if(['blast','cut'].includes(s.type))this.fx.push({kind:'ring',x:s.x,y:s.y,r:s.r,life:.5,max:.5,color:C.pink});
   if(s.type==='ray')this.fx.push({kind:'ray',from:s.from,to:s.to,life:.2,max:.2,color:C.cyan});
   if(s.type==='rewind')this.fx.push({kind:'loop',loop:{poly:s.path},life:.6,max:.6,color:C.violet});
   if(s.type==='dash'){this.burst(g.p.x,g.p.y,C.cyan,7)}
   if(s.type==='overload')this.fx.push({kind:'ring',x:g.p.x,y:g.p.y,r:380,life:1,max:1,color:C.pink});
  }if(this.fx.length>650)this.fx.splice(0,this.fx.length-650);if(this.text.length>90)this.text.splice(0,this.text.length-90)}
  floor(g){
   const key=g.id+'-'+g.map+'-'+g.obstacles.length;
   if(key!==this.floorKey){const layer=document.createElement('canvas');layer.width=1800;layer.height=1300;const output=this.c;this.c=layer.getContext('2d');this.paintFloor(g);this.c=output;this.floorLayer=layer;this.floorKey=key}
   this.c.drawImage(this.floorLayer,0,0);this.drawNodes(g);
  }
  paintFloor(g){const c=this.c,map=CIRCUIT_DATA.maps[g.map];c.fillStyle=['#1a2026','#211b2d','#16252c'][g.map];c.fillRect(0,0,1800,1300);
   for(let x=0;x<1800;x+=100)for(let y=0;y<1300;y+=100){c.fillStyle=(x+y)%300===0?'#ffffff03':'#00000009';c.fillRect(x+2,y+2,96,96)}
   c.strokeStyle='#8c9bb714';c.lineWidth=1;c.beginPath();for(let x=0;x<=1800;x+=100){c.moveTo(x,0);c.lineTo(x,1300)}for(let y=0;y<=1300;y+=100){c.moveTo(0,y);c.lineTo(1800,y)}c.stroke();
   c.fillStyle='#080a1060';c.fillRect(780,40,240,1220);c.fillRect(40,510,1720,260);c.strokeStyle='#ffffff10';c.lineWidth=3;c.setLineDash([20,30]);c.strokeRect(760,45,280,1210);c.setLineDash([]);
   if(g.map===0){for(const x of [120,145,1655,1680]){c.fillStyle='#101218';c.fillRect(x,40,10,1220);c.fillStyle='#555f6340';c.fillRect(x+2,40,2,1220)}for(let y=60;y<1260;y+=35){c.fillStyle='#0d1116';c.fillRect(115,y,50,5);c.fillRect(1650,y,50,5)}}
   if(g.map===1){for(let x=250;x<1750;x+=350)for(let y=180;y<1280;y+=350){this.polygon([{x,y:y-90},{x:x+90,y},{x,y:y+90},{x:x-90,y}],null,'#aa55ff14',2);this.circle(x,y,38,null,'#47e6f216',1)}}
   if(g.map===2){c.strokeStyle='#47e6f218';for(let y=60;y<1300;y+=190){c.beginPath();c.moveTo(30,y);c.lineTo(1770,y+80);c.stroke()}for(let x=80;x<1800;x+=250){c.fillStyle='#ffffff05';c.fillRect(x,100,100,35);c.fillRect(x,1150,100,35)}}
   c.strokeStyle=map.color+'60';c.lineWidth=4;c.strokeRect(26,26,1748,1248);c.fillStyle='#070b12';for(let x=60;x<1800;x+=150){c.fillRect(x,4,100,20);c.fillRect(x,1278,100,20);c.fillStyle=map.color+'80';c.fillRect(x+20,24,45,3);c.fillRect(x+20,1273,45,3);c.fillStyle='#070b12'}
   c.save();c.translate(900,650);c.rotate(-Math.PI/8);c.fillStyle='#ffffff05';c.font='italic 900 100px sans-serif';c.textAlign='center';c.fillText('CIRCUIT // RIOT',0,20);c.font='18px monospace';c.fillStyle=map.color+'33';c.fillText(map.tag,0,60);c.restore();
   for(const o of g.obstacles){c.fillStyle='#0006';c.fillRect(o.x+10,o.y+14,o.w,o.h);c.fillStyle='#0e121a';c.fillRect(o.x,o.y,o.w,o.h);c.fillStyle=['#38404b','#3f2d52','#25444c'][g.map];c.fillRect(o.x+3,o.y+3,o.w-6,o.h-14);c.fillStyle='#ffffff10';c.fillRect(o.x+9,o.y+8,o.w-18,5);c.strokeStyle='#ffffff12';c.lineWidth=1;for(let x=o.x+15;x<o.x+o.w-10;x+=12){c.beginPath();c.moveTo(x,o.y+22);c.lineTo(x,o.y+o.h-24);c.stroke()}c.fillStyle=map.color;c.fillRect(o.x+12,o.y+o.h-14,22,3);c.fillStyle='#ddd';c.font='9px monospace';c.fillText('HIGH VOLTAGE',o.x+45,o.y+o.h-11)}
  }
  drawNodes(g){const c=this.c;for(const n of g.nodes){const color=n.type==='energy'?C.cyan:n.type==='heal'?C.pink:C.violet;c.save();c.translate(n.x,n.y);c.globalAlpha=n.cd>0?.3:1;this.circle(0,0,38,'#10151a',color+'55',2);c.rotate(this.t*.2);this.polygon([{x:0,y:-28},{x:28,y:0},{x:0,y:28},{x:-28,y:0}],color+'10',color,2);c.rotate(-this.t*.2);c.font='bold 24px sans-serif';c.textAlign='center';c.fillStyle=color;c.fillText(n.type==='energy'?'ϟ':n.type==='heal'?'✚':'◇',0,8);c.font='10px monospace';c.fillStyle='#aeb6c4';c.fillText(n.cd>0?`${Math.ceil(n.cd)}s`:n.type==='energy'?'线能 +35':n.type==='heal'?'恢复 +18':'资料 +24',0,57);c.restore()}}
  path(g){const c=this.c,l=g.lastLoop;if(l){c.save();c.setLineDash([10,9]);this.polygon(l.poly,'#aa55ff07','#aa55ff4d',2);c.setLineDash([]);c.fillStyle='#bd85ee80';c.font='10px monospace';c.textAlign='center';c.fillText('旧回路 · U 重放',l.center.x,l.center.y);c.restore()}
   for(const f of g.fields)this.polygon(f.loop.poly,'#c1ff3512','#c1ff3540',2);
   const poly=[...g.path,{x:g.p.x,y:g.p.y}],key=g.id+'-'+g.path.length+'-'+Math.floor(this.t*10);
   if(key!==this.pathAreaKey){this.pathArea=CircuitCore.geometry.area(poly);this.pathAreaKey=key}if(this.pathArea>700)this.polygon(poly,g.heroData.color+'0a',null);
   for(let i=1;i<poly.length;i++){const a=poly[i-1],b=poly[i];if(b.cut){c.save();c.setLineDash([3,10]);c.strokeStyle='#ff459a55';c.lineWidth=2;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.restore();continue}c.strokeStyle=g.heroData.color+'18';c.lineWidth=g.lineWidth*2;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.strokeStyle=g.heroData.color;c.lineWidth=3;c.stroke();c.strokeStyle='#efffb1';c.lineWidth=1;c.stroke()}
   const start=poly[0];c.save();c.setLineDash([9,8]);c.strokeStyle=g.heroData.color+'60';c.lineWidth=2;c.beginPath();c.moveTo(g.p.x,g.p.y);c.lineTo(start.x,start.y);c.stroke();c.restore();this.circle(start.x,start.y,10,'#171e1a',g.heroData.color,2);c.fillStyle=g.heroData.color;c.font='9px monospace';c.textAlign='center';c.fillText('起点',start.x,start.y+22);
   for(let i=0;i<g.p.stored;i++){const index=Math.floor((i+1)/(g.p.stored+1)*(poly.length-1)),p=poly[index];this.circle(p.x,p.y,4+Math.sin(this.t*5+i),C.cyan,'#fff',1)}
  }
  warning(x,y,r,progress){const c=this.c;this.circle(x,y,r,'#ff459a12','#ff459a77',2);c.beginPath();c.arc(x,y,r*.8,-Math.PI/2,-Math.PI/2+Math.PI*2*progress);c.lineWidth=5;c.strokeStyle=C.pink;c.stroke();c.beginPath();c.moveTo(x-12,y);c.lineTo(x+12,y);c.moveTo(x,y-12);c.lineTo(x,y+12);c.lineWidth=2;c.stroke()}
  enemy(e,g){const c=this.c,x=e.x,y=e.y,angle=Math.atan2(g.p.y-y,g.p.x-x),s=e.r/20,color=e.boss?(e.type==='bossPrism'?C.violet:e.type==='bossClock'?C.cyan:C.pink):e.type==='gunner'?C.violet:e.type==='cutter'?C.pink:e.type==='fast'?C.cyan:'#f47387';
   c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#0005';c.beginPath();c.ellipse(3,12,23,12,0,0,Math.PI*2);c.fill();
   if(e.boss){c.save();c.rotate(this.t*(e.phase===2?-1:1)*.5);this.polygon([{x:-40,y:-20},{x:0,y:-45},{x:40,y:-20},{x:40,y:20},{x:0,y:45},{x:-40,y:20}],null,color+'80',2);c.restore();this.circle(0,0,29,color+'16',color,2);c.save();c.rotate(angle);this.polygon([{x:-20,y:-22},{x:18,y:-30},{x:32,y:0},{x:18,y:30},{x:-20,y:22}],e.flash>0?'#fff':'#212737',color,2);this.polygon([{x:20,y:-14},{x:40,y:0},{x:20,y:14}],'#0d131b',color,2);c.fillStyle=color;c.fillRect(23,-6,8,12);for(let i=-1;i<=1;i++){c.fillStyle='#0b1017';c.fillRect(-18,-24+i*22,9,10)}c.restore();if(e.phase===2)this.circle(0,0,35,null,color+'aa',3)}
   else if(e.type==='mine'){c.save();c.rotate(this.t*2);this.polygon([{x:0,y:-20},{x:15,y:-10},{x:18,y:10},{x:0,y:21},{x:-18,y:10},{x:-15,y:-10}],e.flash>0?'#fff':'#382633',color,2);c.restore();this.circle(0,0,6,e.wind>0?'#fff':C.pink);}
   else{c.rotate(angle+Math.PI/2);const step=Math.sin(e.age*10)*5;c.fillStyle='#10151e';c.fillRect(-12,8,8,12+step);c.fillRect(4,8,8,12-step);this.polygon([{x:-17,y:-7},{x:-12,y:13},{x:12,y:13},{x:17,y:-7},{x:8,y:-14},{x:-8,y:-14}],e.flash>0?'#fff':e.type==='tank'?'#465062':'#2b3245',color,1.5);c.fillStyle=color;c.fillRect(-13,-8,6,13);c.fillRect(7,-8,6,13);this.polygon([{x:-10,y:-10},{x:-8,y:-23},{x:7,y:-25},{x:12,y:-15},{x:6,y:-8}],'#171824',color,1);c.fillStyle=e.flash>0?'#fff':color;c.fillRect(-7,-19,14,4);if(e.type==='gunner'){c.fillStyle='#0c131e';c.fillRect(17,-22,8,23);c.fillStyle=color;c.fillRect(17,-24,8,5)}if(e.type==='cutter'){this.polygon([{x:-20,y:3},{x:-27,y:-28},{x:-21,y:-39},{x:-16,y:-10}],color,'#fff',1)}if(e.type==='fast'){this.polygon([{x:-18,y:10},{x:-24,y:27},{x:-11,y:19}],color,null);this.polygon([{x:18,y:10},{x:24,y:27},{x:11,y:19}],color,null)}}
   c.restore();if(e.mark){this.circle(x,y,e.r+5,null,g.heroData.color+'88',1.5);c.fillStyle=g.heroData.color;c.font='bold 10px monospace';c.textAlign='center';c.fillText('▴'.repeat(e.mark),x,y-e.r-10)}if(e.freeze>0)this.circle(x,y,e.r+10,'#47e6f215',C.cyan,2);
   if(e.hp<e.maxHp||e.elite||e.boss){c.fillStyle='#090e17';c.fillRect(x-e.r,y-e.r-19,e.r*2,4);c.fillStyle=color;c.fillRect(x-e.r,y-e.r-19,e.r*2*Math.max(0,e.hp/e.maxHp),4)}if(e.wind>0)this.warning(e.tx??x,e.ty??y,e.boss?(e.type==='bossCutter'?210:90):e.mode==='cut'?150:e.type==='mine'?115:e.r+28,1-Math.min(1,e.wind));
  }
  player(g){const c=this.c,p=g.p,color=g.heroData.color;const angle=Math.atan2(p.dirY,p.dirX);c.save();c.translate(p.x,p.y);if(p.inv>0&&Math.floor(this.t*18)%2===0)c.globalAlpha=.65;this.circle(0,0,p.overload>0?35:24,color+'0b',color+'77',1);c.fillStyle='#0008';c.beginPath();c.ellipse(4,14,20,10,0,0,Math.PI*2);c.fill();c.rotate(angle+Math.PI/2);const walk=Math.sin(this.t*17)*4;c.fillStyle='#090d16';c.fillRect(-11,7,8,15+walk);c.fillRect(3,7,8,15-walk);c.fillStyle=color;c.fillRect(-11,18+walk,8,4);c.fillRect(3,18-walk,8,4);this.polygon([{x:-19,y:-6},{x:-10,y:15},{x:8,y:13},{x:20,y:-4},{x:9,y:-16},{x:-10,y:-13}],'#141827',color,2);this.polygon([{x:-17,y:-9},{x:-5,y:-10},{x:2,y:8},{x:-10,y:6}],color,null);c.fillStyle='#faf5d7';c.fillRect(-8,-20,15,10);this.polygon([{x:-11,y:-19},{x:-7,y:-30},{x:7,y:-31},{x:14,y:-22},{x:5,y:-17},{x:1,y:-24},{x:-5,y:-17}],g.hero===1?'#e666de':g.hero===2?'#576681':'#cdd8dd',null);c.fillStyle='#14151d';c.fillRect(-7,-15,13,3);c.fillStyle='#1d2537';c.fillRect(15,-12,8,13);this.circle(20,-9,7,'#10161b',color,2);this.polygon([{x:22,y:-14},{x:33,y:-43},{x:38,y:-48},{x:29,y:-9}],color,'#f4ffcf',1);if(p.dash>0){c.fillStyle=color+'44';c.fillRect(-10,22,20,40)}c.restore();if(p.overload>0)this.circle(p.x,p.y,38+Math.sin(this.t*8)*4,null,C.pink,2)}
  draw(g,dt){const c=this.c;this.t+=dt;this.fx.forEach(f=>{f.life-=dt;if(f.kind==='spark'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.96;f.vy*=.96}});this.text.forEach(t=>{t.life-=dt;t.y-=dt*25});this.fx=this.fx.filter(f=>f.life>0);this.text=this.text.filter(t=>t.life>0);this.shake=Math.max(0,this.shake-dt*25);if(!g)return;c.setTransform(this.ratio,0,0,this.ratio,0,0);c.clearRect(0,0,this.w,this.h);
   const viewW=this.w/this.zoom,viewH=this.h/this.zoom,clamp=(n,a,b)=>a>b?(a+b)/2:Math.min(b,Math.max(a,n));this.cam.x+=(clamp(g.p.x,viewW/2-40,1840-viewW/2)-this.cam.x)*Math.min(1,dt*10);this.cam.y+=(clamp(g.p.y,viewH/2-40,1340-viewH/2)-this.cam.y)*Math.min(1,dt*10);
   c.save();c.translate(this.w/2,this.h/2);c.scale(this.zoom,this.zoom);c.translate(-this.cam.x+(Math.random()-.5)*this.shake,-this.cam.y+(Math.random()-.5)*this.shake);this.floor(g);this.path(g);
   for(const d of g.drops){this.polygon([{x:d.x,y:d.y-5},{x:d.x+5,y:d.y},{x:d.x,y:d.y+5},{x:d.x-5,y:d.y}],d.type==='heal'?C.pink:C.violet,null)}
   for(const w of g.warnings)this.warning(w.x,w.y,w.r,Math.max(0,1-w.delay));
   const entities=[...g.enemies.map(e=>({y:e.y,draw:()=>this.enemy(e,g)})),{y:g.p.y,draw:()=>this.player(g)}].sort((a,b)=>a.y-b.y);entities.forEach(e=>e.draw());
   for(const b of g.bullets){const color=b.friendly?C.cyan:C.pink;c.strokeStyle=color+'77';c.lineWidth=3;c.beginPath();c.moveTo(b.x-b.vx*.03,b.y-b.vy*.03);c.lineTo(b.x,b.y);c.stroke();this.circle(b.x,b.y,b.r,color);this.circle(b.x,b.y,2,'#fff')}
   for(const f of this.fx){c.save();c.globalAlpha=Math.min(1,f.life/f.max);if(f.kind==='loop'){this.polygon(f.loop.poly,f.color+'28',f.color,5);c.strokeStyle='#fff';c.lineWidth=1;this.polygon(f.loop.poly,null,'#fff',1)}if(f.kind==='ring')this.circle(f.x,f.y,f.r*(1-f.life/f.max*.5),null,f.color,4);if(f.kind==='spark'){c.fillStyle=f.color;c.save();c.translate(f.x,f.y);c.rotate(f.vx);c.fillRect(-3,-1,9,3);c.restore()}if(f.kind==='ray'){c.strokeStyle=f.color;c.lineWidth=4;c.beginPath();c.moveTo(f.from.x,f.from.y);c.lineTo(f.to.x,f.to.y);c.stroke()}c.restore()}
   for(const t of this.text){c.globalAlpha=Math.min(1,t.life*3);c.font=t.big?'italic 900 29px sans-serif':'bold 14px monospace';c.textAlign='center';c.strokeStyle='#111';c.lineWidth=3;c.strokeText(t.label,t.x,t.y);c.fillStyle=t.color;c.fillText(t.label,t.x,t.y)}c.globalAlpha=1;c.restore();
   // A small radar makes distant threats and the old circuit readable on a phone.
   if(this.w>=700){const rx=this.w/2-75,ry=this.h-90;c.fillStyle='#0d1019c0';c.fillRect(rx,ry,150,75);c.strokeStyle='#ffffff20';c.strokeRect(rx,ry,150,75);for(const e of g.enemies){c.fillStyle=e.boss?C.pink:'#ff809780';c.fillRect(rx+e.x/1800*150,ry+e.y/1300*75,e.boss?4:2,e.boss?4:2)}c.fillStyle=g.heroData.color;c.fillRect(rx+g.p.x/1800*150-2,ry+g.p.y/1300*75-2,4,4)}
   for(const e of g.enemies.filter(e=>e.boss||e.elite)){const sx=(e.x-this.cam.x)*this.zoom+this.w/2,sy=(e.y-this.cam.y)*this.zoom+this.h/2;if(sx<40||sx>this.w-40||sy<60||sy>this.h-100){const a=Math.atan2(sy-this.h/2,sx-this.w/2);c.save();c.translate(Math.max(30,Math.min(this.w-30,sx)),Math.max(160,Math.min(this.h-220,sy)));c.rotate(a);this.polygon([{x:10,y:0},{x:-6,y:-7},{x:-6,y:7}],C.pink,null);c.restore()}}
  }
 }
 window.CircuitRenderer=Renderer;
})();
