/* Deterministic engine regression checks; node tests/neon-reaping.test.cjs */
const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'..');
function harness(seed=42,storage=new Map()){
  const elements=new Map(),events={};let raf=[];
  const context2d=new Proxy({createLinearGradient:()=>({addColorStop(){}})}, {get:(o,k)=>k in o?o[k]:()=>{}});
  class Element{constructor(id){this.id=id;this.dataset={};this.style={};this.innerHTML='';this.textContent='';this.listeners={};this.tagName='BUTTON';this.disabled=false;this.classList={add(){},remove(){},toggle(){}}}addEventListener(e,fn){(this.listeners[e]||=[]).push(fn)}querySelector(){return new Element('child')}getContext(){return context2d}focus(){}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,width:150,height:150}}}
  const el=id=>{if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id)};
  const controls=['heal','ult','skill','dash','jump','attack','drop'].map(id=>{const b=el('control-'+id);b.dataset.control=id;return b});
  const document={getElementById:el,querySelector:s=>el(s),querySelectorAll:()=>controls,hidden:false,addEventListener:(e,fn)=>(events[e]||=[]).push(fn),documentElement:{requestFullscreen:async()=>{}},fullscreenElement:null};
  let randomSeed=seed;const math=Object.create(Math);math.random=()=>{randomSeed=(randomSeed*1664525+1013904223)>>>0;return randomSeed/4294967296};
  const window={innerWidth:1280,innerHeight:720,devicePixelRatio:1,__RIFT_TEST__:true,addEventListener(){}};
  const sandbox={window,document,Math:math,navigator:{},screen:{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},requestAnimationFrame:fn=>{raf.push(fn)},setTimeout:()=>0,clearTimeout(){},console,Date,JSON};
  vm.createContext(sandbox);vm.runInContext(readFileSync(path.join(root,'tools/neon-reaping/data.js'),'utf8'),sandbox);vm.runInContext(readFileSync(path.join(root,'tools/neon-reaping/game.js'),'utf8'),sandbox);
  return {api:window.RiftTest,D:window.RIFT_DATA,storage,frame:t=>{const q=raf;raf=[];q.forEach(f=>f(t))},click:dataset=>{const b=new Element('fake');b.dataset=dataset;for(const f of events.click||[])f({target:{closest:()=>b}})},key:(code,down=true)=>{for(const f of events[down?'keydown':'keyup']||[])f({code,repeat:false,target:{tagName:'BODY'},preventDefault(){}})},element:el};
}
let count=0;function test(name,fn){fn();console.log('PASS',name);count++}
test('All 24 upgrades and six valid evolution pairs',()=>{const {D}=harness();assert.equal(D.upgrades.length,24);assert.equal(new Set(D.upgrades.map(i=>i.id)).size,24);assert.equal(D.upgrades.filter(i=>i.weapon).length,6);for(const i of D.upgrades.filter(i=>i.weapon))assert(D.upgrades.some(p=>p.id===i.pair))});
test('Melee combo kills, credits, drops and ultimate charge',()=>{const {api}=harness();api.newGame();const g=api.getGame();const e=api.spawnEnemy('runner');e.x=g.p.x+45;e.y=0;e.hp=10;api.attack();assert.equal(g.kills,1);assert(g.drops.length);assert(g.coins>0);assert(g.p.ult>0);assert.equal(g.waveKills,1)});
test('Dash immunity, armor and shield prevent or mitigate damage',()=>{const {api}=harness();api.newGame();const g=api.getGame();g.p.inv=0;api.action('dash');api.hurtPlayer(30,g.p.x,-30);assert.equal(g.p.hp,140);g.p.inv=0;g.p.shield=1;api.hurtPlayer(30,g.p.x,-30);assert.equal(g.p.hp,140);assert.equal(g.p.shield,0);g.p.inv=0;g.build.armor=5;api.hurtPlayer(30,g.p.x,-30);assert.equal(g.p.hp,125)});
test('Double jump is capped, healing consumes only when effective',()=>{const {api}=harness();api.newGame();const g=api.getGame();api.action('jump');api.action('jump');api.action('jump');assert.equal(g.p.jumps,2);api.action('heal');assert.equal(g.p.heals,2);g.p.hp=40;api.action('heal');assert.equal(g.p.heals,1);assert.equal(g.p.hp,96)});
test('All three heroes use separate attacks, skills and ultimate',()=>{for(let hero=0;hero<3;hero++){const h=harness();h.click({hero:String(hero)});h.api.newGame(true);const g=h.api.getGame();h.api.spawnEnemy('tank').x=g.p.x+40;h.api.attack();h.api.action('skill');assert(g.p.skillCd>0);g.p.ult=100;h.api.action('ult');assert(g.p.ult<100);assert(g.p.inv>0);if(hero>0)assert(g.bullets.length>0)}});
test('Upgrade selection and all six awakenings persist',()=>{const {api,D}=harness();api.newGame();const g=api.getGame();for(const w of D.upgrades.filter(i=>i.weapon)){g.build[w.id]=4;g.build[w.pair]=1;g.pendingLevels=1;g.choices=[w.id];api.showUpgrade();api.selectUpgrade(w.id);assert(g.evolved.includes(w.id))}assert.equal(g.evolutions,6);assert.equal(api.getState(),'playing')});
test('Three unique upgrade choices, reroll and upgrade checkpoint survive reload',()=>{const h=harness();h.api.newGame();h.api.addXp(300);h.api.showUpgrade();const g=h.api.getGame();assert.equal(new Set(g.choices).size,3);h.api.persistRun();const checkpoint=g.pendingLevels,choices=[...g.choices];const r=harness(22,h.storage);r.api.resumeRun();assert.equal(r.api.getState(),'upgrade');assert.equal(r.api.getGame().pendingLevels,checkpoint);assert.deepEqual([...r.api.getGame().choices],choices);r.click({action:'reroll'});assert.equal(r.api.getGame().rerolls,2)});
test('Free supply is once per wave, shop purchases do not repeat',()=>{const h=harness();h.api.newGame();const g=h.api.getGame();g.waveKills=18;g.p.hp=50;h.api.clearWave();assert.equal(h.api.getState(),'shop');h.api.buyShop('free');const hp=g.p.hp;h.api.buyShop('free');assert.equal(g.p.hp,hp);g.coins=100;h.api.buyShop('kit');assert.equal(g.coins,55);h.api.buyShop('kit');assert.equal(g.coins,55);h.click({action:'nextWave'});assert.equal(g.wave,2);assert.equal(h.api.getState(),'playing')});
test('Boss variants spawn and enter second phase',()=>{for(let ch=0;ch<3;ch++){const h=harness();h.api.newGame();const g=h.api.getGame();g.chapter=ch;g.wave=6;h.api.startWave();h.api.updateGame(.016);const boss=g.enemies.find(e=>e.boss);assert.equal(boss.type,['charger','bossGunner','summoner'][ch]);boss.hp=boss.maxHp*.45;h.api.updateGame(.016);assert.equal(boss.phase,2);assert(boss.phaseNotified)}});
test('Save resume and once-only settlement/achievement reward',()=>{const h=harness();h.api.newGame();let g=h.api.getGame();g.kills=160;g.bestCombo=55;g.coins=81;h.api.persistRun();const r=harness(8,h.storage);r.api.resumeRun();g=r.api.getGame();assert.equal(g.kills,160);assert.equal(g.coins,81);r.api.finish(true);const coins=r.api.getSave().coins;r.api.finish(true);assert.equal(r.api.getSave().coins,coins);assert(!r.storage.has('rift-riot-run-v1'));r.api.goLobby();r.click({action:'achievements'});r.click({achievement:'first'});assert.equal(r.api.getSave().coins,coins+80);r.click({achievement:'first'});assert.equal(r.api.getSave().coins,coins+80)});
test('Trial preserves existing run and pays no permanent reward',()=>{const h=harness();h.api.newGame();const original=h.storage.get('rift-riot-run-v1');h.api.newGame(true);h.api.getGame().kills=100;h.api.finish(true);assert.equal(h.api.getSave().coins,0);assert.equal(h.api.getSave().stats.kills,0);assert.equal(h.storage.get('rift-riot-run-v1'),original)});
test('Pause freezes simulation, snapshot resumes combat safely',()=>{const h=harness();h.api.newGame();h.frame(16);h.api.openMenu('pause');const time=h.api.getGame().totalTime;h.frame(32);h.frame(1000);assert.equal(h.api.getGame().totalTime,time);h.api.backMenu();assert.equal(h.api.getState(),'playing');h.frame(1016);assert(h.api.getGame().totalTime>time)});
test('Daily reward cannot be claimed twice',()=>{const h=harness();h.api.getSave().daily.kills=160;h.click({action:'missions'});h.click({mission:'kills'});assert.equal(h.api.getSave().coins,90);h.click({mission:'kills'});assert.equal(h.api.getSave().coins,90)});
test('Platform drop input crosses the platform and lands on the floor',()=>{const h=harness();h.api.newGame();const g=h.api.getGame();g.p.x=700;g.p.y=-105;g.p.vy=0;h.key('KeyS');for(let i=0;i<40;i++)h.api.updateGame(1/60);assert.equal(g.p.y,0);assert.equal(g.p.jumps,0)});
test('Multi-pointer move and attack cancel independently',()=>{const h=harness();h.api.newGame();const g=h.api.getGame(),joystick=h.element('joystick'),attack=h.element('control-attack');const event=(id,x)=>({pointerId:id,clientX:x,preventDefault(){}});joystick.listeners.pointerdown[0](event(1,120));attack.listeners.pointerdown[0](event(2,0));const start=g.p.x;h.api.updateGame(.03);assert(g.p.x>start);attack.listeners.pointerup[0](event(2,0));h.api.updateGame(.03);assert(g.p.x>start+8);joystick.listeners.pointercancel[0](event(1,0));const stop=g.p.x;h.api.updateGame(.03);assert.equal(g.p.x,stop)});
test('Committed result cannot be paid again from a stale run after reload',()=>{const h=harness();h.api.newGame();h.api.getGame().kills=50;h.api.persistRun();const stale=h.storage.get('rift-riot-run-v1');h.api.finish(true);const coins=h.api.getSave().coins;h.storage.set('rift-riot-run-v1',stale);const r=harness(7,h.storage);r.api.resumeRun();r.api.finish(true);assert.equal(r.api.getSave().coins,coins);assert.equal(r.api.getSave().stats.runs,1)});
test('Endless wave 12 continues, finite chapter wave 6 settles',()=>{const h=harness();h.api.newGame();let g=h.api.getGame();g.chapter=3;g.wave=12;g.waveKills=100;h.api.clearWave();assert.equal(h.api.getState(),'shop');h.click({action:'nextWave'});assert.equal(g.wave,13);g.chapter=2;g.wave=6;g.waveKills=100;h.api.clearWave();assert.equal(h.api.getState(),'result');assert.equal(h.api.getSave().stats.chapter,3)});
test('Canvas renderer survives all effects, weapons and enemy archetypes',()=>{const h=harness();h.api.newGame();const g=h.api.getGame();for(const w of h.D.upgrades)g.build[w.id]=w.max;g.evolved=h.D.upgrades.filter(i=>i.weapon).map(i=>i.id);for(const t of ['runner','fast','tank','gunner','fly','bomb','charger','bossGunner','summoner'])h.api.spawnEnemy(t,['charger','bossGunner','summoner'].includes(t));h.api.action('skill');g.p.ult=100;h.api.action('ult');h.frame(16);h.frame(32);h.frame(48)});
console.log(`\n${count} regression checks passed.`);

// A real-time-rule bot runs the actual engine, with baseline hp and no injected damage.
// It uses normal attacks, movement, healing, cooldowns and earned upgrades.
function simulate(ch,hero,seed){const h=harness(seed);h.click({hero:String(hero)});h.api.newGame();const g=h.api.getGame();g.chapter=ch;
  const priority=['bladeOrbit','range','damage','haste','lightning','crit','hp','regen','armor','leech','fire','magnet','multi','skill','shield'];let frames=0;
  while(h.api.getState()!=='result'&&frames++<60*900){const state=h.api.getState();if(state==='upgrade'){const opts=g.choices;let best=opts.find(id=>h.D.upgrades.find(i=>i.id===id).weapon&&g.build[id]>=4)||priority.find(id=>opts.includes(id))||opts[0];h.api.selectUpgrade(best);continue}if(state==='shop'){h.api.buyShop('free');if(g.p.hp<h.api.maxHp()*.8)h.api.buyShop('heal');if(g.coins>=65&&!g.shopUsed.includes('upgrade')){h.api.buyShop('upgrade');continue}h.click({action:'nextWave'});continue}
    const nearest=g.enemies.filter(e=>!e.dead).sort((a,b)=>Math.abs(a.x-g.p.x)-Math.abs(b.x-g.p.x))[0];h.key('KeyA',false);h.key('KeyD',false);if(nearest){const dx=nearest.x-g.p.x;if(g.p.y<-80&&nearest.y===0)h.api.action('drop');if(Math.abs(dx)>100)h.key(dx>0?'KeyD':'KeyA');if(nearest.wind>0&&Math.abs(dx)<180){h.api.action('dash');h.api.action('jump')}}
    h.api.action('skill');if(g.p.ult>=100)h.api.action('ult');if(g.p.hp<h.api.maxHp()*.4)h.api.action('heal');h.api.updateGame(1/60);
  }
  return {chapter:ch+1,hero:h.D.heroes[hero].name,seed,won:g.won||false,wave:g.wave,kills:g.kills,seconds:Math.round(g.totalTime),hp:Math.round(g.p.hp),level:g.level,evolved:g.evolved};
}
for(const [ch,hero,seed] of [[0,0,42],[0,1,43],[0,2,44],[1,0,45],[2,0,46]]){const result=simulate(ch,hero,seed);assert(result.won,`Baseline action bot cannot complete ${JSON.stringify(result)}`);console.log('BALANCE',JSON.stringify(result))}



