(function(root,factory){const d=typeof module==='object'?require('./content.js'):root.PineContent;const c=factory(d);if(typeof module==='object')module.exports=c;else root.PineCore=c})(typeof window==='undefined'?globalThis:window,D=>{
'use strict';const copy=x=>JSON.parse(JSON.stringify(x)),MAX_OFFLINE=43200000,KEY='pine-haven-profile-v1';
const integer=(x,max=1e9)=>Number.isSafeInteger(x)&&x>=0&&x<=max;const set=(x,max)=>Array.isArray(x)&&x.every(n=>integer(n,max-1))&&new Set(x).size===x.length;
class Game{
 constructor({clock=()=>Date.now(),seed=Date.now()}={}){this.clock=clock;const now=clock();this.s={version:1,stamp:now,created:now,rng:(Number(seed)>>>0)||1729,coins:160,pending:0,progress:0,stock:Object.fromEntries(D.stockIds.map(k=>[k,0])),plots:Array.from({length:4},(_,n)=>({crop:n%2?'wheat':'berry',next:now+(n%2?75000:45000)})),jobs:[],jobId:0,trip:null,friends:Array(8).fill(0),wishes:[],letters:[],owned:[0],placed:[0,null,null,null,null,null],finds:[],read:[],ending:false,settings:{sound:false,motion:true,phase:'day'},stats:{harvests:0,crafted:0,trips:0,served:0},intro:true};Object.assign(this.s.stock,{berry:5,wheat:5,tea:2,wood:5,berrycake:2,toast:2})}
 get rate(){return .6+this.s.progress*.14}
 tick(){const now=this.clock();if(now<=this.s.stamp)return;const elapsed=Math.min(MAX_OFFLINE,now-this.s.stamp);this.s.pending+=elapsed/1000*this.rate;const end=this.s.stamp+elapsed;for(const p of this.s.plots){if(p.next<=end){const d=D.crops.find(x=>x.id===p.crop),cycles=1+Math.floor((end-p.next)/(d.seconds*1000));this.s.stock[p.crop]+=cycles;p.next+=cycles*d.seconds*1000}p.next+=now-end}this.s.stamp=now}
 random(){this.s.rng=(Math.imul(this.s.rng,1664525)+1013904223)>>>0;return this.s.rng/4294967296}
 collect(){this.tick();const n=Math.floor(this.s.pending);if(!n)return false;this.s.pending-=n;this.s.coins+=n;this.s.stats.harvests++;return n}
 plant(index,crop){this.tick();const d=D.crops.find(x=>x.id===crop);if(!integer(index,3)||!d||this.s.progress<d.unlock)return false;const p=this.s.plots[index];if(p.crop===crop)return true;p.crop=crop;p.next=this.s.stamp+d.seconds*1000;return true}
 canMake(id){const r=D.recipes.find(x=>x.id===id);return!!r&&this.s.progress>=r.unlock&&this.s.jobs.length<3&&Object.entries(r.needs).every(([k,n])=>this.s.stock[k]>=n)}
 make(id){this.tick();if(!this.canMake(id))return false;const r=D.recipes.find(x=>x.id===id);for(const[k,n]of Object.entries(r.needs))this.s.stock[k]-=n;this.s.jobs.push({id:++this.s.jobId,recipe:id,end:this.s.stamp+r.seconds*1000});return true}
 claimJob(id){this.tick();const n=this.s.jobs.findIndex(j=>j.id===id&&j.end<=this.s.stamp);if(n<0)return false;const[j]=this.s.jobs.splice(n,1);this.s.stock[j.recipe]++;this.s.stats.crafted++;return true}
 build(){this.tick();const b=D.builds[this.s.progress];if(!b||this.s.coins<b.cost)return false;this.s.coins-=b.cost;this.s.progress++;for(const f of D.furniture)if(f.gift&&f.unlock<=this.s.progress&&!this.s.owned.includes(f.id))this.s.owned.push(f.id);if(this.s.progress===24&&!this.s.ending){this.s.ending=true;this.s.coins+=300;this.s.stock.picnic+=2}return b}
 serve(n,id){this.tick();const f=D.friends[n],r=D.recipes.find(x=>x.id===id);if(!f||this.s.progress<f.unlock||!r||!this.s.stock[id])return false;this.s.stock[id]--;this.s.friends[n]=Math.min(12,this.s.friends[n]+(id===f.favorite?2:1));this.s.coins+=id===f.favorite?30:15;this.s.stats.served++;return true}
 wish(id){this.tick();const w=D.wishes[id];if(!w||this.s.wishes.includes(id)||this.s.progress<D.friends[w.friend].unlock||this.s.stock[w.recipe]<w.qty)return false;this.s.stock[w.recipe]-=w.qty;this.s.wishes.push(id);this.s.coins+=w.coins;this.s.friends[w.friend]=Math.min(12,this.s.friends[w.friend]+2);return true}
 letter(id){const n=Math.floor(id/3),stage=id%3;if(!integer(id,23)||this.s.friends[n]<[3,6,12][stage])return false;if(!this.s.letters.includes(id))this.s.letters.push(id);return true}
 travel(id){this.tick();const t=D.trips[id];if(!t||this.s.trip||this.s.progress<t.unlock)return false;this.s.trip={id,end:this.s.stamp+t.seconds*1000};return true}
 claimTrip(){this.tick();const t=this.s.trip;if(!t||t.end>this.s.stamp)return false;const d=D.trips[t.id],n=d.range[0]+Math.floor(this.random()*(d.range[1]-d.range[0]));this.s.trip=null;const fresh=!this.s.finds.includes(n);if(fresh)this.s.finds.push(n);else this.s.coins+=20;this.s.stock.wood+=3+t.id;this.s.stock[D.crops[Math.floor(this.random()*6)].id]+=2;this.s.coins+=30;this.s.stats.trips++;return{find:n,fresh}}
 buy(id){this.tick();const f=D.furniture[id];if(!f||f.gift||this.s.owned.includes(id)||this.s.progress<f.unlock||this.s.coins<f.cost)return false;this.s.coins-=f.cost;this.s.owned.push(id);return true}
 place(slot,id){if(!integer(slot,5)||id!==null&&(!integer(id,23)||!this.s.owned.includes(id)))return false;this.s.placed[slot]=id;return true}
 read(id){if(!integer(id,23)||id>=this.s.progress)return false;if(!this.s.read.includes(id))this.s.read.push(id);return true}
 serialize(){return copy(this.s)}
 static restore(raw,o={}){try{const s=copy(raw);if(!s||s.version!==1||!integer(s.stamp,Number.MAX_SAFE_INTEGER)||!integer(s.created,Number.MAX_SAFE_INTEGER)||s.created>s.stamp||!integer(s.rng,4294967295)||!integer(s.coins)||!Number.isFinite(s.pending)||s.pending<0||s.pending>1e9||!integer(s.progress,24)||!s.stock||Object.keys(s.stock).sort().join()!==D.stockIds.slice().sort().join()||!Object.values(s.stock).every(x=>integer(x)))return null;if(!Array.isArray(s.plots)||s.plots.length!==4||!s.plots.every(p=>p&&Object.keys(p).sort().join()==='crop,next'&&D.crops.some(c=>c.id===p.crop&&s.progress>=c.unlock)&&integer(p.next,Number.MAX_SAFE_INTEGER))||!Array.isArray(s.jobs)||s.jobs.length>3||!integer(s.jobId)||!s.jobs.every(j=>j&&Object.keys(j).sort().join()==='end,id,recipe'&&integer(j.id,s.jobId)&&j.id>0&&D.recipes.some(r=>r.id===j.recipe&&r.unlock<=s.progress)&&integer(j.end,Number.MAX_SAFE_INTEGER))||new Set(s.jobs.map(j=>j.id)).size!==s.jobs.length)return null;if(s.trip!==null&&(!s.trip||Object.keys(s.trip).sort().join()!=='end,id'||!integer(s.trip.id,2)||s.progress<D.trips[s.trip.id].unlock||!integer(s.trip.end,Number.MAX_SAFE_INTEGER)))return null;if(!Array.isArray(s.friends)||s.friends.length!==8||!s.friends.every(x=>integer(x,12))||!set(s.wishes,24)||!set(s.letters,24)||!set(s.owned,24)||!s.owned.includes(0)||!set(s.finds,20)||!set(s.read,24)||s.read.some(x=>x>=s.progress)||s.letters.some(x=>s.friends[Math.floor(x/3)]<[3,6,12][x%3])||!Array.isArray(s.placed)||s.placed.length!==6||s.placed.some(x=>x!==null&&!s.owned.includes(x))||typeof s.ending!=='boolean'||s.ending!==(s.progress===24)||typeof s.intro!=='boolean'||!s.settings||Object.keys(s.settings).sort().join()!=='motion,phase,sound'||typeof s.settings.motion!=='boolean'||typeof s.settings.sound!=='boolean'||!['day','dusk','night'].includes(s.settings.phase)||!s.stats||Object.keys(s.stats).sort().join()!=='crafted,harvests,served,trips'||!Object.values(s.stats).every(x=>integer(x)))return null;const g=new Game(o);g.s=s;return g}catch{return null}}
}
class Store{constructor(storage,clock=()=>Date.now()){this.storage=storage;this.clock=clock;this.error=false}load(){for(const k of[KEY,KEY+'-backup']){try{const raw=this.storage.getItem(k);if(!raw)continue;const g=Game.restore(JSON.parse(raw),{clock:this.clock});if(g){g.tick();return g}this.error=true}catch{this.error=true}}return null}save(g){try{const old=this.storage.getItem(KEY);if(old&&Game.restore(JSON.parse(old),{clock:this.clock}))this.storage.setItem(KEY+'-backup',old);this.storage.setItem(KEY,JSON.stringify(g.serialize()));return true}catch{this.error=true;return false}}export(g){g.tick();return JSON.stringify({game:'pine-haven',state:g.serialize()},null,2)}inspect(text){try{if(text.length>2e6)return null;const d=JSON.parse(text);return d.game==='pine-haven'?Game.restore(d.state,{clock:this.clock}):null}catch{return null}}}
return{Game,Store,KEY,MAX_OFFLINE};
});
