'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),D=require('./reference-content.js'),A=require('./collection-art.js');
const ordinary=D.chains.filter(c=>!c.hidden),allSvg=[];
assert.equal(ordinary.length,40);
for(const chain of ordinary){
 assert.equal(chain.names.length,12);assert.equal(new Set(chain.names).size,12,chain.id+' names');
 const variants=[];
 for(let lv=4;lv<=12;lv++){const d=D.items[chain.id+':'+lv];assert.equal(d.name,chain.names[lv-1]);const shape=A.itemShape(chain.id,lv);assert.ok(shape&&shape.length>100,chain.id+':'+lv);assert.ok(!/undefined|NaN|Infinity/.test(shape));variants.push(shape);allSvg.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><g fill="${chain.color}" stroke="${chain.color}" stroke-width="2">${shape}</g></svg>`)}
 // One silhouette family must still change between low/mid/master construction.
 assert.equal(new Set([variants[0],variants[2],variants[5],variants[8]]).size,4,chain.id+' needs four different constructions');
}
assert.equal(D.activityStories.length,60);assert.equal(D.activityStorySets.length,15);
for(const prop of ['title','text','line'])assert.equal(new Set(D.activityStories.map(c=>c[prop])).size,60,prop+' must be independent');
const cards=D.activityStories.map((c,id)=>{assert.equal(c.id,id);assert.equal(c.set,Math.floor(id/4));assert.equal(c.moment,id%4);assert.ok(c.text.length>=35&&c.text.split('。').length>=3,c.title+' needs a narrated moment');assert.ok(D.characters.some(x=>x.id===c.who));const svg=A.card(c,true);assert.ok(!/undefined|NaN|Infinity/.test(svg));assert.ok(svg.includes('aria-label="'+c.title+'"'));allSvg.push(svg.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '));return svg});
assert.equal(new Set(cards).size,60);
const root=path.resolve(__dirname,'../../docs');
fs.writeFileSync(path.join(root,'neon-seasons-collection-preview.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>霓虹四季 · 收藏画面校对</title><style>body{margin:0;padding:20px;background:#1b2432;color:#e6e9dc;font:14px "Microsoft YaHei",sans-serif}h1{font-size:23px}h2{margin-top:35px;color:#c7eaa4}nav a{color:#a9dbe2;margin-right:15px}.item-row{display:grid;grid-template-columns:repeat(9,minmax(0,1fr));gap:5px;max-width:1100px}.item{background:#2c394b;border-radius:8px;padding:6px;text-align:center}.item svg{display:block;width:64px;max-width:100%;margin:auto}.item small{display:block;font-size:10px;line-height:1.5}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));max-width:1200px;gap:10px}.card{background:#29384a;border-radius:12px;padding:8px}.card svg{width:100%}.card h3{font-size:12px}.card p{font-size:11px;line-height:1.7}.card blockquote{color:#bfd9b1;font-size:11px;margin:8px 0}@media(max-width:650px){.item-row{grid-template-columns:repeat(3,minmax(0,1fr))}.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}</style><h1>原创收藏画面校对</h1><nav><a href="#items">360个高阶物品</a><a href="#stories">60张故事卡</a></nav><p>用于检查图案与文案；游戏存档、解锁和奖励仍由正式页面控制。</p><div id="items">${ordinary.map(c=>`<h2>${c.name}</h2><div class="item-row">${Array.from({length:9},(_,n)=>`<div class="item"><svg viewBox="0 0 64 64"><g fill="${c.color}" stroke="${c.color}" stroke-width="2">${A.itemShape(c.id,n+4)}</g></svg><small>Lv.${n+4} ${c.names[n+3]}</small></div>`).join('')}</div>`).join('')}</div><div id="stories"><h1>十五套日常故事</h1>${D.activityStorySets.map((name,set)=>`<h2>${name}</h2><div class="cards">${D.activityStories.slice(set*4,set*4+4).map(c=>`<article class="card">${cards[c.id]}<h3>${c.title}</h3><p>${c.text}</p><blockquote>${D.characters.find(x=>x.id===c.who).name}：${c.line}</blockquote></article>`).join('')}</div>`).join('')}</div></html>`);
fs.writeFileSync(path.join(root,'neon-seasons-collection-svg-check.json'),JSON.stringify(allSvg));
console.log('PASS 40 ordinary chains / 360 level 4–12 illustrations / 60 independent card passages and rendered scenes');
