'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),C=require('./commissions.js'),D=require('./reference-content.js'),earned=JSON.parse(fs.readFileSync(__dirname+'/full-earned-profile.json','utf8')),copy=v=>JSON.parse(JSON.stringify(v));
let now=earned.clock,passed=[];const fresh=()=>C.Game.restore(copy(earned.state),{clock:()=>now});
function test(name,fn){now=earned.clock;fn();passed.push(name);console.log('PASS '+name)}
test('legacy earned profile stays unchanged and menu reads consume no RNG or UID',()=>{const g=fresh(),before=g.serialize();for(let i=0;i<8;i++){assert.equal(g.commissionOffers().length,3);assert.equal(g.commissionStatus().completed,0)}assert.deepEqual(g.serialize(),before);const locked=new C.Game({clock:()=>now});assert.deepEqual(locked.commissionOffers(),[]);assert.equal(locked.acceptCommission('unknown'),false)});
test('three distinct unlocked families, ordinary materials, exact highest 8/10/12 grades',()=>{const g=fresh(),offers=g.commissionOffers();assert.equal(new Set(offers.map(x=>x.family)).size,3);assert.deepEqual(offers.map(x=>x.level),[8,10,12]);for(const o of offers){assert.equal(o.requirements.length,2);assert.equal(o.requirements[1].level,o.level-3);assert.ok(o.requirements.every(r=>D.generators[o.family].chains.includes(r.chain)&&!D.byChain[r.chain].hidden));assert.ok(o.reward.coins<=2400)}assert.equal(g.acceptCommission(offers[0].id),true);assert.deepEqual(g.commissionOffers(),[]);assert.equal(g.acceptCommission(offers[1].id),false);assert.ok(fresh())});
test('missing materials refuse atomically; accepted contract survives actual serialize/restore',()=>{const g=fresh(),o=g.commissionOffers()[2];assert.ok(g.acceptCommission(o.id));for(const r of o.requirements){g.s.board=g.s.board.map(i=>i?.chain===r.chain&&i.level===r.level?null:i);g.s.inventory=g.s.inventory.filter(i=>i.chain!==r.chain||i.level!==r.level)}const before=g.serialize();assert.equal(g.deliverCommission(o.id),false);assert.deepEqual(g.serialize(),before);assert.deepEqual(C.Game.restore(before,{clock:()=>now}).commissionStatus().active,o)});
test('fixture delivery uses board plus warehouse once; stale button cannot claim twice',()=>{const g=fresh(),o=g.commissionOffers()[0];assert.ok(g.acceptCommission(o.id));for(const r of o.requirements){g.s.board=g.s.board.map(i=>i?.chain===r.chain&&i.level===r.level?null:i);g.s.inventory=g.s.inventory.filter(i=>i.chain!==r.chain||i.level!==r.level)}g.s.board[g.empty()]=g.make(o.requirements[0].chain,o.requirements[0].level);g.s.inventory.push(g.make(o.requirements[1].chain,o.requirements[1].level));const before=g.s.coins,orders=g.s.stats.orders;assert.ok(g.deliverCommission(o.id));assert.equal(g.s.coins,before+o.reward.coins);assert.equal(g.s.stats.orders,orders+1);assert.ok(o.requirements.every(r=>g.owned(r)===0));const after=g.serialize();assert.equal(g.deliverCommission(o.id),false);assert.deepEqual(g.serialize(),after);assert.ok(C.Game.restore(after,{clock:()=>now}));const limited=fresh();assert.ok(limited.acceptCommission(limited.commissionOffers()[0].id));limited.s.commissions.completed=3;limited.s.commissions.daily=3;limited.s.commissions.nonce=3;limited.s.commissions.active.sequence=3;const limitedOrder=limited.commissionStatus().active;for(const r of limitedOrder.requirements)if(!limited.owned(r))limited.s.inventory.push(limited.make(r.chain,r.level));assert.ok(limited.canDeliver(limitedOrder.requirements));const capBefore=limited.serialize();assert.ok(C.Game.restore(capBefore,{clock:()=>now}));assert.equal(limited.deliverCommission(limited.commissionStatus().active.id),false);assert.deepEqual(limited.serialize(),capBefore)});
test('three-per-day cap, accepted contract carries across day, cancellation consumes no items',()=>{const g=fresh(),o=g.commissionOffers()[0];assert.ok(g.acceptCommission(o.id));const before=g.serialize();assert.ok(g.cancelCommission(o.id));assert.deepEqual(g.s.board,before.board);assert.equal(g.s.coins,before.coins);assert.deepEqual(g.commissionOffers(),[]);now+=30000;g.tick();assert.equal(g.commissionOffers().length,3);assert.equal(g.acceptCommission(o.id),false);g.s.commissions.completed=3;g.s.commissions.daily=3;g.s.commissions.nonce=3;assert.deepEqual(g.commissionOffers(),[]);now+=86400000;g.tick();const next=g.commissionOffers()[0];assert.ok(g.acceptCommission(next.id));now+=86400000;g.tick();assert.equal(g.commissionStatus().active.id,next.id);assert.equal(g.commissionStatus().daily,0);assert.ok(C.Game.restore(g.serialize(),{clock:()=>now}))});
test('strict save guards refuse corrupt family, tier, sequence, reward, limits and future day',()=>{const g=fresh();assert.ok(g.acceptCommission(g.commissionOffers()[0].id));const raw=g.serialize();for(const mutate of [c=>c.active.family=99,c=>c.active.tier=3,c=>c.active.level=13,c=>c.active.sequence++,c=>c.active.reward={coins:1e9},c=>c.daily=4,c=>c.completed=-1,c=>c.nonce=-1,c=>c.day='2099-12-31']){const bad=copy(raw);mutate(bad.commissions);assert.equal(C.Game.restore(bad,{clock:()=>now}),null)}});
fs.writeFileSync(__dirname+'/commission-test-results.json',JSON.stringify({checked:new Date().toISOString(),passed,scope:'Boundary fixtures explicitly labelled; genuine resource playthrough is separate.'},null,2));
