(function(root,factory){const node=typeof module==='object'&&module.exports,C=node?require('./reference-activities.js'):root.NSCore,D=node?require('./reference-content.js'):root.NSContent;factory(C,D);if(node)module.exports=C})(typeof window==='undefined'?globalThis:window,(C,D)=>{
'use strict';const P=C.Game.prototype;if(P.commissionOffers)return;const restore=C.Game.restore;
const integer=(n,min=0,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
const titles=[['补齐维修站工具','为新学徒备好材料','装好社区维修台'],['整理幼苗课堂','为花园茶会备货','做一份丰收礼物'],['给夜班留一杯热饮','准备窗边的点心','为外婆开一次茶会'],['接好旧广播线路','修复没播完的唱片','录一场完整的问候'],['系好回港的船','整理守潮人的收藏','给新航程备一份礼'],['搭起周末的小舞台','为朋友排一次合奏','把演出留给整条街'],['补好海边休息站','给志愿者送来清凉','准备夏天的告别礼'],['接好屋顶的光能','为午后送一阵风','建起共享光能站'],['为手账补好纸墨','印出街区的来信','整理新一年的书页'],['为夜班备好热汤','准备六人的晚餐','开一桌共享宴席'],['把合照收进展架','布置不剪辑的展览','给记忆馆留一份原件'],['标出回家的路','接通新的指示灯','整理完整的撤离图'],['校准值守者的钟','为钟楼备好新机芯','让明天准时来到'],['给来客留一杯热茶','把陶器送进暖屋','准备冬夜的共享炉'],['校准极光观测镜','给新朋友印好星图','记录共同看见的极光'],['接亮回港的航灯','为站台补好供电','照亮新一年的航路']];
const notes=['把耐用工具和木料送到义务维修站，给新学徒留一个工作位。','温室要教第一次种花的邻居，把植物和果实准备好。','夜班结束后也该吃到热食，咖啡和点心会留在窗边。','修复原带需要线路与唱片，让每个人的声音都能被听见。','码头要重新系好小艇，船具与海边的收藏会送给守潮人。','舞台要为大家留一场合奏，乐器和旗帜都是欢迎的信号。','给海边的志愿者备好饮品与泳具，让夏天的工作轻松一点。','把光能设备和风扇装进休息站，炎热的午后也有一阵风。','新印刷台要留给社区手账，纸张和油墨都会派上用场。','今晚有一桌共享晚餐，厨具与热汤会等最后一位夜班朋友。','把没有剪去的合照装好，照片和展架都留给公共记忆馆。','信号和地图会标出安全回家的路，每个人都看得懂。','给钟楼值守者送来新机芯，让被留下的时间继续往前走。','炉具和陶器要送到暖屋，让冬夜来客都能喝到一杯热茶。','用镜片校准观测台，新星图要给第一次来看极光的人。','把新镜片与航灯材料装好，让新一年的站台亮到天明。'];
function spec(a){const f=D.generators[a.family],first=f.chains[a.sequence%f.chains.length],second=f.chains[(a.sequence+1)%f.chains.length],requirements=[{chain:first,level:a.level,qty:1},{chain:second,level:a.level-3,qty:1}],reward={coins:Math.min(2400,a.level*120+(a.level-3)*70),energy:[50,80,100][a.tier],xp:a.level*25+40};return{...a,id:'commission-'+[a.sequence,a.family,a.tier,a.level].join('-'),requirements,reward,title:titles[a.family][a.tier],npc:[5,3,4,2,1,2,3,5,0,4,0,2,5,4,3,1][a.family],familyName:f.name,note:notes[a.family],tierName:['手作','精制','珍藏'][a.tier]}}
P.commissionStatus=function(){const c=this.s.commissions;return{completed:c?.completed||0,daily:c?.day===this.s.day?c.daily:0,nonce:c?.nonce||0,rerollAt:c?.rerollAt||0,active:c?.active?spec(c.active):null,unlocked:this.s.progress>=16}};
P.commissionOffers=function(){const c=this.commissionStatus();if(!c.unlocked||c.active||c.daily>=3||this.s.stamp<c.rerollAt)return[];const families=this.s.sourceGranted,offset=C.hash(this.s.seed+':'+this.s.day+':'+c.nonce)%families.length,bonus=this.s.progress===64?2:this.s.progress>=32?1:0;return[0,1,2].map(tier=>spec({sequence:c.nonce,family:families[(offset+tier)%families.length],tier,level:6+tier*2+bonus}))};
function update(g){const old=g.s.commissions;return g.s.commissions={completed:old?.completed||0,day:g.s.day,daily:old?.day===g.s.day?old.daily:0,nonce:old?.nonce||0,rerollAt:old?.rerollAt||0,active:old?.active||null}}
P.acceptCommission=function(id){this.tick();const offer=this.commissionOffers().find(x=>x.id===id);if(!offer)return false;this.invalidate();const c=update(this);c.active={sequence:offer.sequence,family:offer.family,tier:offer.tier,level:offer.level};return true};
P.cancelCommission=function(id){this.tick();const a=this.commissionStatus().active;if(!a||a.id!==id)return false;this.invalidate();const c=update(this);c.active=null;c.nonce++;c.rerollAt=this.s.stamp+30000;return true};
P.deliverCommission=function(id){this.tick();const status=this.commissionStatus(),a=status.active;if(!status.unlocked||status.daily>=3||!a||a.id!==id||!this.canDeliver(a.requirements))return false;this.invalidate();if(!this.consume(a.requirements))return false;const c=update(this);c.active=null;c.completed++;c.daily++;c.nonce++;c.rerollAt=0;this.s.stats.orders++;this.s.npcOrders[a.npc]++;if(this.s.npcOrders[a.npc]%3===0)this.s.bonds[a.npc]++;this.s.pass+=35;this.award(a.reward);if(this.s.stats.orders%3===0)this.s.tools.packs++;if(this.s.stats.orders%6===0)this.award({energy:40});this.activityGain('order');if(this.s.stats.orders%4===0){const box=this.make('partsbox');box.family=a.family;this.s.inbox.push(box)}this.emit('deliver',{commission:id});return true};
function valid(g){const c=g.s.commissions;if(c===undefined)return true;if(!c||typeof c!=='object'||Array.isArray(c)||Object.keys(c).sort().join(',')!=='active,completed,daily,day,nonce,rerollAt'||!integer(c.completed,0,g.s.stats.orders)||!integer(c.daily,0,3)||c.daily>c.completed||!integer(c.nonce,c.completed)||!integer(c.rerollAt)||typeof c.day!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(c.day)||c.day>g.s.day||g.s.progress<16)return false;if(c.active===null)return true;const a=c.active;if(!a||typeof a!=='object'||Array.isArray(a)||Object.keys(a).sort().join(',')!=='family,level,sequence,tier'||!integer(a.sequence)||a.sequence!==c.nonce||!integer(a.family,0,15)||!g.s.sourceGranted.includes(a.family)||!integer(a.tier,0,2)||!integer(a.level,6+a.tier*2,6+a.tier*2+(g.s.progress===64?2:g.s.progress>=32?1:0)))return false;return spec(a).requirements.every(r=>D.items[r.chain+':'+r.level]&&!D.byChain[r.chain].hidden)}
C.Game.restore=function(raw,o={}){const g=restore.call(this,raw,o);return g&&valid(g)?g:null};
C.commissionSpec=spec;
});
