'use strict';
// Independent DOM/event fixture running the actual app handlers; not a browser or touch-device test.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('./reference-core.js');
const app=fs.readFileSync(__dirname+'/app.js','utf8'),start=app.indexOf("document.addEventListener('pointerdown'"),end=app.indexOf("$('import-file').onchange",start),lifeStart=app.indexOf("addEventListener('pagehide'"),lifeEnd=app.indexOf('\nfunction frame',lifeStart);
assert.ok(start>0&&end>start&&lifeEnd>lifeStart);
const handlers=app.slice(start,end)+'\n'+app.slice(lifeStart,lifeEnd);
let passed=0;
function fixture(){
 const now=Date.parse('2026-10-01T13:00:00Z'),g=new C.Game({seed:'pointer-fixture',clock:()=>now});g.dismissScene();g.s.board.fill(null);
 const listeners={},tokens=[],selectedCalls=[],moves=[],effects=[];
 const on=(name,fn)=>(listeners[name]??=[]).push(fn),cells=new Map();
 const cell=(n,ctx='main')=>{const k=ctx+':'+n;if(!cells.has(k)){const c={tagName:'BUTTON',dataset:{cell:String(n),context:ctx},disabled:false,classList:{contains:()=>false},capture:new Set(),closest(s){return s==='button'||s==='[data-cell]'?this:null},matches(s){return s==='[data-cell]'},setPointerCapture(id){this.capture.add(id)},hasPointerCapture(id){return this.capture.has(id)},releasePointerCapture(id){this.capture.delete(id)},focus(){}};cells.set(k,c)}return cells.get(k)};
 const doc={hidden:false,addEventListener:on,createElement(){const t={style:{},remove(){this.removed=true}};tokens.push(t);return t},body:{append(){}},elementFromPoint(){return doc.hit},querySelector(){return null}};
 const env={document:doc,addEventListener:on,game:g,A:{icon:()=>'<svg/>'},audio:{unlock(){}},actions:{'mini-act':()=>effects.push('beat')},performance:{now:()=>now},drag:null,dragToken:null,pointerEngaged:new Set(),rhythmPressedButtons:new WeakSet(),context:'main',tab:'merge',modalKind:'',selected:-1,hintAt:[],lastFrame:0,selectCell:(i,ctx)=>selectedCalls.push([i,ctx]),transact(fn,after){const r=fn();moves.push(r);if(r.ok&&after)after(r);return r},render:()=>effects.push('render'),night:()=>effects.push('night'),save:()=>effects.push('save'),arcadeView:()=>effects.push('arcade'),refreshModal:()=>effects.push('refresh'),close:()=>effects.push('close')};
 const ctx=vm.createContext(env);vm.runInContext(handlers,ctx);
 const fire=(name,extra={})=>{const e={pointerId:1,button:0,isPrimary:true,clientX:10,clientY:10,target:cell(3),preventDefault(){this.prevented=true},...extra};for(const fn of listeners[name]||[])fn(e);return e};
 const put=(n,chain,level)=>g.s.board[n]=g.make(chain,level),state=()=>JSON.stringify(g.s);
 return{g,env,doc,cell,fire,put,tokens,selectedCalls,moves,effects,state};
}
function test(name,fn){fn();passed++;console.log('PASS '+name)}
test('primary tap selects once; secondary finger and right click do not act',()=>{const f=fixture();f.fire('pointerdown',{isPrimary:false});f.fire('pointerup');assert.equal(f.selectedCalls.length,0);f.fire('pointerdown',{button:2});f.fire('pointerup');assert.equal(f.selectedCalls.length,0);f.fire('pointerdown');f.fire('pointerup');assert.deepEqual(f.selectedCalls,[[3,'main']]);assert.equal(f.env.pointerEngaged.size,0)});
test('actual rules move, merge and swap through release, without extra energy charge',()=>{for(const mode of ['move','merge','swap']){const f=fixture();const a=f.put(3,'wood',1),b=mode==='move'?null:f.put(4,mode==='merge'?'wood':'tool',1),energy=f.g.s.energy;f.doc.hit=f.cell(4);f.fire('pointerdown');f.fire('pointermove',{clientX:60});assert.ok(f.env.dragToken);f.fire('pointerup',{clientX:60});assert.equal(f.moves.length,1);assert.equal(f.moves[0].ok,true);assert.equal(f.g.s.energy,energy);if(mode==='merge'){assert.equal(f.g.s.board[4].level,2);assert.equal(f.g.s.board[3],null)}else{assert.equal(f.g.s.board[4].uid,a.uid);assert.equal(f.g.s.board[3]?.uid??null,b?.uid??null)}assert.equal(f.selectedCalls.length,0);assert.equal(f.env.drag,null);assert.equal(f.env.dragToken,null);assert.equal(f.tokens[0].removed,true)}});
test('off-board and cross-context drops leave resources and items unchanged',()=>{for(const target of [null,'night']){const f=fixture();f.put(3,'wood',2);const before=f.state();f.doc.hit=target?f.cell(4,target):null;f.fire('pointerdown');f.fire('pointermove',{clientX:60});f.fire('pointerup',{clientX:60});assert.equal(f.state(),before);assert.equal(f.moves.length,0);assert.equal(f.env.drag,null)}});
test('secondary pointer cannot complete or replace the primary drag',()=>{const f=fixture();f.put(3,'wood',1);f.doc.hit=f.cell(4);f.fire('pointerdown');f.fire('pointermove',{clientX:60});f.fire('pointerdown',{pointerId:2,isPrimary:false,target:f.cell(4)});f.fire('pointerup',{pointerId:2,isPrimary:false,clientX:60});assert.equal(f.moves.length,0);assert.equal(f.env.drag.id,1);f.fire('pointerup',{clientX:60});assert.equal(f.moves.length,1)});
test('system cancellation and lost capture clear gestures without mutations',()=>{for(const name of ['pointercancel','lostpointercapture']){const f=fixture();f.put(3,'wood',3);const before=f.state();f.fire('pointerdown');f.fire('pointermove',{clientX:60});f.fire(name);assert.equal(f.state(),before);assert.equal(f.env.pointerEngaged.size,0);assert.equal(f.env.drag,null);assert.equal(f.env.dragToken,null);assert.equal(f.cell(3).capture.size,0);f.fire('pointerup');assert.equal(f.selectedCalls.length,0)}});
test('blur, pagehide, hidden and Escape abort a gesture; resume accepts a fresh gesture',()=>{for(const name of ['blur','pagehide','visibilitychange','keydown']){const f=fixture();f.put(3,'wood',3);const before=f.state();f.fire('pointerdown');f.fire('pointermove',{clientX:60});if(name==='visibilitychange')f.doc.hidden=true;f.fire(name,{key:'Escape'});assert.equal(f.state(),before);assert.equal(f.env.pointerEngaged.size,0);assert.equal(f.env.drag,null);assert.equal(f.tokens[0].removed,true);f.fire('pointerup');assert.equal(f.selectedCalls.length,0);f.fire('pointerdown');f.fire('pointerup');assert.equal(f.selectedCalls.length,1)}});
test('Enter and Space select once; key repeat and editable fields cannot produce',()=>{for(const key of ['Enter',' ']){const f=fixture(),extra={key,code:key===' '?'Space':'Enter'};assert.equal(f.fire('keydown',extra).prevented,true);f.fire('keydown',{...extra,repeat:true});assert.equal(f.selectedCalls.length,1);f.fire('keydown',{...extra,target:{tagName:'TEXTAREA'}});assert.equal(f.selectedCalls.length,1)}});
console.log(JSON.stringify({passed,scope:'actual event handlers in independent DOM fixture; real game move rules; not real touch hardware'}));
