'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),D=require('./reference-content.js'),C=require('./reference-core.js'),Legacy=require('./engine.js'),{Store,keys}=require('./save.js');let count=0;const passed=[];
const copy=v=>JSON.parse(JSON.stringify(v));
function fresh(seed='reference'){let now=seed==='72-renovations'&&process.env.NS_CURRENT_DATE_CAMPAIGN?Date.now()-70000000:Date.parse('2026-10-01T08:00:00+08:00');const g=new C.Game({seed,clock:()=>now});g.dismissScene();return{g,clock:()=>now,wait(ms){now+=ms;g.tick()}}}
function test(name,fn){fn();passed.push(name);count++;console.log('PASS '+name)}
function put(g,n,chain,lv){g.s.board[n]=g.make(chain,lv);g.discover(g.s.board[n]);return g.s.board[n]}
test('7x9 board holds producer + fragments; fresh save accepted',()=>{const {g,clock}=fresh();assert.equal(g.s.board.length,63);assert.ok(C.isActive(g.s.board[0]));assert.equal(g.s.board[1].chain,'producer0');assert.ok(C.Game.restore(g.serialize(),{clock}));assert.equal(g.generate(0).ok,false);assert.equal(g.upgrade(0),false)});
test('fragment merge, producer merge and per-instance recharge',()=>{const {g,wait,clock}=fresh();assert.ok(g.move(1,2).ok);assert.equal(g.s.board[2].level,2);const a=put(g,3,'producer0',5),b=put(g,4,'producer0',5);a.charge=0;b.charge=7;wait(9000);assert.equal(a.charge,1);assert.equal(b.charge,8);g.move(3,4);assert.equal(g.s.board[4].level,6);assert.equal(g.s.board[4].charge,26);assert.ok(C.Game.restore(g.serialize(),{clock}))});
test('full board refuses production without consuming energy/stock/RNG',()=>{const {g}=fresh();for(let n=0;n<g.unlocked;n++)if(!g.s.board[n])put(g,n,'wood',1);const before=copy(g.s);assert.equal(g.produce(0).ok,false);assert.deepEqual(g.s,before)});
test('producer cannot be sold, bought-upgraded, or modified with scissors/joker',()=>{const {g}=fresh();const before=copy(g.s);assert.equal(g.sell(0,true),false);assert.equal(g.tool('joker',0),false);assert.equal(g.tool('scissors',0),false);assert.equal(g.upgrade(0),false);assert.deepEqual(g.s,before)});
test('orders consume goods, give coins, no build star/material gate',()=>{const {g}=fresh();assert.equal(g.build(),false);const req=g.s.neighbors[0].requirements[0];put(g,3,req.chain,req.level);const before=g.s.coins;assert.ok(g.deliver('neighbor',0));assert.ok(g.s.coins>before);assert.equal(g.s.stars,0);assert.equal(g.deliver('main'),false);const coins=g.s.coins;assert.ok(g.build());assert.equal(g.s.coins,coins-D.homeCosts[0]);assert.equal(g.s.homeProgress,1);assert.equal(g.s.progress,0);assert.equal(g.build(),false);assert.ok(g.dismissScene())});
test('automatic flower emission blocks safely, accumulates capped offline and manual remote release',()=>{const {g,wait,clock}=fresh();const flower=put(g,16,'flower',5);for(const n of g.adjacent(16))if(n<g.unlocked)put(g,n,'tool',1);wait(3600000);assert.equal(flower.autoStock,3);const energy=g.s.energy;const r=g.produce(16);assert.ok(r.ok);assert.equal(g.s.board[r.index].chain,'petal');assert.equal(flower.autoStock,2);assert.equal(g.s.energy,energy);assert.ok(C.Game.restore(g.serialize(),{clock}));g.s.board[17]=null;wait(1);assert.equal(g.s.board[17].chain,'petal')});
test('needle container emits eight cloth then leaves cord, started containers cannot merge/tool',()=>{const {g,clock}=fresh();put(g,3,'needle',4);for(let n=0;n<8;n++){assert.ok(g.produce(3).ok);if(n===0){const b=put(g,30,'needle',4);assert.equal(g.move(3,30).ok,false);assert.equal(g.tool('joker',3),false);g.s.board[30]=null}assert.ok(C.Game.restore(g.serialize(),{clock}))}assert.equal(g.s.board[3].chain,'cord');assert.ok(g.s.discovered.includes('cord:1'));const raw=g.serialize();raw.discovered=raw.discovered.filter(id=>id!=='cord:1');raw.stats.discovered--;const repaired=C.Game.restore(raw,{clock});assert.ok(repaired);assert.ok(repaired.s.discovered.includes('cord:1'));const discovery=repaired.s.stats.discovered,xp=repaired.s.xp;repaired.tick();assert.equal(repaired.s.stats.discovered,discovery);assert.equal(repaired.s.xp,xp);assert.ok(C.Game.restore(repaired.serialize(),{clock}));put(g,4,'cord',4);put(g,5,'cord',4);assert.ok(g.move(4,5).ok);assert.equal(g.s.board[5].chain,'toy')});
test('petals -> perfume -> glass, timed emission validates space before consuming',()=>{const {g,wait,clock}=fresh();put(g,3,'petal',4);for(let n=0;n<3;n++)assert.ok(g.produce(3).ok);assert.equal(g.s.board[3].chain,'glass');const index=g.s.board.findIndex(i=>i?.chain==='perfume');assert.equal(g.produce(index).ok,false);wait(90000);for(let n=0;n<g.unlocked;n++)if(!g.s.board[n])put(g,n,'tool',1);const before=copy(g.s);assert.equal(g.produce(index).ok,false);assert.deepEqual(g.s,before);g.s.board[34]=null;assert.ok(g.produce(index).ok);assert.equal(g.s.board[index].chain,'glass');assert.equal(g.s.board[34].chain,'glass');assert.ok(C.Game.restore(g.serialize(),{clock}))});
test('boxes merge only same family, produce fragments, opened boxes cannot merge again',()=>{const {g,clock}=fresh();const a=put(g,3,'partsbox',1),b=put(g,4,'partsbox',1);a.family=b.family=0;assert.ok(g.move(3,4).ok);assert.equal(g.s.board[4].level,2);for(let n=0;n<6;n++)assert.ok(g.produce(4).ok);assert.equal(g.s.board[4],null);assert.equal(g.s.board.filter(i=>i?.chain==='producer0'&&i.level===2).length,6);assert.ok(C.Game.restore(g.serialize(),{clock}))});
test('eight side source containers have origin, cooldown, residue and unique three-stage reward',()=>{for(let n=0;n<8;n++){const {g,wait,clock}=fresh('side'+n),p=D.paths[n];put(g,3,p.source,p.level);assert.ok(g.activatePath(3));assert.equal(g.activatePath(3),false);for(let k=0;k<4;k++){assert.ok(g.produce(3).ok);if(k<3){assert.equal(g.produce(3).ok,false);wait(p.delay)}}assert.equal(g.s.board[3].chain,p.residue);assert.ok(g.s.recipes.includes(p.id));assert.equal(g.s.stats.recipes,1);for(let stage=0;stage<3;stage++){const r=g.sideOrder(n);put(g,30,r.chain,r.level);assert.ok(g.sideDeliver(n))}assert.equal(g.sideDeliver(n),false);assert.ok(C.Game.restore(g.serialize(),{clock}))}});
test('malformed producer/container/UID/save data rejected',()=>{const {g,clock}=fresh();const raw=g.serialize();for(const mutate of [s=>s.board[0].charge=-1,s=>s.board[0].charge=100,s=>s.board[0].chargeStamp=s.stamp+1,s=>s.sourceGranted=[0,0],s=>s.homeProgress=9,s=>s.homeStyles[0]=3,s=>s.doubleEnergy=true,s=>s.board[1].uid=s.board[0].uid,s=>s.sideProgress[0]=4,s=>s.pendingScene={kind:'home',id:7},s=>s.stars=1]){const bad=copy(raw);mutate(bad);assert.equal(C.Game.restore(bad,{clock}),null)}});
test('legacy migration retains all goods/progress/inventory and records pre-migration backup',()=>{let now=Date.parse('2026-10-01T08:00:00+08:00');const old=new Legacy.Game({seed:'old',clock:()=>now});old.dismissScene();old.s.board[4]=old.make('flower',5);old.discover(old.s.board[4]);old.s.inventory.push(old.make('wood',3));const raw=old.serialize(),goods=[...raw.board,...raw.inventory,...raw.inbox].filter(Boolean),map=new Map([[keys.KEY,JSON.stringify(raw)]]),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},store=new Store(storage,()=>now),g=store.load();assert.ok(g);assert.equal(g.s.version,2);for(const i of goods)assert.ok([...g.s.board,...g.s.inventory,...g.s.inbox].some(x=>x?.uid===i.uid&&x.chain===i.chain&&x.level===i.level));assert.ok(map.has(keys.KEY+'-before-v2'));store.save(g);assert.ok(C.Game.restore(g.serialize(),{clock:()=>now}));assert.ok(store.load())});

// Normal-operation campaign: no state resource/progress assignment; obtain coins by production, merges,
// sales/real orders, claim ordinary rewards, wait for real regeneration and restore every checkpoint.
const run=fresh('72-renovations'),g=run.g;let produced=0,orders=0,waited=0;
function checkpoint(){const restored=C.Game.restore(g.serialize(),{clock:run.clock});assert.ok(restored,'checkpoint restore at '+g.s.homeProgress+'/'+g.s.progress);g.s=restored.s}
function tidy(req){let changed=true;while(changed){changed=false;for(let n=0;n<g.unlocked;n++){const x=g.s.board[n];if(!x||x.web||x.bubble||x.used||x.path||C.producer(x)!==undefined||x.level>=C.itemDef(x).max||x.chain===req.chain&&x.level>=req.level||req.chain==='cloth'&&x.chain==='needle'&&x.level>=4)continue;const m=g.s.board.findIndex((y,j)=>j!==n&&j<g.unlocked&&y&&!y.bubble&&!y.used&&!y.path&&y.chain===x.chain&&y.level===x.level);if(m>=0){assert.ok(g.move(n,m).ok);changed=true;break}}}for(let n=0;n<g.unlocked;n++)if(g.s.board[n]?.bubble)g.bubble(n,false);if(g.empty()<0){const n=g.s.board.findIndex(i=>i&&!i.web&&!i.bubble&&C.producer(i)===undefined&&i.chain!==req.chain&&!(req.chain==='cloth'&&i.chain==='needle'));assert.ok(n>=0,'space must be recoverable');assert.ok(g.sell(n,true))}}
function acquire(req){let limit=0;while(!g.canDeliver([req])){assert.ok(++limit<20000,'reachable '+req.chain+':'+req.level);tidy(req);if(g.canDeliver([req]))break;if(req.chain==='cloth'){const container=g.s.board.findIndex(i=>i?.chain==='needle'&&i.level===4&&!i.web&&!i.bubble);if(container>=0&&g.empty()>=0){const emitted=g.produce(container);if(!emitted.ok)assert.equal(emitted.reason,'棋盘已满，先合成或收进仓库','Only automatic flower emission may occupy the last space between tidy and produce');continue}}const id=D.byChain[req.chain].generator;let index=g.s.board.findIndex(i=>C.isActive(i)&&C.producer(i)===id);if(index<0){const box=g.s.inbox.findIndex(i=>C.isActive(i)&&C.producer(i)===id);assert.ok(box>=0);assert.ok(g.claimInbox(box));index=g.s.board.findIndex(i=>C.isActive(i)&&C.producer(i)===id)}const result=g.produce(index);if(!result.ok){run.wait(20000);waited+=20000}else produced++;if(req.chain==='cloth'){const n=g.s.board.findIndex(i=>i?.chain==='needle'&&i.level===4&&!i.web&&!i.bubble);if(n>=0){tidy(req);if(g.empty()>=0)g.produce(n)}}}}
test('complete all 8 home + 64 island renovations through normal coin-order play, every checkpoint restorable',()=>{g.sign();let guard=0;while(g.project){assert.ok(++guard<10000);if(g.s.coins>=g.project.cost&&(g.project.home||g.s.level>=3)){assert.ok(g.build());if(g.s.pendingScene?.kind==='project'&&D.projects[g.s.pendingScene.id].part===3)assert.ok(g.sceneChoice(0));assert.ok(g.dismissScene());if(g.s.homeProgress===1&&!g.s.activity)assert.ok(g.startSeasonEvent());checkpoint();continue}const order=g.s.neighbors[0];for(const r of order.requirements)acquire(r);assert.ok(g.deliver('neighbor',0));orders++;for(let n=0;n<6;n++)if(g.decorValue>=D.decorThresholds[n]&&!g.s.decorClaims.includes(n))g.claimDecor(n);if(g.doubleUnlocked&&!g.s.doubleEnergy)g.setDouble(true)}assert.equal(g.s.homeProgress,8);assert.equal(g.s.progress,64);assert.equal(g.s.read.length,64);assert.equal(g.s.sceneHomeRead.length,8);assert.equal(g.s.clues.length,8);assert.equal(g.s.sourceGranted.length,16);assert.equal(g.unlocked,63);assert.equal(g.s.stars,0);assert.ok(g.s.coins>=0);if(process.env.NS_CURRENT_DATE_CAMPAIGN){assert.equal(g.s.endReward,false);assert.equal(g.s.ending,null);assert.ok(run.clock()<=Date.now());fs.writeFileSync(__dirname+'/first-ending-ready-profile.json',JSON.stringify({provenance:'Normal campaign production, merges, real orders and coin renovation; no resource/progress assignment. Virtual regeneration begins in the past so first-award and wall-clock UI can be tested today.',clock:run.clock(),state:g.serialize()},null,2))}assert.ok(g.ending('restore'));checkpoint()});
test('decoration styles add value once and double energy always emits at least level two',()=>{const before=g.decorValue;assert.ok(g.homeDecorate(0,1));const value=g.decorValue;assert.equal(value,before+20);assert.ok(g.homeDecorate(0,0));assert.ok(g.homeDecorate(0,1));assert.equal(g.decorValue,value);g.setDouble(true);const req={chain:'tool',level:3};tidy(req);run.wait(20000);const energy=g.s.energy;const r=g.produce(g.s.board.findIndex(C.isActive));assert.ok(r.ok);assert.equal(g.s.energy,energy-2);assert.ok(g.s.board[r.index].level>=2);checkpoint()});

test('full season event resource loop: 12 island nodes, 12 dig layers and 10 dinner courses from genuine campaign drops',()=>{const e=g.s.activity;assert.ok(e&&e.tokens>1800&&e.picks>900);while(g.s.activity.nodes<12){assert.ok(g.buildEventNode());const n=g.s.activity.nodes-1;assert.ok(g.claimEventNode(n));assert.equal(g.claimEventNode(n),false);checkpoint()}assert.ok(g.s.activityCollections.includes(e.theme));while(g.s.activity.digLayer<12){const a=g.s.activity;let guard=0;while(!a.digBoard.every(t=>t.open)){assert.ok(++guard<150);const n=a.digBoard.findIndex((t,n)=>g.digAvailable(n));assert.ok(n>=0);assert.ok(g.dig(n))}assert.ok(g.digNext());checkpoint()}const a=g.s.activity;while(a.dinner<10){assert.ok(g.feedDinner());assert.ok(g.claimDinner(a.dinner-1));assert.equal(g.claimDinner(a.dinner-1),false)}assert.equal(g.s.activity.digLayer,12);assert.equal(g.s.activity.dinner,10);assert.equal(g.feedDinner(),false);checkpoint()});
function compactFish(){const e=g.s.activity;let changed=true;while(changed){changed=false;for(let n=0;n<12;n++){const x=e.fishBoard[n];if(!x||x.level===4)continue;const j=e.fishBoard.findIndex((y,k)=>k!==n&&y&&y.kind===x.kind&&y.level===x.level);if(j>=0){assert.ok(g.mergeFish(n,j));changed=true;break}}}for(let n=0;n<12;n++){const i=e.fishBoard[n];if(i&&(i.level===4||g.s.fishCollection.includes(i.kind*4+3)))g.releaseFish(n)}if(!e.fishBoard.some(i=>!i)){const n=e.fishBoard.findIndex(i=>i.level===1);assert.ok(g.releaseFish(n>=0?n:0))}}
test('fishing timing/merges: all 24 fish tiers and six awards without injected bait or catches',()=>{let guard=0;while(g.s.fishCollection.length<24||g.s.activity.fishScore<600){assert.ok(++guard<1500);compactFish();assert.ok(g.castFish());const f=g.s.activity.fishing;let steps=0;while(Math.abs((f.phase<=1?f.phase:2-f.phase)-f.zone)>.02){assert.ok(++steps<600);g.updateFishing(.005)}assert.ok(g.reelFish());assert.equal(f.result.grade,3);assert.ok(g.finishFishing());if(guard%15===0)checkpoint()}for(let n=0;n<6;n++){assert.ok(g.claimFish(n));assert.equal(g.claimFish(n),false)}assert.equal(g.s.fishCollection.length,24);checkpoint()});
test('all 15 four-card activity albums reachable with earned packs, pity and duplicate crafting; each reward unique',()=>{let guard=0;while(g.s.activityCards.length<60){assert.ok(++guard<500);if(g.s.activityDust>=30){const id=Array.from({length:60},(_,n)=>n).find(n=>!g.s.activityCards.includes(n));assert.ok(g.craftActivityCard(id))}else{assert.ok(g.s.activityPacks>0);assert.ok(g.openActivityPack())}}for(let set=0;set<15;set++){assert.ok(g.claimActivityAlbum(set));assert.equal(g.claimActivityAlbum(set),false)}assert.equal(g.s.activityAlbumClaims.length,15);checkpoint()});
test('expired activities preserve unclaimed state, settle only after explicit restart, retain collections',()=>{const before={cards:copy(g.s.activityCards),fish:copy(g.s.fishCollection),collections:copy(g.s.activityCollections)},oldRound=g.s.activity.round;run.wait(7*86400000);assert.ok(g.s.activity.ended);assert.equal(g.buildEventNode(),false);assert.equal(g.dig(1),false);assert.equal(g.castFish(),false);assert.equal(g.startSeasonEvent(),true);assert.equal(g.s.activity.round,oldRound+1);assert.deepEqual(g.s.activityCards,before.cards);assert.deepEqual(g.s.fishCollection,before.fish);assert.deepEqual(g.s.activityCollections,before.collections);assert.equal(g.s.activity.nodes,0);checkpoint()});
test('activity save rejects invalid board/resources/card claims and out-of-range fishing phases',()=>{const raw=g.serialize();for(const mutate of [s=>s.activity.picks=-1,s=>s.activity.nodes=13,s=>s.activity.digBoard[1].hp=-1,s=>s.activityCards=[60],s=>s.activityAlbumClaims=[15],s=>s.fishCollection=[24],s=>s.activity.fishBoard[0]={kind:6,level:1},s=>s.activity.fishing={phase:2.1,elapsed:1,speed:1,zone:.5,result:null},s=>s.activityCards=null]){const bad=copy(raw);mutate(bad);assert.equal(C.Game.restore(bad,{clock:run.clock}),null)}});

const result={version:2,checked:new Date().toISOString(),checks:count,passed,campaign:{home:g.s.homeProgress,island:g.s.progress,orders,produced,waitedSeconds:waited/1000,coins:g.s.coins,level:g.s.level},remaining:'art polish and exact item correspondence, all-theme rounds, full collection reachability and complete mobile playability audit'};fs.writeFileSync(__dirname+'/reference-test-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result.campaign));
// A continuation can use this genuinely earned campaign profile; no save fixtures are exported.
module.exports={run,g,checkpoint};
