(function(root,factory){const node=typeof module==='object'&&module.exports,D=node?require('./reference-content.js'):root.NSContent,base=node?require('./engine.js'):root.NSCore;const result=factory(D,base);if(node)module.exports=result;else root.NSCore=result})(typeof window==='undefined'?globalThis:window,(D,Base)=>{
'use strict';const cp=v=>JSON.parse(JSON.stringify(v)),integer=(v,min=0,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(v)&&v>=min&&v<=max,producer=i=>D.byChain[i?.chain]?.producer,cap=i=>[18,26,36][i.level-5],step=i=>[9000,7000,5000][i.level-5],isActive=i=>producer(i)!==undefined&&i.level>=5,saleValue=i=>D.items[i?.chain+':'+i?.level]&&producer(i)===undefined?[2,3,5,8,12,18,26,38,54,76,108,152][i.level-1]||0:0;
function productionRates(i,weather,double=false){if(!isActive(i))return null;const matchingWeather=weather===D.generators[producer(i)].season,third=i.level>=7?12:0,second=(i.level>=6?28:0)-third+(matchingWeather?8:0);return{matchingWeather,cost:double?2:1,levels:[1,2,3].map(n=>n+(double?1:0)),probabilities:[(100-second-third)/100,second/100,third/100]}}
class Game extends Base.Game{
 constructor(o={}){super(o);const s=this.s;s.version=2;s.homeProgress=0;s.homeStyles=Array(8).fill(0);s.homeOwned=Array.from({length:8},()=>[0]);s.world='home';s.doubleEnergy=false;s.sourceGranted=[0];s.decorClaims=[];s.sideProgress=Array(8).fill(0);s.sideRead=[];s.sceneHomeRead=[];s.activity=null;s.activityCollections=[];s.activityCards=[];s.activityDust=0;s.activityPacks=0;s.activityPity=0;s.activityAlbumClaims=[];s.fishCollection=[];s.dinnerRounds=0;s.board=Array(63).fill(null);s.discovered=[];s.stats.discovered=0;s.stats.maxItems=0;s.stats.highItems=0;
  for(const [index,chain,lv,web]of [[0,'producer0',5,false],[1,'producer0',1,false],[2,'producer0',1,false],[7,'tool',1,false],[8,'tool',1,false],[14,'wood',1,false],[15,'wood',1,false],[28,'flower',1,true],[29,'flower',1,false]]){s.board[index]=this.make(chain,lv,web);this.discover(s.board[index])}s.neighbors=Array.from({length:3},(_,i)=>this.newOrder(i));
 }
 make(chain,level=1,web=false){const i=super.make(chain,level,web);if(isActive(i)){i.charge=cap(i);i.chargeStamp=this.s.stamp}if(chain==='flower'&&level>=5){i.autoStock=0;i.autoStamp=this.s.stamp}if(chain==='perfume')i.readyAt=this.s.stamp+90000;return i}
 get sourceCount(){return this.s.homeProgress===undefined?1:Math.min(16,this.s.homeProgress>=8?Math.max(2,this.area+1):this.s.homeProgress>=4?2:1)}
 get unlocked(){return Math.min(63,35+(this.s.homeProgress||0)+this.s.progress)}
 get project(){return this.s.homeProgress<8?{home:true,id:this.s.homeProgress,title:D.homeTitles[this.s.homeProgress],cost:D.homeCosts[this.s.homeProgress],npc:[1,4,1,4,3,2,5,0][this.s.homeProgress]}:D.projects[this.s.progress]?{...D.projects[this.s.progress],cost:D.projectCost(D.projects[this.s.progress])}:null}
 get decorValue(){const s=this.s;return(s.homeProgress||0)*40+s.progress*35+(s.homeOwned||[]).reduce((n,x)=>n+(x.length-1)*20,0)+s.decorOwned.reduce((n,x)=>n+(x.length-1)*25,0)}
 get doubleUnlocked(){return this.decorValue>=600}
 tick(){const r=super.tick();if(this.s.version!==2)return r;const s=this.s,now=s.stamp;
  for(const i of [...s.board,...s.inventory].filter(Boolean)){if(isActive(i)){const n=Math.floor((now-i.chargeStamp)/step(i));if(i.charge>=cap(i))i.chargeStamp=now;else if(n>0){i.charge=Math.min(cap(i),i.charge+n);i.chargeStamp+=n*step(i)}}if(i.chain==='flower'&&i.level>=5&&!i.web&&!i.bubble&&!i.path){const delay=Math.max(25000,45000-(i.level-5)*10000),n=Math.floor((now-i.autoStamp)/delay);if(i.autoStock>=3)i.autoStamp=now;else if(n>0){i.autoStock=Math.min(3,i.autoStock+n);i.autoStamp+=n*delay}}}
  const residueChains=new Set(['cord','glass',...D.paths.map(p=>p.residue)]);for(const i of [...s.board,...s.inventory])if(i&&!i.bubble&&residueChains.has(i.chain)&&!s.discovered.includes(i.chain+':'+i.level))this.discover(i);
  s.board.forEach((i,index)=>{if(i?.chain==='flower'&&i.autoStock>0&&!i.web&&!i.bubble&&!i.path){const adjacent=this.adjacent(index).find(n=>n<this.unlocked&&!s.board[n]);if(adjacent!==undefined){this.invalidate();i.autoStock--;s.board[adjacent]=this.make('petal');this.discover(s.board[adjacent]);this.emit('auto',{index:adjacent})}}});return r;
 }
 adjacent(index){const x=index%7,y=Math.floor(index/7),a=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if((dx||dy)&&x+dx>=0&&x+dx<7&&y+dy>=0&&y+dy<9)a.push((y+dy)*7+x+dx);return a}
 producerItems(id){return [...this.s.board,...this.s.inventory,...this.s.inbox].filter(i=>isActive(i)&&producer(i)===id&&!i.web&&!i.bubble)}
 grantSources(){for(let id=0;id<this.sourceCount;id++)if(!this.s.sourceGranted.includes(id)){this.s.sourceGranted.push(id);this.s.inbox.push(this.make('producer'+id,5));this.emit('sourceUnlock',{id})}}
 generate(){return{ok:false,reason:'在棋盘上点击带闪电的生产器。生成器零件也需要在棋盘上合成。'}}
 upgrade(){return false}
 setDouble(value){if(typeof value!=='boolean'||value&&!this.doubleUnlocked)return false;this.invalidate();this.s.doubleEnergy=value;return true}
 produce(index){this.tick();const s=this.s,i=s.board[index],fail=reason=>({ok:false,reason});if(!i||i.web||i.bubble)return fail('请选择可以使用的生产器');const target=this.empty();if(target<0)return fail('棋盘已满，先合成或收进仓库');
  if(isActive(i)){const cost=s.doubleEnergy&&this.doubleUnlocked?2:1;if(i.charge<1)return fail('储量恢复中，沙漏可以补充');if(s.energy<cost)return fail('体力不足，邻里订单、签到和补给可获得体力');const g=D.generators[producer(i)],roll=this.random(),weights=g.chains.length===2?[.78,1]:[.64,.9,1];let chain=g.chains[Math.min(g.chains.length-1,weights.findIndex(n=>roll<n))];if(producer(i)===0&&roll>=.9)chain='needle';const tierRoll=this.random();const rates=productionRates(i,s.weather,cost===2);let lv=tierRoll<rates.probabilities[2]?rates.levels[2]:tierRoll<rates.probabilities[1]+rates.probabilities[2]?rates.levels[1]:rates.levels[0];lv=Math.min(lv,D.items[chain+':1'].max);this.invalidate();s.energy-=cost;i.charge--;s.board[target]=this.make(chain,lv);s.stats.produced++;this.discover(s.board[target]);this.activityGain('produce');this.emit('spawn',{index:target});return{ok:true,index:target,item:cp(s.board[target])}}
  if(i.chain==='flower'&&i.level>=5&&!i.path){if(!i.autoStock)return fail('花瓣还在生长，等待自动生产');this.invalidate();i.autoStock--;s.board[target]=this.make('petal');this.discover(s.board[target]);return{ok:true,index:target}}
  if(i.chain==='perfume'){if(s.stamp<i.readyAt)return fail('香水陈化中，'+Math.ceil((i.readyAt-s.stamp)/1000)+'秒后留下海玻璃');const spaces=s.board.reduce((a,v,n)=>n<this.unlocked&&!v?[...a,n]:a,[]);if(spaces.length<1)return fail('先空出一格接收两份海玻璃');this.invalidate();s.board[index]=this.make('glass');s.board[target]=this.make('glass');this.discover(s.board[index]);return{ok:true,index}}
  let output,residue,count;if(i.chain==='partsbox'){output='producer'+(i.family??0);count=i.level===2?6:3;residue=null}else if(i.chain==='needle'&&i.level===4){output='cloth';count=8;residue='cord'}else if(i.chain==='petal'&&i.level===4){output='perfume';count=3;residue='glass'}else if(i.chain==='glass'&&i.level===5){output='toy';count=8;residue=null}else if(i.path){const p=D.paths.find(p=>p.id===i.path);if(s.stamp<(i.nextAt||0))return fail('支线物件冷却中');output=p.id;count=p.count;residue=p.residue}else return fail('这件物品可以继续合成、交单或收集');
  this.invalidate();if(i.left===undefined){i.left=count;i.used=true}const lv=i.chain==='partsbox'&&i.level===2?2:1;s.board[target]=this.make(output,lv);i.left--;if(i.path)i.nextAt=s.stamp+D.paths.find(p=>p.id===i.path).delay;if(i.left===0){s.board[index]=residue?this.make(residue):null;if(s.board[index])this.discover(s.board[index])}this.discover(s.board[target]);return{ok:true,index:target};
 }
 canProduce(i){return isActive(i)||i?.path||i?.chain==='partsbox'||i?.chain==='perfume'||i?.chain==='flower'&&i.level>=5||['needle','petal'].includes(i?.chain)&&i.level===4||i?.chain==='glass'&&i.level===5}
 refill(index,useTool=false){this.tick();const i=this.s.board[index];if(!isActive(i)||i.charge>=cap(i)||!useTool||this.s.tools.hourglass<1)return false;this.invalidate();this.s.tools.hourglass--;i.charge=cap(i);i.chargeStamp=this.s.stamp;return true}
 move(a,b,context='main'){if(context!=='main')return super.move(a,b,context);this.tick();const x=this.s.board[a],y=this.s.board[b];if(x&&y&&x.chain===y.chain&&x.level===y.level&&(x.used||y.used||x.path||y.path))return{ok:false,reason:'已开启的容器不能继续合成，先取完产物'};if(x?.chain==='partsbox'&&y?.chain==='partsbox'&&x.family!==y.family)return{ok:false,reason:'不同来源的零件箱不能合成'};
  if(x?.chain==='cord'&&x.level===4&&y?.chain==='cord'&&y.level===4&&a!==b&&a>=0&&b>=0&&a<this.unlocked&&b<this.unlocked&&!x.web&&!x.bubble&&!y.bubble){this.undoState={state:cp(this.s),at:this.clock()};this.s.board[a]=null;this.s.board[b]=this.make('toy');this.s.stats.merges++;this.s.pass+=4;this.discover(this.s.board[b]);this.emit('merge',{index:b,context:'main',level:1});return{ok:true,type:'merge',index:b}}
  const result=super.move(a,b,context);if(result.ok&&result.type==='merge'){const z=this.s.board[b];if(z.chain==='partsbox')z.family=x.family;this.activityGain('merge')}return result;
 }
 owned(req){return [...this.s.board,...this.s.inventory].filter(i=>i&&!i.web&&!i.bubble&&!i.used&&!i.path&&producer(i)===undefined&&i.chain===req.chain&&i.level===req.level).length}
 consume(reqs){if(!this.canDeliver(reqs))return false;for(const r of reqs)for(let n=0;n<(r.qty||1);n++){const match=i=>i&&!i.web&&!i.bubble&&!i.used&&!i.path&&producer(i)===undefined&&i.chain===r.chain&&i.level===r.level,index=this.s.board.findIndex(match);if(index>=0)this.s.board[index]=null;else this.s.inventory.splice(this.s.inventory.findIndex(match),1)}return true}
 newOrder(slot){if(this.s.version!==2)return super.newOrder(slot);const candidates=D.chains.filter(c=>!c.hidden&&this.s.sourceGranted?.includes(c.generator));let chain;if(slot===0)chain=candidates[Math.floor(this.random()*candidates.length)];else{const secrets=D.chains.filter(c=>c.hidden&&this.s.recipes.includes(c.id));chain=secrets.length&&this.random()<.14?secrets[Math.floor(this.random()*secrets.length)]:candidates[Math.floor(this.random()*candidates.length)]}const level=slot===0?2+Math.floor(this.random()*Math.min(3,2+this.season)):2+Math.floor(this.random()*Math.min(this.s.progress===64?11:7,2+this.season+Math.floor(this.s.stats.orders/35)));return{id:'order-'+this.s.uid++,slot,npc:1+Math.floor(this.random()*5),requirements:[{chain:chain.id,level:Math.min(level,chain.names.length),qty:1}],reward:{coins:25+2**(Math.min(level,chain.names.length)-1)*7,xp:18+level*3},title:['熟客的日常','街区预约单','认真做的礼物'][slot]}}
 deliver(kind='neighbor',slot=0){if(kind==='main')return false;const ok=super.deliver('neighbor',slot);if(ok){this.activityGain('order');if(this.s.stats.orders%4===0){const box=this.make('partsbox');box.family=this.s.sourceGranted[Math.floor(this.random()*this.s.sourceGranted.length)];this.s.inbox.push(box)}}return ok}
 build(){this.tick();const s=this.s,p=this.project;if(!p||s.pendingScene||s.coins<p.cost||!p.home&&s.level<3)return false;this.invalidate();s.coins-=p.cost;s.ready=false;s.stars=0;s.pass+=80;this.award({energy:20,xp:35});if(p.home){s.homeProgress++;s.pendingScene={kind:'home',id:p.id};if(s.homeProgress===8)s.world='island'}else{s.progress++;s.stats.built++;if(p.clue)s.clues.push(p.clue);if(p.part===3){s.tools.packs++;s.bonds[0]++;for(const i of [...s.board,...s.inventory].filter(isActive)){i.charge=cap(i);i.chargeStamp=s.stamp}const box=this.make('partsbox',2);box.family=Math.min(15,p.area);s.inbox.push(box)}s.pendingScene={kind:'project',id:p.id}}this.grantSources();this.emit('build',{project:p.id,home:!!p.home});return true}
 dismissScene(){if(this.s.pendingScene?.kind==='home'){const id=this.s.pendingScene.id;if(!this.s.sceneHomeRead.includes(id))this.s.sceneHomeRead.push(id);this.invalidate();this.s.pendingScene=null;return true}return super.dismissScene()}
 setWorld(world){if(!['home','island'].includes(world)||world==='island'&&(this.s.homeProgress<8||this.s.level<3))return false;this.s.world=world;return true}
 homeDecorate(index,style){const s=this.s;if(!integer(index,0,7)||index>=s.homeProgress||!integer(style,0,2))return false;if(!s.homeOwned[index].includes(style)){if(s.coins<100+style*40)return false;s.coins-=100+style*40;s.homeOwned[index].push(style)}this.invalidate();s.homeStyles[index]=style;return true}
 claimDecor(index){if(!integer(index,0,5)||this.decorValue<D.decorThresholds[index]||this.s.decorClaims.includes(index))return false;this.invalidate();this.s.decorClaims.push(index);this.award({coins:100+index*80,energy:40,packs:index%2});return true}
 tool(kind,index){const i=this.s.board[index];if(producer(i)!==undefined||i?.used||i?.path||['partsbox','perfume'].includes(i?.chain))return false;return super.tool(kind,index)}
 saleValue(i){return saleValue(i)}
 sell(index,confirm=false){const s=this.s,i=s.board[index],price=this.saleValue(i);if(!price||i.web||i.bubble||i.level>=4&&!confirm)return false;this.invalidate();s.coins+=price;s.sold={item:cp(i),price};s.board[index]=null;return true}
 get energyOffer(){const used=this.s.energyBuys,prices=[60,80,120,180,260,360];return{remaining:Math.max(0,prices.length-used),price:prices[used]??null}}
 buy(id){if(id!=='energy')return ['scissors','joker','hourglass','pack'].includes(id)?super.buy(id):false;this.tick();const offer=this.energyOffer,s=this.s;if(!offer.remaining||s.coins<offer.price)return false;this.invalidate();s.coins-=offer.price;s.energy+=100;s.energyBuys++;return true}
 parkProducer(index,where='board'){const s=this.s,list=where==='board'?s.board:where==='inventory'?s.inventory:null;if(!list||!integer(index,0,list.length-1))return false;const i=list[index];if(!i||producer(i)===undefined||i.web||i.bubble||i.used||i.path)return false;this.invalidate();s.inbox.push(i);if(where==='board')list[index]=null;else list.splice(index,1);this.emit('producerParked',{uid:i.uid});return true}
 activatePath(index){this.tick();const i=this.s.board[index],path=D.paths.find(p=>p.source===i?.chain&&p.level===i?.level);if(!path||i.web||i.bubble||i.path||i.used)return false;this.invalidate();i.path=path.id;i.left=path.count;i.used=true;i.nextAt=this.s.stamp;return true}
 recipe(){return false}
 discover(i){super.discover(i);if(D.paths?.some(p=>p.id===i.chain)&&!this.s.recipes.includes(i.chain)){this.s.recipes.push(i.chain);this.s.stats.recipes++;this.award({gems:3,xp:30})}}
 sideOrder(index){const p=D.paths[index],n=this.s.sideProgress[index];if(!p||n>=3)return null;return{chain:p.id,level:[2,4,6][n],qty:1}}
 sideDeliver(index){const r=this.sideOrder(index);if(!r||!this.canDeliver([r]))return false;this.invalidate();this.consume([r]);this.s.sideProgress[index]++;this.s.sideRead.push(index+':'+this.s.sideProgress[index]);this.award({coins:200*this.s.sideProgress[index],energy:50,packs:1,decor:this.s.sideProgress[index]===3?index*2:undefined});return true}
 activityGain(){/* Long activities connect here; state is added by the activity module. */}
 static restore(raw,o={}){try{
  if(raw?.version===1){const old=Base.Game.restore(raw,o);if(!old)return null;const g=new Game({...o,seed:raw.seed}),s=cp(old.s);s.version=2;s.homeProgress=s.progress?8:0;s.homeStyles=Array(8).fill(0);s.homeOwned=Array.from({length:8},()=>[0]);s.world=s.progress&&s.level>=3?'island':'home';s.doubleEnergy=false;s.sourceGranted=Array.from({length:Math.min(16,Math.max(s.progress?2:1,Math.floor(s.progress/4)+1))},(_,i)=>i);s.decorClaims=[];s.sideProgress=Array(8).fill(0);s.sideRead=[];s.sceneHomeRead=Array.from({length:s.homeProgress},(_,i)=>i);s.activity=null;s.coins+=s.stars*180;s.stars=0;s.ready=false;g.s=s;for(const id of s.sourceGranted){const lv=Math.min(7,4+s.generators[id].level),i=g.make('producer'+id,lv);s.inbox.push(i);g.discover(i)}for(const i of [...s.board,...s.inventory,...s.inbox].filter(Boolean))if(i.chain==='flower'&&i.level>=5){i.autoStock=0;i.autoStamp=s.stamp}s.pendingScene=s.pendingScene?.kind==='intro'?{kind:'intro'}:s.pendingScene;g.emit('migrated');g.tick();return g}
  if(raw?.version!==2)return null;const s=cp(raw);if(!integer(s.homeProgress,0,8)||!['home','island'].includes(s.world)||s.world==='island'&&(s.homeProgress<8||s.level<3)||typeof s.doubleEnergy!=='boolean'||!Array.isArray(s.sourceGranted)||!s.sourceGranted.includes(0)||!s.sourceGranted.every(n=>integer(n,0,15))||new Set(s.sourceGranted).size!==s.sourceGranted.length||!Array.isArray(s.sideProgress)||s.sideProgress.length!==8||s.sideProgress.some(n=>!integer(n,0,3)))return null;
  const unique=(a,max)=>Array.isArray(a)&&a.every(n=>integer(n,0,max-1))&&new Set(a).size===a.length;if(!unique(s.sceneHomeRead,s.homeProgress)||!unique(s.decorClaims,6)||!Array.isArray(s.sideRead)||new Set(s.sideRead).size!==s.sideRead.length||s.sideRead.some(id=>!/^([0-7]):([1-3])$/.test(id)||+id[2]>s.sideProgress[+id[0]]))return null;
  if(!Array.isArray(s.homeStyles)||s.homeStyles.length!==8||!Array.isArray(s.homeOwned)||s.homeOwned.length!==8||s.homeOwned.some((a,i)=>!unique(a,3)||!a.includes(0)||!a.includes(s.homeStyles[i])))return null;
  const pending=s.pendingScene;if(pending&&!(pending.kind==='intro'&&s.homeProgress===0&&s.progress===0||pending.kind==='home'&&integer(pending.id,0,7)&&pending.id===s.homeProgress-1||pending.kind==='project'&&pending.id===s.progress-1))return null;
  if(s.progress>0&&s.homeProgress!==8||s.ready||s.stars!==0)return null;
  const all=[...s.board,...s.inventory,...s.inbox].filter(Boolean);for(const i of all){if(isActive(i)&&(!integer(i.charge,0,cap(i))||!integer(i.chargeStamp,0,s.stamp)))return null;if(i.chain==='flower'&&i.level>=5&&(!integer(i.autoStock,0,3)||!integer(i.autoStamp,0,s.stamp)))return null;if(i.chain==='partsbox'&&(!integer(i.family,0,15)||!s.sourceGranted.includes(i.family)))return null;if(i.used!==undefined&&typeof i.used!=='boolean')return null;if(i.left!==undefined&&(!integer(i.left,1,8)||!i.used))return null;if(i.path&&(!D.paths.some(p=>p.id===i.path&&p.source===i.chain&&p.level===i.level)||!i.used||!integer(i.left,1,4)||!integer(i.nextAt)))return null;if(i.chain==='perfume'&&!integer(i.readyAt))return null}
  if(s.sold&&(!integer(s.sold.price,1)||![saleValue(s.sold.item),2**s.sold.item?.level].includes(s.sold.price)))return null;
  const projection=cp(s);if(projection.sold)projection.sold.price=2**projection.sold.item.level;projection.version=1;projection.ready=false;projection.stars=0;projection.pendingScene=pending?.kind==='home'?null:pending?.kind==='intro'&&s.progress?null:pending;const legacyOpen=Math.min(63,35+s.progress);for(let n=legacyOpen;n<63;n++)if(projection.board[n]){projection.inbox.push(projection.board[n]);projection.board[n]=null}if(!Base.Game.restore(projection,o))return null;
  const g=new Game({...o,seed:s.seed});g.s=s;if(s.sourceGranted.some(n=>n>=g.sourceCount)||s.doubleEnergy&&!g.doubleUnlocked||s.board.some((i,n)=>i&&n>=g.unlocked))return null;g.signals=[];g.tick();return g;
 }catch{return null}}
}
return{...Base,Game,producer,isActive,cap,step,productionRates};
});
