'use strict';
const assert=require('node:assert/strict'),D=require('./content.js'),{Game}=require('./engine.js');
function driver(seed='story-normal'){
 let now=new Date('2026-10-01T08:00:00+08:00').getTime(),g=new Game({seed,clock:()=>now}),operations=0,waitMs=0;const start=now;
 const wait=ms=>{now+=ms;waitMs+=ms;g.tick()},call=(name,...args)=>{operations++;const r=g[name](...args);assert.ok(r!==false&&r?.ok!==false,`${name} ${JSON.stringify(args)}: ${r?.reason||'false'}`);g.drain();return r};
 function collect(){if(g.s.signedDay<g.s.day)call('sign');D.passThresholds.forEach((n,i)=>{if(g.s.pass>=n&&!g.s.passClaims.includes(i))call('claimPass',i)});D.achievements.forEach(a=>{if(g.s.stats[a.stat]>=a.target&&!g.s.achievementClaims.includes(a.id))call('claimAchievement',a.id)});for(const weekly of [false,true])g.taskInfo(weekly).forEach((t,i)=>{if(t.value>=t.target&&!t.claimed)call('claimTask',i,weekly)});for(let i=0;i<6;i++)for(const t of [3,6,10])if(g.s.bonds[i]>=t&&!g.s.bondClaims.includes(i+':'+t))call('claimBond',i,t)}
 function clearBubbles(){for(let i=0;i<g.s.board.length;i++)if(g.s.board[i]?.bubble)call('bubble',i,false)}
 function mergeOne(chain,target,ctx='main'){const b=ctx==='night'?g.s.night.board:g.s.board;for(let level=1;level<target;level++){const matches=b.map((x,i)=>x?.chain===chain&&x.level===level&&!x.bubble?i:-1).filter(i=>i>=0),first=matches.find(i=>!b[i].web);if(first!==undefined){const second=matches.find(i=>i!==first);if(second!==undefined){call('move',first,second,ctx);return true}}}return false}
 function cleanup(chain,target){clearBubbles();if(g.empty()>=0)return;const i=g.s.board.findIndex(i=>i&&!i.web&&!i.bubble&&(i.chain!==chain||i.level>target));assert.ok(i>=0,'board has no safely disposable item');call('sell',i,true)}
 function make(chain,level,qty=1){const c=D.byChain[chain];assert.ok(c&&!c.hidden&&c.generator<g.sourceCount,`${chain} unlocked source`);let guard=0;while(g.owned({chain,level})<qty){assert.ok(++guard<200000,`make loop ${chain}:${level}`);if(mergeOne(chain,level))continue;cleanup(chain,level);const id=c.generator,source=g.s.generators[id];if(level>=5&&source.level<5&&g.s.coins>=80*source.level**2+100)call('upgrade',id);if(g.s.energy<2){collect();if(g.s.energy<2){if(g.s.coins>=80)call('buy','energy');else wait(40000)}}if(source.charge<1)wait((11-source.level)*1000);call('generate',id,chain);clearBubbles()}return true}
 function story(){call('dismissScene');while(g.s.progress<64){const p=g.project;for(const r of p.requirements)make(r.chain,r.level,r.qty);call('deliver');assert.equal(g.deliver(),false,'cannot deliver twice');call('build');assert.equal(g.build(),false,'cannot double build');if(p.part===3)call('sceneChoice',p.area%2);call('dismissScene');collect();const restored=Game.restore(g.serialize(),{clock:()=>now});assert.ok(restored,`restore at project ${p.id}`);g=restored}return g}
 function secret(id,target=6){const r=D.recipes.find(r=>r.id===id);assert.ok(r);let guard=0;while(g.owned({chain:id,level:target})<1){assert.ok(++guard<10000);if(mergeOne(id,target))continue;make(r.a.chain,r.a.level);make(r.b.chain,r.b.level);cleanup(id,target);call('recipe',id)}return true}
 function night(){call('startNight','drink');let guard=0;while(g.nightOrder){assert.ok(++guard<20000);const r=g.nightOrder,e=g.s.night;if(e.board.some(i=>i?.chain===r.chain&&i.level===r.level)){call('nightDeliver');continue}if(mergeOne(r.chain,r.level,'night'))continue;if(g.empty('night')<0){for(const chain of ['nightdrink','nightmusic'])if(mergeOne(chain,8,'night'))break;assert.ok(g.empty('night')>=0,'night full with no pair')}if(e.energy<1){if(e.tokens>=100*(1+e.buys))call('nightEnergy');else wait(30000)}if(e.stock<1)wait(7000);call('nightGenerate',false)}D.eventThresholds.forEach((n,i)=>{if(g.s.night.score>=n)call('claimNight',i)});return g.s.night}
 return {get game(){return g},get now(){return now},wait,call,collect,make,secret,story,night,mergeOne,clearBubbles,get summary(){return{seed,operations,waitHours:+(waitMs/3600000).toFixed(2),elapsedHours:+((now-start)/3600000).toFixed(2),progress:g.s.progress,level:g.s.level,coins:g.s.coins,energy:g.s.energy,merges:g.s.stats.merges,produced:g.s.stats.produced,discovered:g.s.discovered.length,recipes:g.s.recipes.length,claims:g.s.passClaims.length}}};
}
if(require.main===module){const fs=require('node:fs'),d=driver();d.story();console.log('story',d.summary);for(const c of D.chains.filter(c=>!c.hidden)){d.make(c.id,12);const index=d.game.s.board.findIndex(i=>i?.chain===c.id&&i.level===12&&!i.bubble);d.call('sell',index,true)}for(const r of D.recipes){d.secret(r.id,6);const index=d.game.s.board.findIndex(i=>i?.chain===r.id&&i.level===6);d.call('sell',index,true)}const e=d.night();for(const ending of D.endings)d.call('ending',ending.id);d.collect();const report={...d.summary,maxOrdinary:D.chains.filter(c=>!c.hidden&&d.game.s.discovered.includes(c.id+':12')).length,maxSecret:D.recipes.filter(c=>d.game.s.discovered.includes(c.id+':6')).length,clues:d.game.s.clues.length,read:d.game.s.read.length,night:{orders:e.order,score:e.score,claims:e.claimed.length},endings:D.endings.map(e=>e.id)};fs.writeFileSync(__dirname+'/simulation-results.json',JSON.stringify(report,null,2));console.log(report)}
module.exports={driver};
