(()=>{'use strict';
  const C=HotContent,E=HotEngine,$=id=>document.getElementById(id),KEY='hotsearch-reaping-v1'+(new URLSearchParams(location.search).get('review')==='1'?'-review':'');
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let s=E.create(),loadError='',view='hot',board='real',onlyFavorites=false,feed={items:[]},previous=new Map(),previousHeat=new Map(),busy=false,lastSave=0,lastFrame=performance.now(),lastUi=0,eventCursor=0,lastBattle=null,fx=[],history=[],nextHistory=0,toastTimer=0,audio=null,hidden=false,exportText='';
  const input={x:0,y:0},keys=new Set(),images={};
  try{const raw=localStorage.getItem(KEY);if(raw)s=E.restore(raw);}catch(e){loadError='旧存档未能读取，已保留备份。';try{localStorage.setItem(KEY+'-recovery',localStorage.getItem(KEY)||'');}catch(_){}}
  const initialAway=(Date.now()-s.lastSeen)/1000;
  if(initialAway>60){const r=E.offline(s,initialAway);if(r.reward)setTimeout(()=>toast('离线训练 +'+r.reward+' 暖光，按已通关记录结算'),600);}
  function save(){s.lastSeen=Date.now();try{localStorage.setItem(KEY,JSON.stringify(s));}catch(e){toast('浏览器无法保存；可以在设置中导出存档。');}}
  function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3000);}
  function modal(html){$('dialog-content').innerHTML=html;if(!$('dialog').open)$('dialog').showModal();}
  function close(){if($('dialog').open)$('dialog').close();}
  function heat(n){return n>=10000?(n/10000).toFixed(1)+'万':Math.round(n).toLocaleString('zh-CN');}
  function time(n){return Math.floor(n/60).toString().padStart(2,'0')+':'+Math.floor(n%60).toString().padStart(2,'0');}
  function safeUrl(item){try{const u=new URL(item.url);if(u.protocol==='https:'&&['s.weibo.com','weibo.com','www.weibo.com'].includes(u.hostname))return u.href;}catch(_){}return 'https://s.weibo.com/weibo?q='+encodeURIComponent(item.title);}
  function sprite(ctx,index,x,y,w,h){const img=images.sprites;if(!img?.complete||!img.naturalWidth)return false;const boxes=[[32,32,383,409],[436,0,403,452],[865,20,380,419],[0,437,410,367],[412,437,424,382],[839,428,415,385],[0,809,418,445],[417,811,423,443],[837,801,417,453]];const box=boxes[index];ctx.drawImage(img,...box,x,y,w,h);return true;}
  function loadImages(){const initial=s.battle?C.maps[s.battle.map].art:'sprout';for(const name of ['sprites',...C.maps.map(m=>m.art)]){const img=new Image();images[name]=img;img.onload=()=>{portraits();};img.onerror=()=>{img.failed=true;};if(name==='sprites'||name===initial)img.src='hotsearch-reaping/assets/'+name+'.png';}}
  function portraits(){const main=$('home-portrait');if(main){const ctx=main.getContext('2d');ctx.clearRect(0,0,240,260);sprite(ctx,C.heroes.findIndex(h=>h.id===s.hero),10,6,216,240);}document.querySelectorAll('canvas[data-hero]').forEach(el=>{const ctx=el.getContext('2d');ctx.clearRect(0,0,130,150);sprite(ctx,Number(el.dataset.hero),10,0,110,145);});}
  function show(next){view=next;for(const el of document.querySelectorAll('main>.view'))el.hidden=el.id!==next+'-view';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===next));input.x=input.y=0;keys.clear();if(next==='hot')ranks();if(next==='workshop')workshop();if(next==='archive')archive();if(next==='settings')settings();portraits();updateUi();window.scrollTo({top:0,behavior:'instant'});}
  async function loadFeed(force=false){if(busy)return;busy=true;$('refresh-feed').disabled=true;$('refresh-feed').classList.add('loading');let connected=false,data;
    try{if(['127.0.0.1','localhost'].includes(location.hostname)){const response=await fetch('http://127.0.0.1:8767/feed'+(force?'?refresh=1':''),{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('服务不可用');data=await response.json();connected=data.status==='live';}
      else throw Error('使用已读取快照');
    }catch(_){try{const response=await fetch('hotsearch-reaping/feed.json',{cache:'no-store'});data=await response.json();}catch(e){data=feed;toast('无法读取榜单，固定战役仍可游玩。');}}
    if(Array.isArray(data?.items)&&data.items.length){previous=new Map(feed.items.map(i=>[i.title,i.rank]));previousHeat=new Map(feed.items.map(i=>[i.title,i.heat]));feed={...data,items:data.items.filter(i=>typeof i.title==='string'&&i.title.length<=100&&Number.isFinite(i.rank)&&Number.isFinite(i.heat)).slice(0,50),connected};const date=new Date(feed.obtainedAt);$('feed-source').textContent=(connected?'公开榜单已读取':'官方榜单快照')+' · '+(Number.isNaN(+date)?'时间未知':date.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}))+' · '+feed.items.length+'条';if(force)toast(connected?'榜单已刷新':'连接暂不可用，保留带时间的官方快照');}
    if($('settings-feed-source'))$('settings-feed-source').textContent=$('feed-source').textContent;busy=false;$('refresh-feed').disabled=false;$('refresh-feed').classList.remove('loading');ranks();
  }
  function ranks(){const list=$('rank-list'),old=new Map(Array.from(list.querySelectorAll('[data-title]')).map(el=>[el.dataset.title,el.getBoundingClientRect().top]));const query=$('search').value.trim();$('feed-heading').innerHTML=board==='game'?'<span>◉</span> 清屏战报榜':board==='training'?'<span>◉</span> 固定战役':'<span>◉</span> 微博热搜';$('feed-source').parentElement.hidden=board!=='real';$('refresh-feed').hidden=board!=='real';$('favorites-filter').hidden=board==='training';$('search').placeholder=board==='game'?'搜索清屏战报':board==='training'?'搜索固定战役':'搜索热搜话题';
    if(board==='training'){list.innerHTML=C.maps.map((m,i)=>{if(query&&!m.name.includes(query)&&!m.chapter.includes(query))return '';const unlocked=s.highest>=i*6;return `<article class="card stage-card"><img src="hotsearch-reaping/assets/${m.art}.png" alt="${esc(m.name)}原创章节场景"><div class="stage-body"><h3>${i+1}. ${m.name}</h3><p>${esc(m.rule)}</p><div class="stage-grid">${Array.from({length:6},(_,j)=>{const id=i*6+j;return `<button data-stage="${id}" class="${id<s.highest?'done':id===s.highest?'frontier':''}" ${id>Math.min(35,s.highest)?'disabled':''}>${j===5?'首领':j+1}${s.records[id]?'<small class="stars">'+('★'.repeat(s.records[id].stars))+'</small>':''}</button>`;}).join('')}</div><div class="chapter-buttons"><button data-story="${i*2}" ${!unlocked?'disabled':''}>章节故事</button><button data-story="${i*2+1}" ${s.highest<(i+1)*6?'disabled':''}>归档结局</button></div></div></article>`;}).join('')||'<div class="empty">没有找到对应的章节。</div>';return;}
    const items=board==='game'?Object.values(s.topicRecords).sort((a,b)=>b.kills-a.kills).map((r,i)=>({title:r.title,rank:i+1,heat:r.kills,tag:r.stars===3?'优':'',record:r})):feed.items;
    const filtered=items.filter(i=>(!query||i.title.includes(query))&&(!onlyFavorites||s.favorites.includes(i.title)));const max=Math.max(1,...items.map(i=>i.heat));
    list.innerHTML=filtered.map((item,idx)=>{const oldRank=previous.get(item.title),delta=board==='real'&&oldRank?oldRank-item.rank:0;const rankId=feed.items.findIndex(x=>x.title===item.title);const favorite=s.favorites.includes(item.title);return `<button class="rank-row" data-title="${esc(item.title)}" ${board==='game'?`data-report="${esc(item.title)}"`:`data-topic="${rankId}"`} style="animation-delay:${Math.min(idx,12)*.02}s"><span class="rank-number rank-top-${Math.min(4,item.rank)}">${item.rank}</span><span class="rank-copy"><strong>${esc(item.title)} ${favorite?'☆':''}</strong><small>${board==='game'?'清屏 '+item.heat+' · '+time(item.record.time):heat(item.heat)+' 搜索指数'}${item.tag?`<i class="heat-tag ${item.tag==='新'?'new':item.tag==='爆'?'boom':''}">${esc(item.tag)}</i>`:''}</small></span><span class="rank-trend ${delta>0?'up':delta<0?'down':''}">${delta>0?'↑ '+delta:delta<0?'↓ '+Math.abs(delta):'—'}</span><i class="rank-heat" style="width:${Math.max(3,item.heat/max*85)}%"></i></button>`;}).join('')||`<div class="empty">${board==='game'?'还没有话题战报<br>完成一次话题清屏，就能在这里看到成绩。':feed.items.length?'没有找到符合条件的话题':'正在读取榜单…'}</div>`;
    if(s.settings.motion)for(const el of list.querySelectorAll('[data-title]')){const item=items.find(i=>i.title===el.dataset.title);if(board==='real'&&item){const bar=el.querySelector('.rank-heat'),before=previousHeat.get(item.title);bar.animate([{transform:`scaleX(${before===undefined?0:Math.max(.03,before/Math.max(1,item.heat))})`},{transform:'scaleX(1)'}],{duration:900,easing:'cubic-bezier(.2,.8,.2,1)'});if(before!==undefined&&before!==item.heat){const label=el.querySelector('small'),text=label.firstChild,start=performance.now();const count=now=>{if(!el.isConnected)return;const t=Math.min(1,(now-start)/850),v=before+(item.heat-before)*(1-Math.pow(1-t,3));text.textContent=heat(v)+' 搜索指数';if(t<1)requestAnimationFrame(count);};requestAnimationFrame(count);}}if(!old.has(el.dataset.title))continue;const delta=old.get(el.dataset.title)-el.getBoundingClientRect().top;if(Math.abs(delta)>2)el.animate([{transform:`translateY(${delta}px)`},{transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.2,.8,.2,1)'});}
    if(filtered.length)list.insertAdjacentHTML('beforeend',`<div class="rank-end">${board==='game'?'个人战报排名 · '+filtered.length+'条记录':'已显示 '+filtered.length+' 条 · 数据来自官方公开榜单'}</div>`);
  }
  function topic(index){const item=feed.items[index];if(!item)return;modal(`<div class="modal"><small class="saved-mark">微博公开热搜 · 第${item.rank}位</small><h2>${esc(item.title)}</h2><div class="heat-detail">${heat(item.heat)} <small>搜索指数</small></div><p>进入独立的舆论清屏战场：关注规模影响初始强度，复读、扩音与断章噪声由游戏规则生成。</p><p class="source-note">战斗不判定真实事件真假，也不会改变微博排名。</p><div class="modal-actions"><button data-action="close">返回</button><button data-favorite="${index}">${s.favorites.includes(item.title)?'★ 已收藏':'☆ 收藏'}</button></div><div class="modal-actions"><a class="source-note" href="${esc(safeUrl(item))}" target="_blank" rel="noopener noreferrer">查看微博话题 ↗</a><button class="primary" data-launch-topic="${index}">进入话题清屏</button></div></div>`);}
  function launch(stage,topic=null,endless=false){if(s.battle?.phase==='playing'&&s.battle.time>3){modal(`<div class="modal"><h2>开始新的清屏？</h2><p>当前战斗将结束；已获得的暖光和永久成长保留。</p><div class="modal-actions"><button data-action="close">继续当前</button><button class="primary" data-confirm-launch="${stage}" data-topic-id="${topic?feed.items.indexOf(topic):-1}" data-endless="${endless?'1':'0'}">开始新战斗</button></div></div>`);return;}doLaunch(stage,topic,endless);}
  function doLaunch(stage,topic=null,endless=false){if(!E.start(s,stage,topic,endless)){toast('请先完成前面的固定战役。');return;}close();show('battle');save();}
  function workshop(){const panel=$('workshop-view');panel.innerHTML=`<h2 class="page-title">清屏工坊</h2><p class="page-subtitle">永久成长与固定武器组合。没有随机三选一，四个武器槽由你安排。</p><div class="hero-grid">${C.heroes.map((h,i)=>`<button class="hero-card ${s.hero===h.id?'selected':''}" data-hero-select="${h.id}"><canvas width="130" height="150" data-hero="${i}"></canvas><strong>${h.name}</strong><small>${h.role}</small></button>`).join('')}</div><p class="source-note">${esc(C.heroes.find(h=>h.id===s.hero).desc)} · 角色切换用于下一场交战。</p><div class="section-title">固定武器组合 <small>已装备 ${s.weapons.length}/4</small></div><div class="weapon-grid">${C.weapons.map(w=>`<article class="card"><span class="weapon-icon">${w.icon}</span><h3>${w.name} <span class="rank">${s.levels[w.id]>=5?'已进阶':'Lv.'+s.levels[w.id]}</span></h3><p>${w.desc}</p><div class="buttons"><button data-weapon-up="${w.id}" ${s.highest<w.unlock||s.levels[w.id]>=5||s.coins<E.cost(s,w.id,true)?'disabled':''}>${s.highest<w.unlock?'通关'+w.unlock+'关':s.levels[w.id]>=5?'已进阶':'☀ '+E.cost(s,w.id,true)}</button><button data-equip="${w.id}" class="${s.weapons.includes(w.id)?'active':''}" ${!s.levels[w.id]?'disabled':''}>${s.weapons.includes(w.id)?'已装备':'装备'}</button></div></article>`).join('')}</div><div class="section-title">守望研究 <small>清屏收入用于永久提升</small></div>${C.upgrades.map(u=>`<div class="card research-row"><div><strong>${u.name} <span class="stars">${s.upgrades[u.id]}/${u.max}</span></strong><small>${u.desc}</small></div><button data-upgrade="${u.id}" ${s.highest<u.unlock||s.upgrades[u.id]>=u.max||s.coins<E.cost(s,u.id)?'disabled':''}>${s.highest<u.unlock?'通关'+u.unlock+'关':s.upgrades[u.id]>=u.max?'已满级':'☀ '+E.cost(s,u.id)}</button></div>`).join('')}<div class="section-title">装备预设 <small>最多三组</small></div>${presetsMarkup()}<input id="preset-name" class="preset-input" maxlength="20" placeholder="给当前配置起个名字"><button data-action="save-preset" class="primary" style="width:100%;margin-top:9px">保存当前配置</button>`;portraits();}
  function presetsMarkup(){return s.presets.map((p,i)=>`<div class="preset-row"><button data-preset="${i}">${esc(p.name)} · ${C.heroes.find(h=>h.id===p.hero).name}</button><button data-delete-preset="${i}">移除</button></div>`).join('')||'<p class="source-note">保存角色、武器组合和攻击优先级，下次一键切换。</p>';}
  function archive(){const p=$('archive-view');p.innerHTML=`<h2 class="page-title">潮讯档案</h2><p class="page-subtitle">每一次清屏，都给讨论留下一点空间。</p><div class="stat-grid">${[['累计清屏',s.stats.kills],['交战胜利',s.stats.wins],['最高连击',s.stats.combo],['固定战役',s.highest+'/36'],['清理扩音',s.stats.sources],['查证次数',s.stats.verifies]].map(([label,val])=>`<div class="card"><strong>${val}</strong><small>${label}</small></div>`).join('')}</div><div class="section-title">章节故事 <small>图片生成的原创场景</small></div>${C.maps.map((m,i)=>`<article class="card stage-card"><img src="hotsearch-reaping/assets/${m.art}.png" alt="${esc(m.name)}"><div class="stage-body"><h3>${m.name} · ${m.chapter}</h3><div class="chapter-buttons"><button data-story="${i*2}" ${s.highest<i*6?'disabled':''}>${C.stories[i*2][0]}</button><button data-story="${i*2+1}" ${s.highest<(i+1)*6?'disabled':''}>${C.stories[i*2+1][0]}</button></div></div></article>`).join('')}<div class="section-title">噪声图鉴 <small>全部为虚构游戏实体</small></div><div class="codex-grid">${Object.entries(C.enemyKinds).map(([id,e])=>`<article class="card"><h3>${e.name}</h3><p>${id==='repeat'?'存在一段时间后分裂。':id==='source'?'持续生成刷屏团，优先清源阻止增殖。':id==='shield'?'护盾抵挡攻击；查证直接破盾。':id==='rush'?'移动更快，降温可以减速。':id==='speaker'?'远距离发出噪声弹丸。':'追逐守望者，成群出现。'}</p></article>`).join('')}</div><div class="section-title">守望成就 <small>${s.badges.length}/${C.achievements.length}</small></div>${C.achievements.map(a=>{const val=a.key==='highest'?s.highest:s.stats[a.key],done=s.badges.includes(a.id);return `<div class="achievement ${done?'earned':''}"><span>${done?'✦':'◇'} ${a.name}</span><small>${done?'已获得 ☀'+a.reward:Math.min(val,a.goal)+' / '+a.goal}</small></div>`;}).join('')}`;}
  function settings(){const p=$('settings-view');p.innerHTML=`<h2 class="page-title">守望手册</h2><p class="page-subtitle">自动巡航，少量介入。舒服地清场，也看清战斗里的因果。</p><div class="card"><h3>舆论清屏怎么玩</h3><p>复读怪会分裂，扩音怪会持续刷出噪声。切到“优先清源”，先处理源头。</p><p>拾取上下文，点击查证破除断章护盾；降温减速并降低噪声压力；满能量后置顶大范围清场。</p><p>摇杆或WASD临时接管走位；松开就恢复自动。Q查证、E降温、空格置顶、Shift闪避。</p><p>热搜标题是话题入口，战斗对象是虚构噪声。真实榜单排名不受游戏结果影响。</p></div><div class="card"><h3>舒适设置</h3>${[['sound','战斗音效'],['haptics','触控震动'],['motion','动态画面与榜位过渡']].map(([id,label])=>`<label class="settings-row">${label}<input type="checkbox" data-setting="${id}" ${s.settings[id]?'checked':''}></label>`).join('')}<p class="source-note">关闭动态会减少粒子和榜位过渡。系统“减少动态”设置也会自动生效。</p></div><div class="card"><h3>离线训练</h3><p>离开后，按已通关关卡的最高收益速度×35%获得暖光，最多8小时。未通关的首领仍需实际交战；离线不会替你推进固定战役。</p><p>累计离线训练 ${Math.floor(s.stats.offline/60)} 分钟。</p></div><div class="card"><h3>本地存档</h3><p>自动保存进度和当前交战；导入会先校验，失败时保留现有进度。</p><div class="button-row"><button data-action="export">导出存档</button><button data-action="import">导入存档</button></div><button data-action="reset" class="danger" style="width:100%;margin-top:9px">开启新旅程</button></div><div class="card"><h3>榜单来源</h3><p id="settings-feed-source">${esc($('feed-source').textContent)}</p><p>刷新前后对比同一词条计算升降；首次读取不编造趋势。连接不可用时保留官方页面或接口读取快照。</p><a class="source-note" href="https://s.weibo.com/top/summary?cate=realtimehot" target="_blank" rel="noopener noreferrer">查看微博官方热搜 ↗</a></div>`;}
  function story(id){if(id<0||id>=12||s.highest<(id%2?Math.floor(id/2)*6+6:Math.floor(id/2)*6)){toast('完成对应章节后解锁。');return;}const m=C.maps[Math.floor(id/2)],text=C.stories[id];modal(`<button data-action="close" class="dialog-close" aria-label="关闭故事">×</button><img class="story-art" src="hotsearch-reaping/assets/${m.art}.png" alt="${m.name}原创剧情插画"><div class="story-copy"><small>CHAPTER ${Math.floor(id/2)+1} · ${m.name}</small><h2>${text[0]}</h2><p>${text[1]}</p><button data-action="close" class="primary">回到守望</button></div>`);}
  function updateUi(){const coins=$('coins');coins.textContent=Math.floor(s.coins).toLocaleString('zh-CN');document.body.classList.toggle('reduced-motion',!s.settings.motion);if(view==='workshop')document.querySelectorAll('[data-weapon-up],[data-upgrade]').forEach(button=>{const weapon=!!button.dataset.weaponUp,id=button.dataset.weaponUp||button.dataset.upgrade,d=(weapon?C.weapons:C.upgrades).find(x=>x.id===id),level=weapon?s.levels[id]:s.upgrades[id],max=weapon?5:d.max;button.disabled=s.highest<d.unlock||level>=max||s.coins<E.cost(s,id,weapon);button.textContent=s.highest<d.unlock?'通关'+d.unlock+'关':level>=max?(weapon?'已进阶':'已满级'):'☀ '+E.cost(s,id,weapon);});const b=s.battle;$('ongoing').hidden=!b;if(b)$('ongoing').innerHTML=`<span>${b.phase==='playing'?'清屏进行中':b.phase==='paused'?'交战已暂停':b.phase==='won'?'清屏完成':'准备再次守望'} · ${b.kills} 噪声</span><button data-view="battle">去看看 ›</button>`;
    $('auto').classList.toggle('active',s.auto);$('auto').textContent=s.auto?'自动走位':'手动走位';$('auto-skill').classList.toggle('active',s.autoSkill);$('auto-skill').textContent=s.autoSkill?'自动技能':'手动技能';$('advance').textContent=s.autoAdvance?'自动推进 ON':'自动推进 OFF';$('policy').textContent=C.policies.find(p=>p.id===s.policy).name;$('speed').textContent=s.speed+'×';
    if(!b){$('battle-banner').hidden=false;$('battle-banner').innerHTML='<strong>准备清屏</strong><small>从热搜选择话题，或挑战固定战役。</small><button class="primary" data-stage="0">开始第一关</button>';return;}
    $('battle-kind').textContent=(b.topic?'话题战场 · 游戏模拟':b.endless?'无尽风暴':'固定战役 '+(b.stage+1)+'/36')+' · '+C.maps[b.map].name;$('battle-topic').textContent=b.topic?.title||C.trainingTitles[b.map];$('hp-text').textContent=Math.ceil(b.p.hp)+' / '+b.p.max;$('hp-bar').style.width=b.p.hp/b.p.max*100+'%';$('wave').textContent='第 '+b.wave+' 波';$('timer').textContent=time(b.time);$('kills').textContent='清屏 '+b.kills;$('combo').textContent='连击 ×'+b.combo;$('combo').style.opacity=b.combo?1:.55;$('context-text').textContent=Math.floor(b.context);$('context-bar').style.width=b.context+'%';$('pressure-text').textContent=Math.floor(b.pressure);$('pressure-bar').style.width=b.pressure+'%';$('pause').textContent=b.phase==='paused'?'▶':'Ⅱ';$('battle-tip').textContent='扩音源 '+b.enemies.filter(e=>e.kind==='source').length+' · 断章盾 '+b.enemies.filter(e=>e.shield>0).length+' · 查证破盾，降温减速，置顶清屏。';
    const boss=b.enemies.find(e=>e.kind==='boss');$('boss-hud').hidden=!boss;if(boss){$('boss-name').textContent=C.maps[b.map].boss;$('boss-bar').style.width=Math.max(0,boss.hp/boss.max)*100+'%';}
    $('verify').disabled=b.context<25||b.skillCD>0||b.phase!=='playing';$('cool').disabled=b.coolCD>0||b.phase!=='playing';$('dash').disabled=b.dashCD>0||b.phase!=='playing';$('pin').disabled=b.energy<100||b.phase!=='playing';$('verify').querySelector('small').textContent=b.skillCD>0?Math.ceil(b.skillCD)+'秒':'25上下文';$('cool').querySelector('small').textContent=b.coolCD>0?Math.ceil(b.coolCD)+'秒':'就绪';$('dash').querySelector('small').textContent=b.dashCD>0?Math.ceil(b.dashCD)+'秒':'就绪';$('pin').querySelector('small').textContent=Math.floor(b.energy)+'%';
    $('battle-banner').hidden=b.phase==='playing';if(b.phase==='paused')$('battle-banner').innerHTML='<strong>稍作休息</strong><small>交战已暂停。</small><button data-action="pause" class="primary">继续清屏</button>';else if(b.phase==='won'||b.phase==='lost')$('battle-banner').innerHTML=`<strong>${b.phase==='won'?'清屏完成':'稍作整备'}</strong><small>${b.kills}次清屏 · 最高连击${b.peak}<br>本场获得 ☀${b.earned}${s.autoAdvance?'<br>'+Math.max(0,Math.ceil(b.wait))+'秒后自动继续':''}</small><button data-action="workshop">前往工坊</button>`;
  }
  function sound(type){if(!s.settings.sound||!audio)return;const now=audio.currentTime;if(sound.last&&now-sound.last<.06)return;sound.last=now;const osc=audio.createOscillator(),g=audio.createGain();osc.connect(g);g.connect(audio.destination);osc.type='sine';const strong=['pin','victory','bossdown'].includes(type);osc.frequency.setValueAtTime(strong?180:type==='pickup'?680:type==='hurt'?110:330,now);osc.frequency.exponentialRampToValueAtTime(strong?600:170,now+.09);g.gain.setValueAtTime(.015,now);g.gain.exponentialRampToValueAtTime(.001,now+.12);osc.start(now);osc.stop(now+.13);}
  function audioStart(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}
  document.addEventListener('click',event=>{const button=event.target.closest('button,a');if(!button)return;const d=button.dataset;if(button.disabled)return;if(d.view){show(d.view);return;}if(d.board){board=d.board;$('search').value='';document.querySelectorAll('[data-board]').forEach(b=>b.classList.toggle('selected',b.dataset.board===board));ranks();return;}if(d.topic!==undefined){topic(Number(d.topic));return;}if(d.favorite!==undefined){const item=feed.items[Number(d.favorite)];if(!s.favorites.includes(item.title)&&s.favorites.length>=100){toast('最多收藏100个话题。');return;}s.favorites=s.favorites.includes(item.title)?s.favorites.filter(t=>t!==item.title):[...s.favorites,item.title];save();topic(Number(d.favorite));ranks();return;}
    if(d.launchTopic!==undefined){const item=feed.items[Number(d.launchTopic)];launch(Math.min(35,s.highest),item);return;}if(d.confirmLaunch!==undefined){doLaunch(Number(d.confirmLaunch),Number(d.topicId)>=0?feed.items[Number(d.topicId)]:null,d.endless==='1');return;}if(d.stage!==undefined){launch(Number(d.stage));return;}if(d.story!==undefined){story(Number(d.story));return;}
    if(d.report){const r=s.topicRecords[d.report];modal(`<div class="modal"><h2>${esc(d.report)}</h2><p>个人游戏战报：清屏${r.kills} · 最高连击${r.peak} · 用时${time(r.time)} · 剩余清晰度${Math.round(r.clarity*100)}%</p><button data-action="close" class="primary">返回榜单</button></div>`);return;}
    if(d.heroSelect){s.hero=d.heroSelect;save();workshop();portraits();return;}if(d.weaponUp){if(E.upgrade(s,d.weaponUp,true)){save();workshop();}return;}if(d.upgrade){if(E.upgrade(s,d.upgrade)){save();workshop();}return;}if(d.equip){if(!E.equip(s,d.equip))toast('保留至少一件武器，最多装备四件。');save();workshop();return;}
    if(d.skill){if(E.skill(s,d.skill)){audioStart();save();updateUi();}else toast(d.skill==='verify'?'需要25上下文且查证已冷却':d.skill==='pin'?'置顶需要100%能量':'技能尚在冷却');return;}
    if(d.policyId){s.policy=d.policyId;close();save();updateUi();return;}if(d.preset!==undefined){const p=s.presets[Number(d.preset)];s.hero=p.hero;s.weapons=[...p.weapons];s.policy=p.policy;save();workshop();toast('已应用：'+p.name);return;}if(d.deletePreset!==undefined){s.presets.splice(Number(d.deletePreset),1);save();workshop();return;}
    switch(d.action){case'close':close();break;case'refresh':loadFeed(true);break;case'favorites':onlyFavorites=!onlyFavorites;$('favorites-filter').classList.toggle('active',onlyFavorites);ranks();break;case'campaign':board='training';$('search').value='';show('hot');document.querySelectorAll('[data-board]').forEach(b=>b.classList.toggle('selected',b.dataset.board===board));ranks();$('rank-list').scrollIntoView({behavior:s.settings.motion?'smooth':'instant',block:'start'});break;
      case'pause':if(s.battle){s.battle.phase=s.battle.phase==='paused'?'playing':s.battle.phase==='playing'?'paused':s.battle.phase;save();updateUi();}break;case'auto':s.auto=!s.auto;save();updateUi();break;case'autoSkill':s.autoSkill=!s.autoSkill;save();updateUi();break;case'advance':s.autoAdvance=!s.autoAdvance;save();updateUi();break;case'speed':s.speed=s.speed===1?2:1;save();updateUi();break;case'workshop':close();show('workshop');break;
      case'policy':modal(`<div class="modal"><h2>攻击优先级</h2><p>固定策略持续生效，也可以用摇杆临时介入。</p>${C.policies.map(p=>`<button data-policy-id="${p.id}" class="policy-button ${s.policy===p.id?'active':''}"><b>${p.name}</b><small>${p.desc}</small></button>`).join('')}<div class="modal-actions"><button data-action="close">返回战斗</button></div></div>`);break;
      case'bag':modal(`<div class="modal"><h2>当前武器组合</h2>${s.weapons.map(id=>{const w=C.weapons.find(x=>x.id===id);return `<p>${w.icon} ${w.name} · Lv.${s.levels[id]}${s.levels[id]>=5?' · 已进阶':''}<br>${w.desc}</p>`;}).join('')}<div class="modal-actions"><button data-action="close">继续战斗</button><button data-action="workshop">调整组合</button></div></div>`);break;
      case'wallet':toast('暖光来自实际清屏与训练，可在工坊购买永久成长。');break;case'endless':if(s.highest<6)toast('完成第一章后解锁无尽风暴。');else launch(Math.min(35,s.highest),null,true);break;
      case'fullscreen':if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>toast('当前浏览器不支持全屏。'));break;
      case'save-preset':{const name=$('preset-name').value.trim().slice(0,20);if(!name){toast('先给配置起个名字。');break;}if(s.presets.length>=3){toast('最多三组，可以先移除旧预设。');break;}s.presets.push({name,hero:s.hero,weapons:[...s.weapons],policy:s.policy});save();workshop();break;}
      case'export':{save();exportText=JSON.stringify(s,null,2);modal('<div class="modal"><h2>导出守望进度</h2><p>可以下载JSON文件；浏览器不支持下载时，也可以保存存档文本。</p><div class="modal-actions"><button data-action="download-save" class="primary">下载存档文件</button><button data-action="save-text">显示存档文本</button></div><textarea id="save-text" class="save-text" aria-label="存档文本" readonly hidden></textarea><div class="modal-actions"><button data-action="close">完成</button></div></div>');break;}case'download-save':{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([exportText],{type:'application/json'}));a.href=url;a.download='热搜清屏存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}case'save-text':$('save-text').hidden=false;$('save-text').value=exportText;$('save-text').focus();$('save-text').select();break;case'import':$('import-file').click();break;
      case'reset':modal('<div class="modal"><h2>开启新旅程？</h2><p>会清空本游戏的进度。建议先导出存档。</p><div class="modal-actions"><button data-action="close">保留进度</button><button data-action="confirm-reset" class="danger">确认新旅程</button></div></div>');break;case'confirm-reset':s=E.create();save();close();show('hot');toast('新的守望开始了。');break;
    }
  });
  $('search').addEventListener('input',ranks);document.addEventListener('change',e=>{if(e.target.dataset.setting){s.settings[e.target.dataset.setting]=e.target.checked;if(e.target.dataset.setting==='sound'&&e.target.checked)audioStart();save();updateUi();}});
  $('import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const restored=E.restore(await file.text());modal('<div class="modal"><h2>存档校验通过</h2><p>导入将替换当前本地进度。</p><div class="modal-actions"><button data-action="close">保留当前</button><button id="accept-import" class="primary">确认导入</button></div></div>');$('accept-import').addEventListener('click',()=>{s=restored;s.lastSeen=Date.now();save();close();show('hot');toast('存档已导入。');});}catch(err){toast('无法导入：'+err.message);}e.target.value='';});
  const joy=$('joy'),stick=$('stick');let pointer=null;
  function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.max(28,Math.hypot(dx,dy));input.x=dx/d;input.y=dy/d;stick.style.transform=`translate(${input.x*24}px,${input.y*24}px)`;}
  joy.addEventListener('pointerdown',e=>{pointer=e.pointerId;joy.setPointerCapture(pointer);joyMove(e);e.preventDefault();});joy.addEventListener('pointermove',e=>{if(pointer===e.pointerId)joyMove(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(name,e=>{if(pointer===e.pointerId){pointer=null;input.x=input.y=0;stick.style.transform='';}});
  window.addEventListener('keydown',e=>{if(view!=='battle'||['INPUT','TEXTAREA'].includes(document.activeElement.tagName)||$('dialog').open||(document.activeElement.tagName==='BUTTON'&&e.key===' '))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){keys.add(k);e.preventDefault();}const skillKey={q:'verify',e:'cool',' ':'pin',shift:'dash'}[k];if(skillKey&&!e.repeat){E.skill(s,skillKey);e.preventDefault();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();input.x=input.y=0;});
  document.addEventListener('visibilitychange',()=>{hidden=document.hidden;keys.clear();input.x=input.y=0;if(hidden)save();else{const seconds=(Date.now()-s.lastSeen)/1000;if(seconds>60){const r=E.offline(s,seconds);if(r.reward)toast('离线训练 +'+r.reward+' 暖光');}s.lastSeen=Date.now();lastFrame=performance.now();save();}});window.addEventListener('pagehide',save);
  const canvas=$('arena'),ctx=canvas.getContext('2d');
  function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
  function draw(now){const b=s.battle,w=420,h=540;ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,w,h);const map=b?C.maps[b.map]:C.maps[0],bg=images[map.art];if(bg&&!bg.src)bg.src='hotsearch-reaping/assets/'+map.art+'.png';ctx.fillStyle=map.color;ctx.fillRect(0,0,w,h);if(bg?.complete&&bg.naturalWidth){ctx.drawImage(bg,0,0,w,h);ctx.fillStyle='#fffbea85';ctx.fillRect(0,0,w,h);}else{for(let i=0;i<18;i++)ellipse((i*91)%420,(i*137)%540,18,8,'#ffffff18');}
    if(!b){sprite(ctx,0,170,220,76,85);return;}const ox=210-b.p.x,oy=275-b.p.y,screen=e=>({x:e.x+ox,y:e.y+oy});
    ctx.strokeStyle='#94a07833';ctx.lineWidth=2;ctx.strokeRect(ox,oy,900,900);
    for(const f of b.fields){const p=screen(f),ratio=f.life/f.total;ctx.globalAlpha=f.type==='warning'?.25+Math.sin(now*.018)*.13:Math.max(.1,ratio*.25);ellipse(p.x,p.y,f.r,f.r,f.type==='warning'?'#d97965':f.type==='cool'?'#81c2c4':f.type==='frost'?'#77b8c0':f.type==='pin'?'#dfb761':'#8bbdaf');ctx.globalAlpha=1;ctx.strokeStyle=f.type==='warning'?'#c27962':'#f9ffd2';ctx.lineWidth=f.type==='pin'?4:2;ctx.beginPath();ctx.arc(p.x,p.y,f.r*(f.type==='bell'||f.type==='pin'?1-ratio*.3:1),0,Math.PI*2);ctx.stroke();}
    for(const d of b.drops){const p=screen(d);ctx.fillStyle='#a8cba8';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.PI/4);ctx.fillRect(-3,-3,6,6);ctx.restore();}
    const sorted=[...b.enemies].sort((a,z)=>a.y-z.y);for(const e of sorted){const p=screen(e);if(p.x<-80||p.x>500||p.y<-80||p.y>620)continue;ellipse(p.x,p.y+e.r*.8,e.r*.8,e.r*.27,'#5e70411d');if(e.kind==='boss'){if(!sprite(ctx,3+b.map,p.x-48,p.y-53,96,99))ellipse(p.x,p.y,35,32,'#afa6c9');}else{const def=C.enemyKinds[e.kind];ctx.fillStyle=e.flash>0?'#fff9dc':def.color;ctx.beginPath();ctx.roundRect(p.x-e.r,p.y-e.r,e.r*2,e.r*1.7,e.r*.65);ctx.fill();ctx.beginPath();ctx.moveTo(p.x-e.r*.4,p.y+e.r*.5);ctx.lineTo(p.x-e.r*.3,p.y+e.r*1.05);ctx.lineTo(p.x+e.r*.05,p.y+e.r*.65);ctx.fill();ctx.fillStyle='#ffffffbc';ctx.font=(e.kind==='source'?11:9)+'px "Microsoft YaHei"';ctx.textAlign='center';ctx.fillText(e.kind==='source'?'◖':e.kind==='shield'?'▤':e.kind==='repeat'?'↻':e.kind==='rush'?'!':e.kind==='speaker'?'♪':'···',p.x,p.y+3);if(e.kind==='source'){ctx.strokeStyle='#e0ad84';ctx.beginPath();ctx.arc(p.x,p.y,e.r+5,0,Math.PI*2);ctx.stroke();}}
      if(e.shield>0){ctx.strokeStyle='#b8a377bb';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,e.r+5,0,Math.PI*2);ctx.stroke();}if(e.hp<e.max){ctx.fillStyle='#bca79c70';ctx.fillRect(p.x-e.r,p.y-e.r-7,e.r*2,3);ctx.fillStyle='#bd826d';ctx.fillRect(p.x-e.r,p.y-e.r-7,e.r*2*Math.max(0,e.hp/e.max),3);}}
    for(const q of b.bullets){const p=screen(q);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(q.vy,q.vx));ctx.fillStyle=q.enemy?'#d58d77':q.type==='petal'?'#dbb173':q.type==='context'?'#9ecac1':'#fff6ca';if(q.enemy)ellipse(0,0,q.r,q.r,ctx.fillStyle);else{ctx.shadowColor='#fff6cd';ctx.shadowBlur=s.settings.motion?7:0;ctx.fillRect(-7,-3,14,6);}ctx.restore();}
    ellipse(210,286,18,6,'#5b75472b');const bob=s.settings.motion?Math.sin(now*.011)*1.5:0;ctx.globalAlpha=b.p.inv>0&&Math.floor(now/90)%2?.65:1;if(!sprite(ctx,C.heroes.findIndex(x=>x.id===b.hero),187,244+bob,46,52))ellipse(210,272,12,16,'#6c997d');ctx.globalAlpha=1;
    if(s.weapons.includes('orbit')){const rank=s.levels.orbit,n=rank>=4?5:3,r=64*E.stats(s,b.hero).range;for(let j=0;j<n;j++){const a=b.time*2.5+j*Math.PI*2/n;ctx.fillStyle='#fff6c1';ctx.save();ctx.translate(210+Math.cos(a)*r,275+Math.sin(a)*r);ctx.rotate(a);ctx.fillRect(-4,-8,8,16);ctx.restore();}}
    fx=fx.filter(f=>now-f.at<f.life);for(const f of fx){const p=screen(f),t=(now-f.at)/f.life;ctx.globalAlpha=1-t;if(f.type==='hit'||f.type==='hurt'){ctx.font=(f.type==='hurt'?12:10)+'px sans-serif';ctx.textAlign='center';ctx.fillStyle=f.type==='hurt'?'#bf7161':'#928052';ctx.fillText(Math.ceil(f.amount),p.x,p.y-12-t*18);}else if(f.type==='beam'){const z=screen({x:f.x2,y:f.y2});ctx.strokeStyle='#fff2bd';ctx.lineWidth=5*(1-t);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(z.x,z.y);ctx.stroke();}else if(f.type==='kill'||f.type==='pin'||f.type==='bossdown'){const count=s.settings.motion?7:2;for(let j=0;j<count;j++){const a=j*Math.PI*2/count;ellipse(p.x+Math.cos(a)*t*23,p.y+Math.sin(a)*t*23,2*(1-t),2*(1-t),f.type==='kill'?'#e9dab6':'#f6cd82');}}ctx.globalAlpha=1;}
  }
  function pressureChart(){const c=$('pressure-chart').getContext('2d');c.clearRect(0,0,130,45);c.strokeStyle='#c8997b';c.lineWidth=2;c.beginPath();history.forEach((v,i)=>{const x=i/Math.max(1,history.length-1)*126+2,y=42-v/100*38;i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();}
  function frame(now){const delta=Math.min(.2,(now-lastFrame)/1000);lastFrame=now;if(!hidden){const keyX=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),keyY=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);E.run(s,delta,keyX||keyY?{x:keyX,y:keyY}:input);const b=s.battle;if(b!==lastBattle){lastBattle=b;eventCursor=0;fx=[];history=[];nextHistory=0;}if(b){for(const event of b.events){if(event.id<=eventCursor)continue;if(['hit','hurt','kill','beam','pin','bossdown'].includes(event.type))fx.push({...event,at:now,life:event.type==='beam'?180:600});if(['hurt','pin','victory','defeat','pickup'].includes(event.type))sound(event.type);if(event.type==='victory')toast('清屏完成 · '+event.kills+' 噪声 · 暖光 +'+event.earned);if(event.type==='achievement')toast('成就：'+event.name+' · +'+event.reward+'暖光');if(event.type==='hurt'&&s.settings.haptics)navigator.vibrate?.(15);eventCursor=Math.max(eventCursor,event.id);}fx=fx.slice(-100);if(b.time>=nextHistory){history.push(b.pressure);if(history.length>60)history.shift();nextHistory=b.time+1;pressureChart();}}
      if(view==='battle')draw(now);if(now-lastUi>200){updateUi();lastUi=now;}if(now-lastSave>2000){save();lastSave=now;}}
    requestAnimationFrame(frame);
  }
  if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)s.settings.motion=false;
  $('dialog').addEventListener('click',e=>{if(e.target===$('dialog'))close();});loadImages();loadFeed();updateUi();if(loadError)toast(loadError);requestAnimationFrame(frame);
})();
