(function(r,f){const a=f(typeof module==='object'&&module.exports?require('./content.js'):r.HotContent);if(typeof module==='object'&&module.exports)module.exports=a;else r.HotEngine=a;})(globalThis,C=>{
  'use strict';const DT=.05,W=900,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),clone=x=>JSON.parse(JSON.stringify(x)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  function hash(t){let h=2166136261;for(const c of String(t))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0||1;}
  function random(b){b.rng=(Math.imul(b.rng,1664525)+1013904223)>>>0;return b.rng/4294967296;}
  function emit(b,type,data={}){b.events.push({id:++b.eventId,type,...data});if(b.events.length>70)b.events.shift();}
  function create(){return {version:1,carry:0,coins:0,highest:0,hero:'bell',weapons:['paper','bell'],levels:Object.fromEntries(C.weapons.map(w=>[w.id,['paper','bell'].includes(w.id)?1:0])),upgrades:Object.fromEntries(C.upgrades.map(u=>[u.id,0])),auto:true,autoSkill:true,autoAdvance:true,policy:'source',speed:1,settings:{sound:false,haptics:false,motion:true},stats:{kills:0,wins:0,losses:0,burst:0,combo:0,sources:0,shields:0,verifies:0,cools:0,pins:0,studies:0,endless:0,offline:0},records:{},topicRecords:{},favorites:[],presets:[],badges:[],lastSeen:Date.now(),battle:null};}
  function stats(s,hero=s.hero){const u=s.upgrades,h=C.heroes.find(x=>x.id===hero)||C.heroes[0];return {attack:h.attack*(1+u.attack*.08),hp:h.hp+u.hp*18,speed:h.speed*(1+u.speed*.05),range:1+u.range*.06,haste:Math.max(.6,1-u.haste*.04),magnet:50+u.magnet*12,focus:1+u.focus*.1,armor:1-u.armor*.04,regen:u.regen*.2+(h.id==='leaf'?.35:0),cooling:u.cooling*.1,skill:1+u.skill*.12,income:1+u.income*.08};}
  function start(s,stage=0,topic=null,endless=false){if(!Number.isInteger(stage)||stage<0||stage>35||stage>Math.min(35,s.highest))return false;if(topic&&(!topic.title||typeof topic.title!=='string'))return false;
    const st=stats(s),map=topic?hash(topic.title)%6:Math.floor(stage/6);s.battle={version:1,stage,map,topic:topic?{title:topic.title.slice(0,100),rank:clamp(Number(topic.rank)||20,1,50),heat:Math.max(0,Number(topic.heat)||0)}:null,endless:!!endless,hero:s.hero,rng:hash(stage+':'+(topic?.title||'training')),phase:'playing',time:0,carry:0,p:{x:450,y:450,hp:st.hp,max:st.hp,inv:1,dx:1,dy:0},enemies:[],bullets:[],drops:[],fields:[],events:[],eventId:0,nextId:1,spawnCD:.2,weaponCD:Object.fromEntries(C.weapons.map(w=>[w.id,.4])),pressure:topic?Math.min(35,10+Math.log10(Math.max(1,topic.heat))*3):12,context:0,energy:0,kills:0,earned:0,combo:0,comboTime:0,peak:0,skillCD:0,coolCD:0,dashCD:0,dashTime:0,bossSpawned:false,bossKilled:false,bossesKilled:0,wave:1,wait:0,result:null};return true;
  }
  function spawn(s,kind='noise',position=null,boss=false){const b=s.battle;if(b.enemies.length>=170)return null;const def=boss?{hp:700+b.stage*42,speed:29,r:36,damage:20}:C.enemyKinds[kind];if(!def)return null;const a=random(b)*Math.PI*2,d=250+random(b)*80;const scale=1+b.stage*.045+(b.endless?Math.floor(b.time/90)*.15:0);
    const e={id:b.nextId++,kind:boss?'boss':kind,x:clamp(position?.x??b.p.x+Math.cos(a)*d,25,W-25),y:clamp(position?.y??b.p.y+Math.sin(a)*d,25,W-25),hp:def.hp*(boss?1:scale),max:def.hp*(boss?1:scale),r:def.r,speed:def.speed,damage:def.damage*(1+b.stage*.025),shield:kind==='shield'?35*scale:0,cd:kind==='repeat'?7:kind==='source'?4.5:boss?2.8:2,slow:0,silence:0,split:0,dead:false,flash:0,hitTimes:{}};b.enemies.push(e);emit(b,'spawn',{x:e.x,y:e.y,boss});return e;
  }
  function earn(s,value){const amount=Math.round(value*stats(s,s.battle.hero).income);s.coins+=amount;s.battle.earned+=amount;return amount;}
  function damage(s,e,value,breaks=false){if(!e||e.dead)return 0;const b=s.battle;let amount=value;if(e.shield>0){const shieldDamage=breaks?amount*4:amount*(b.hero==='ink'?.8:.35);e.shield=Math.max(0,e.shield-shieldDamage);amount*=breaks?.75:.15;}e.hp-=amount;e.flash=.1;emit(b,'hit',{x:e.x,y:e.y,amount,shield:e.shield>0});
    if(e.hp<=0){e.dead=true;b.kills++;s.stats.kills++;b.combo=b.comboTime>0?b.combo+1:1;b.comboTime=2.8;b.peak=Math.max(b.peak,b.combo);s.stats.combo=Math.max(s.stats.combo,b.combo);b.energy=clamp(b.energy+2,0,100);b.pressure=clamp(b.pressure-.3,0,100);if(e.kind==='source')s.stats.sources++;if(e.kind==='shield')s.stats.shields++;if(e.kind==='boss'){b.bossKilled=true;b.bossesKilled=(b.bossesKilled||0)+1;emit(b,'bossdown',{x:e.x,y:e.y});}
      b.drops.push({x:e.x,y:e.y,value:e.kind==='boss'?15:e.kind==='source'?4:1,life:18});if(b.drops.length>180){const dropped=b.drops.shift();earn(s,dropped.value);b.context=clamp(b.context+dropped.value*stats(s,b.hero).focus,0,100);}emit(b,'kill',{x:e.x,y:e.y,kind:e.kind,combo:b.combo});return 1;}return 0;
  }
  function aoe(s,x,y,r,value,breaks=false){let kills=0;for(const e of s.battle.enemies)if(!e.dead&&Math.hypot(e.x-x,e.y-y)<=r+e.r)kills+=damage(s,e,value,breaks);s.stats.burst=Math.max(s.stats.burst,kills);return kills;}
  function choose(s){const b=s.battle;let best=null,score=Infinity;for(const e of b.enemies){if(e.dead)continue;let v=distance(b.p,e);if(s.policy==='source'&&e.kind==='source')v*=.32;if(s.policy==='shield'&&e.kind==='shield')v*=.45;if(v<score){best=e;score=v;}}return best;}
  function bullet(b,x,y,a,damage,speed=290,life=1.4,extra={}){if(b.bullets.length>=300)return;b.bullets.push({id:b.nextId++,x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,damage,life,total:life,r:5,enemy:false,pierce:1,hit:[],...extra});}
  function skill(s,id){const b=s.battle;if(!b||b.phase!=='playing')return false;const st=stats(s,b.hero);
    if(id==='verify'){if(b.context<25||b.skillCD>0)return false;b.context-=25;b.skillCD=7;const r=150*st.range*(b.hero==='bell'?1.15:1);for(const e of b.enemies)if(distance(b.p,e)<r+e.r){e.shield=0;e.silence=5;damage(s,e,35*st.skill,true);}b.fields.push({type:'verify',x:b.p.x,y:b.p.y,r,life:.7,total:.7,cd:0});s.stats.verifies++;emit(b,'verify',{x:b.p.x,y:b.p.y,r});return true;}
    if(id==='cool'){if(b.coolCD>0)return false;b.coolCD=14;b.pressure=Math.max(0,b.pressure-22);const r=145*st.range;b.fields.push({type:'cool',x:b.p.x,y:b.p.y,r,life:5,total:5,cd:0});for(const e of b.enemies)if(distance(b.p,e)<r)e.slow=5;s.stats.cools++;emit(b,'cool',{x:b.p.x,y:b.p.y,r});return true;}
    if(id==='pin'){if(b.energy<100)return false;b.energy=0;aoe(s,b.p.x,b.p.y,320*st.range,160*st.skill,true);b.pressure=Math.max(0,b.pressure-15);b.fields.push({type:'pin',x:b.p.x,y:b.p.y,r:320*st.range,life:.9,total:.9,cd:0});s.stats.pins++;emit(b,'pin',{x:b.p.x,y:b.p.y});return true;}
    if(id==='dash'){if(b.dashCD>0)return false;b.dashCD=4;b.dashTime=.25;b.p.inv=.5;emit(b,'dash',{x:b.p.x,y:b.p.y});return true;}return false;
  }
  function fire(s,id){const b=s.battle,st=stats(s,b.hero),def=C.weapons.find(w=>w.id===id),rank=s.levels[id],factor=st.attack*(1+(rank-1)*.25),target=choose(s);if(!target)return;const a=Math.atan2(target.y-b.p.y,target.x-b.p.x),d=def.damage*factor;const advanced=rank>=5;
    if(id==='paper'){const n=advanced?3:rank>=3?2:1;for(let j=0;j<n;j++)bullet(b,b.p.x,b.p.y,a+(j-(n-1)/2)*.13,d,330,1.5,{pierce:advanced?3:1,type:'paper'});}
    if(id==='bell'){const r=(70+rank*5)*st.range;aoe(s,b.p.x,b.p.y,r,d);for(const q of b.bullets)if(q.enemy&&distance(b.p,q)<r)q.life=0;b.fields.push({type:'bell',x:b.p.x,y:b.p.y,r,life:.45,total:.45,cd:0});}
    if(id==='orbit'){const r=64*st.range,n=rank>=4?5:3;for(let j=0;j<n;j++){const ang=b.time*2.5+j*Math.PI*2/n;aoe(s,b.p.x+Math.cos(ang)*r,b.p.y+Math.sin(ang)*r,18,d);}}
    if(id==='context'){for(let j=-1;j<=1;j++)bullet(b,b.p.x,b.p.y,a+j*.24,d,280,1.25,{pierce:advanced?5:2,breaks:true,type:'context'});}
    if(id==='beam'){const length=260*st.range;for(const e of b.enemies){const dx=e.x-b.p.x,dy=e.y-b.p.y,t=dx*Math.cos(a)+dy*Math.sin(a),side=Math.abs(dx*Math.sin(a)-dy*Math.cos(a));if(t>=0&&t<=length&&side<12+e.r)damage(s,e,d,advanced);}emit(b,'beam',{x:b.p.x,y:b.p.y,x2:b.p.x+Math.cos(a)*length,y2:b.p.y+Math.sin(a)*length});}
    if(id==='frost')b.fields.push({type:'frost',x:target.x,y:target.y,r:(60+rank*4)*st.range,life:3,total:3,cd:0,damage:d});
    if(id==='return')bullet(b,b.p.x,b.p.y,a,d,250,2,{pierce:20,type:'return',returning:false,originX:b.p.x,originY:b.p.y});
    if(id==='petal')for(let j=0;j<(advanced?14:8);j++)bullet(b,b.p.x,b.p.y,j*Math.PI*2/(advanced?14:8)+b.time,d,240,1.6,{pierce:advanced?3:1,type:'petal'});
  }
  function badges(s){for(const a of C.achievements){const v=a.key==='highest'?s.highest:s.stats[a.key];if(v>=a.goal&&!s.badges.includes(a.id)){s.badges.push(a.id);s.coins+=a.reward;if(s.battle)emit(s.battle,'achievement',{name:a.name,reward:a.reward});}}}
  function finish(s,won){const b=s.battle;if(b.phase!=='playing')return;b.phase=won?'won':'lost';b.wait=4;s.stats[won?'wins':'losses']++;const reward=won?earn(s,60+b.stage*13):0;let first=false;
    if(won){const record={time:b.time,reward:b.earned,kills:b.kills,peak:b.peak,clarity:b.p.hp/b.p.max,stars:b.p.hp/b.p.max>.7?3:b.p.hp/b.p.max>.35?2:1};if(b.topic){const old=s.topicRecords[b.topic.title];if(!old||record.kills>old.kills)s.topicRecords[b.topic.title]={...record,title:b.topic.title};const names=Object.keys(s.topicRecords);if(names.length>500)delete s.topicRecords[names[0]];}
      else if(!b.endless){first=b.stage>=s.highest;if(first)s.highest=b.stage+1;const old=s.records[b.stage],rate=Math.max(record.reward/record.time,old?.bestRate||0,old?old.reward/old.time:0);record.bestRate=rate;if(!old||record.stars>old.stars||record.time<old.time)s.records[b.stage]=record;else old.bestRate=rate;}}
    b.result={won,reward,earned:b.earned,kills:b.kills,time:b.time,first,peak:b.peak};badges(s);emit(b,won?'victory':'defeat',b.result);
  }
  function autoMove(s){const b=s.battle,p=b.p;let dx=Math.cos(b.time*.63)*.12,dy=Math.sin(b.time*.43)*.12,nearest=Infinity;for(const e of b.enemies){if(e.dead)continue;const d=distance(p,e);nearest=Math.min(nearest,d);if(d<115){const force=(115-d)/Math.max(20,d);dx+=(p.x-e.x)/Math.max(1,d)*force;dy+=(p.y-e.y)/Math.max(1,d)*force;}}
    for(const f of b.fields)if(f.type==='warning'&&distance(p,f)<f.r+50){dx+=(p.x-f.x)/Math.max(20,distance(p,f))*1.8;dy+=(p.y-f.y)/Math.max(20,distance(p,f))*1.8;}
    for(const q of b.bullets)if(q.enemy&&q.life>0){const d=distance(p,q);if(d<105){const toward=((p.x-q.x)*q.vx+(p.y-q.y)*q.vy)>0;if(toward){const f=(105-d)/Math.max(18,d);dx+=(p.x-q.x)/Math.max(1,d)*f*1.6;dy+=(p.y-q.y)/Math.max(1,d)*f*1.6;}}}
    if(nearest>65&&b.drops.length){let best=b.drops[0];for(const d of b.drops)if(distance(p,d)<distance(p,best))best=d;const len=Math.max(1,distance(p,best));dx+=(best.x-p.x)/len*.7;dy+=(best.y-p.y)/len*.7;}
    else if(nearest>115){const target=choose(s);if(target){const len=Math.max(1,distance(p,target));dx+=(target.x-p.x)/len*.45;dy+=(target.y-p.y)/len*.45;}}
    if(p.x<110)dx+=1;if(p.x>790)dx-=1;if(p.y<110)dy+=1;if(p.y>790)dy-=1;const length=Math.hypot(dx,dy);return length?{x:dx/length,y:dy/length}:{x:0,y:0};
  }
  function tick(s,input={}){const b=s.battle;if(!b)return;if(b.phase==='paused')return;if(b.phase!=='playing'){if(s.autoAdvance&&!b.endless){b.wait-=DT;if(b.wait<=0){const next=b.phase==='won'?Math.min(35,s.highest):Math.max(0,s.highest-1);start(s,next,b.topic);}}return;}
    const st=stats(s,b.hero),p=b.p;b.time+=DT;b.wave=1+Math.floor(b.time/30);if(b.endless)s.stats.endless=Math.max(s.stats.endless,b.wave);b.comboTime=Math.max(0,b.comboTime-DT);if(!b.comboTime)b.combo=0;p.inv=Math.max(0,p.inv-DT);for(const k of ['skillCD','coolCD','dashCD','dashTime'])b[k]=Math.max(0,b[k]-DT);
    if(st.hp!==p.max){p.hp=clamp(p.hp+st.hp-p.max,1,st.hp);p.max=st.hp;}p.hp=Math.min(p.max,p.hp+st.regen*DT);
    const manual=Math.hypot(input.x||0,input.y||0)>.05;const v=manual?input:s.auto?autoMove(s):{x:0,y:0};const len=Math.max(1,Math.hypot(v.x||0,v.y||0));if(v.x||v.y){p.dx=(v.x||0)/len;p.dy=(v.y||0)/len;}const speed=st.speed*(b.dashTime>0?4:1);p.x=clamp(p.x+(v.x||0)/len*speed*DT,20,880);p.y=clamp(p.y+(v.y||0)/len*speed*DT,20,880);
    const sources=b.enemies.filter(e=>!e.dead&&e.kind==='source').length;b.pressure=clamp(b.pressure+(.05+(b.map===3?.15:0)+sources*.07-st.cooling)*DT,0,100);
    const duration=90;if(b.time<duration||b.endless){b.spawnCD-=DT;if(b.spawnCD<=0){const waveScale=1+Math.min(4,Math.floor(b.time/30))*.35,amount=2+(b.stage>=12?1:0);for(let j=0;j<amount;j++){const roll=random(b),pool=b.map===0?['noise','repeat','rush']:b.map===1?['noise','source','speaker']:b.map===2?['noise','shield','rush']:['noise','repeat','source','shield','rush','speaker'];spawn(s,pool[Math.floor(roll*pool.length)]);}b.spawnCD=.75/(waveScale*(1+b.pressure/100)*(1+b.stage*.013));}
      if(b.time>=(b.nextSurge||12)){const angle=random(b)*Math.PI*2,amount=16+Math.min(24,Math.floor(b.stage*.7));for(let j=0;j<amount;j++){const a=angle+(j%3)*Math.PI*2/3+(random(b)-.5)*.3,d=210+random(b)*50;spawn(s,j%5===0?'repeat':'noise',{x:clamp(p.x+Math.cos(a)*d,25,875),y:clamp(p.y+Math.sin(a)*d,25,875)});}b.pressure=clamp(b.pressure+6,0,100);b.nextSurge=b.time+12;emit(b,'surge',{amount});}}
    const bossStage=b.stage%6===5||b.topic||b.endless;if(bossStage&&!b.bossSpawned&&b.time>=(b.nextBossTime||60)){spawn(s,'boss',null,true);b.bossSpawned=true;emit(b,'boss',{name:C.maps[b.map].boss});}
    for(const e of b.enemies){if(e.dead)continue;e.flash=Math.max(0,e.flash-DT);e.slow=Math.max(0,e.slow-DT);e.silence=Math.max(0,e.silence-DT);e.cd-=DT;const d=distance(p,e),move=e.kind==='source'&&d<180?0:e.kind==='speaker'&&d<180?-.25:1;const slow=e.slow>0?.4:1;if(d>1){e.x=clamp(e.x+(p.x-e.x)/d*e.speed*slow*move*DT,10,890);e.y=clamp(e.y+(p.y-e.y)/d*e.speed*slow*move*DT,10,890);}
      if(d<e.r+13&&p.inv<=0){p.hp=Math.max(0,p.hp-e.damage*st.armor);p.inv=.5;emit(b,'hurt',{x:p.x,y:p.y,amount:e.damage*st.armor});}
      if(e.cd<=0){if(e.kind==='repeat'&&e.split<1&&!e.silence){e.split++;for(let j=0;j<2;j++)spawn(s,'noise',{x:e.x+(j?16:-16),y:e.y});emit(b,'repeat',{x:e.x,y:e.y});e.cd=8;}
        else if(e.kind==='source'&&!e.silence){for(let j=0;j<3;j++)spawn(s,'noise',{x:e.x+(j-1)*16,y:e.y});b.pressure=clamp(b.pressure+1.8,0,100);e.cd=4.5;}
        else if(e.kind==='speaker'&&!e.silence){bullet(b,e.x,e.y,Math.atan2(p.y-e.y,p.x-e.x),8*(1+b.stage*.025),105,4,{enemy:true,type:'noise',r:6});e.cd=2.8;}
        else if(e.kind==='boss'){const count=8+b.map,angle=Math.atan2(p.y-e.y,p.x-e.x)+(b.map===5?b.time*.8:0);for(let j=0;j<count;j++)bullet(b,e.x,e.y,angle+j*Math.PI*2/count,12*(1+b.stage*.025),100+b.map*8,4,{enemy:true,type:'boss',r:7});
          if(b.map===0)for(let j=0;j<2;j++)spawn(s,'repeat',{x:e.x+(j?30:-30),y:e.y});
          if(b.map===1&&sources<5)spawn(s,'source',{x:e.x+30,y:e.y});
          if(b.map===2)e.shield=Math.min(100,e.shield+45);
          if(b.map===3)b.pressure=clamp(b.pressure+12,0,100);
          if(b.map===4)spawn(s,'speaker',{x:e.x-30,y:e.y});
          if(e.hp<e.max*.65||b.map===3||b.map===5)b.fields.push({type:'warning',x:p.x,y:p.y,r:65,life:1.1,total:1.1,cd:0,damage:17*(1+b.stage*.025)});e.cd=3.1;}
        else e.cd=1;}
    }
    if(s.autoSkill){if(b.context>=25&&(b.enemies.some(e=>e.shield>0&&distance(p,e)<160)||b.enemies.filter(e=>!e.dead&&distance(p,e)<140).length>8))skill(s,'verify');if(b.pressure>42||p.hp<p.max*.5)skill(s,'cool');if(b.energy>=100&&(b.enemies.filter(e=>!e.dead&&distance(p,e)<320).length>12||b.enemies.some(e=>e.kind==='boss'&&distance(p,e)<280)))skill(s,'pin');}
    for(const id of s.weapons){b.weaponCD[id]-=DT;if(b.weaponCD[id]<=0){fire(s,id);const def=C.weapons.find(w=>w.id===id);b.weaponCD[id]+=def.cd*st.haste;}}
    const grid=new Map();for(const e of b.enemies){if(e.dead)continue;const key=Math.floor(e.x/60)+','+Math.floor(e.y/60);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(e);}
    for(const q of b.bullets){q.life-=DT;if(q.type==='return'&&q.life<q.total/2){if(!q.returning){q.returning=true;q.hit=[];}const d=Math.max(1,Math.hypot(p.x-q.x,p.y-q.y));q.vx=(p.x-q.x)/d*270;q.vy=(p.y-q.y)/d*270;}q.x+=q.vx*DT;q.y+=q.vy*DT;
      if(q.enemy){if(distance(p,q)<q.r+13&&p.inv<=0){p.hp=Math.max(0,p.hp-q.damage*st.armor);p.inv=.35;q.life=0;emit(b,'hurt',{x:p.x,y:p.y,amount:q.damage*st.armor});}}
      else{const gx=Math.floor(q.x/60),gy=Math.floor(q.y/60);for(let x=gx-1;x<=gx+1;x++)for(let y=gy-1;y<=gy+1;y++)for(const e of grid.get(x+','+y)||[]){if(q.life<=0||e.dead||q.hit.includes(e.id))continue;if(distance(q,e)<q.r+e.r){damage(s,e,q.damage,q.breaks);q.hit.push(e.id);q.pierce--;if(q.pierce<=0)q.life=0;}}}
    }
    b.bullets=b.bullets.filter(q=>q.life>0&&q.x>-40&&q.y>-40&&q.x<940&&q.y<940);
    for(const f of b.fields){f.life-=DT;f.cd-=DT;if(f.type==='frost'&&f.cd<=0){for(const e of b.enemies)if(!e.dead&&distance(f,e)<f.r+e.r){e.slow=.6;damage(s,e,f.damage);}f.cd=.5;}if(f.type==='cool')for(const e of b.enemies)if(!e.dead&&distance(f,e)<f.r)e.slow=.6;if(f.type==='warning'&&f.life<=0&&distance(p,f)<f.r&&p.inv<=0){p.hp=Math.max(0,p.hp-f.damage*st.armor);p.inv=.5;emit(b,'hurt',{x:p.x,y:p.y,amount:f.damage*st.armor});}}
    b.fields=b.fields.filter(f=>f.life>0).slice(-40);
    for(const d of b.drops){d.life-=DT;const len=distance(p,d);if(len<st.magnet){const speed=240;d.x+=(p.x-d.x)/Math.max(1,len)*speed*DT;d.y+=(p.y-d.y)/Math.max(1,len)*speed*DT;}if(len<20){earn(s,d.value);b.context=clamp(b.context+d.value*3*st.focus,0,100);d.life=0;emit(b,'pickup',{x:d.x,y:d.y,value:d.value});}}
    b.drops=b.drops.filter(d=>d.life>0);b.enemies=b.enemies.filter(e=>!e.dead);
    b.badgeCD=(b.badgeCD||0)-DT;if(b.badgeCD<=0){badges(s);b.badgeCD=1;}
    if(p.hp<=0)finish(s,false);else if(!b.endless&&b.time>=duration&&b.enemies.length===0&&(!bossStage||b.bossKilled))finish(s,true);
    if(b.endless&&b.bossKilled){b.bossKilled=false;b.bossSpawned=false;b.nextBossTime=b.time+90;}
  }
  function run(s,seconds,input={}){if(!s.battle||s.battle.phase==='paused'||!Number.isFinite(seconds)||seconds<0)return;let total=(s.carry||0)+seconds*s.speed;const count=Math.floor((total+1e-8)/DT);s.carry=Math.max(0,total-count*DT);for(let i=0;i<count;i++)tick(s,input);}
  function cost(s,id,weapon=false){const d=(weapon?C.weapons:C.upgrades).find(x=>x.id===id);return d?Math.round(d.cost*Math.pow(weapon?2:1.6,weapon?s.levels[id]:s.upgrades[id])):Infinity;}
  function upgrade(s,id,weapon=false){const d=(weapon?C.weapons:C.upgrades).find(x=>x.id===id),rank=weapon?s.levels[id]:s.upgrades[id];if(!d||s.highest<d.unlock||rank>=(weapon?5:d.max)||s.coins<cost(s,id,weapon))return false;s.coins-=cost(s,id,weapon);if(weapon)s.levels[id]++;else s.upgrades[id]++;s.stats.studies++;badges(s);return true;}
  function equip(s,id){if(!s.levels[id])return false;if(s.weapons.includes(id)){if(s.weapons.length===1)return false;s.weapons=s.weapons.filter(x=>x!==id);}else{if(s.weapons.length>=4)return false;s.weapons.push(id);}return true;}
  function offline(s,seconds){const time=Math.min(28800,Math.max(0,seconds));let rate=0;for(const record of Object.values(s.records))if(record.time>0)rate=Math.max(rate,(record.bestRate??record.reward/record.time)*.35);const reward=Math.floor(rate*time);s.coins+=reward;s.stats.offline+=time;return {time,rate,reward,capped:seconds>28800};}
  function restore(raw){if(typeof raw==='string'){if(raw.length>1500000)throw Error('存档过大');raw=JSON.parse(raw);}if(!raw||raw.version!==1)throw Error('存档版本不支持');const s=clone(raw),n=(v,a,z,int=false)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<a||v>z||int&&!Number.isInteger(v))throw Error('存档数值不合法');};n(s.coins,0,1e12);n(s.highest,0,36,true);n(s.lastSeen,0,1e15);if(!C.heroes.some(h=>h.id===s.hero)||!C.policies.some(p=>p.id===s.policy))throw Error('角色或策略不合法');if(![1,2].includes(s.speed))throw Error('倍率不合法');for(const k of ['auto','autoSkill','autoAdvance'])if(typeof s[k]!=='boolean')throw Error('自动设置不合法');for(const k of ['sound','haptics','motion'])if(typeof s.settings?.[k]!=='boolean')throw Error('设置不合法');for(const d of C.upgrades)n(s.upgrades?.[d.id],0,d.max,true);for(const d of C.weapons)n(s.levels?.[d.id],0,5,true);
    if(!Array.isArray(s.weapons)||s.weapons.length<1||s.weapons.length>4||new Set(s.weapons).size!==s.weapons.length||s.weapons.some(id=>!C.weapons.some(w=>w.id===id)||!s.levels[id]))throw Error('武器不合法');for(const key of Object.keys(create().stats))n(s.stats?.[key],0,1e12);if(!Array.isArray(s.badges)||s.badges.some(id=>!C.achievements.some(a=>a.id===id))||!Array.isArray(s.favorites)||s.favorites.length>100||s.favorites.some(x=>typeof x!=='string'||x.length>100)||!Array.isArray(s.presets)||s.presets.length>3)throw Error('收藏不合法');
    for(const p of s.presets)if(typeof p.name!=='string'||p.name.length>20||!C.heroes.some(h=>h.id===p.hero)||!C.policies.some(x=>x.id===p.policy)||!Array.isArray(p.weapons)||p.weapons.length<1||p.weapons.length>4||p.weapons.some(id=>!s.levels[id]))throw Error('预设不合法');
    if(!s.records||typeof s.records!=='object'||Array.isArray(s.records)||!s.topicRecords||typeof s.topicRecords!=='object'||Array.isArray(s.topicRecords)||Object.keys(s.topicRecords).length>500)throw Error('战报结构不合法');for(const r of Object.values(s.records)){n(r.time,.05,1e9);n(r.reward,0,1e9);n(r.stars,1,3,true);if(r.bestRate!==undefined)n(r.bestRate,0,1e9);}for(const r of Object.values(s.topicRecords||{})){if(typeof r.title!=='string'||r.title.length>100)throw Error('战报不合法');n(r.kills,0,1e9);n(r.time,.05,1e9);n(r.peak,0,1e9);n(r.clarity,0,1);}
    if(s.battle){const b=s.battle;n(b.stage,0,35,true);n(b.map,0,5,true);n(b.rng,0,4294967295,true);n(b.time,0,1e9);n(b.carry,0,DT+.00001);n(b.p.x,0,W);n(b.p.y,0,W);n(b.p.max,1,1e5);n(b.p.hp,0,b.p.max);n(b.p.inv,0,10);n(b.p.dx,-1,1);n(b.p.dy,-1,1);for(const key of ['endless','bossSpawned','bossKilled'])if(typeof b[key]!=='boolean')throw Error('首领状态不合法');if(b.nextBossTime!==undefined)n(b.nextBossTime,0,1e9);if(!['playing','paused','won','lost'].includes(b.phase)||!C.heroes.some(h=>h.id===b.hero))throw Error('交战状态不合法');for(const k of ['pressure','context','energy'])n(b[k],0,100);for(const key of ['skillCD','coolCD','dashCD','dashTime','spawnCD','comboTime','wait'])n(b[key],-1,1e5);for(const key of ['kills','earned','combo','peak','eventId','nextId','wave'])n(b[key],0,1e12);if(b.topic&&(typeof b.topic.title!=='string'||b.topic.title.length>100))throw Error('话题不合法');
      for(const [key,max]of [['enemies',170],['bullets',300],['drops',180],['fields',40],['events',70]])if(!Array.isArray(b[key])||b[key].length>max)throw Error('实体数量不合法');
      for(const e of b.enemies){n(e.id,1,1e12,true);n(e.split,0,1,true);if(typeof e.dead!=='boolean')throw Error('敌人状态不合法');if(e.kind!=='boss'&&!C.enemyKinds[e.kind])throw Error('敌种不合法');for(const k of ['x','y','hp','max','r','speed','damage','shield','cd','slow','silence','flash'])n(e[k],k==='cd'?-1:0,k==='x'||k==='y'?W:1e6);if(!e.hitTimes||!Array.isArray(e.hitTimes)&&typeof e.hitTimes!=='object')throw Error('命中记录不合法');}
      for(const q of b.bullets){n(q.id,1,1e12,true);n(q.total,.01,100);if(typeof q.enemy!=='boolean'||!['paper','context','return','petal','noise','boss'].includes(q.type))throw Error('弹丸类型不合法');for(const k of ['x','y','vx','vy','damage','life','r','pierce'])n(q[k],['x','y','vx','vy'].includes(k)?-1e5:0,1e5);if(!Array.isArray(q.hit)||q.hit.length>200)throw Error('弹丸不合法');}
      for(const d of b.drops)for(const k of ['x','y','value','life'])n(d[k],0,k==='x'||k==='y'?W:1e6);for(const f of b.fields){if(!['verify','cool','pin','bell','frost','warning'].includes(f.type))throw Error('区域类型不合法');for(const k of ['x','y','r','life','total','cd'])n(f[k],k==='cd'?-1:0,1e5);if(['frost','warning'].includes(f.type))n(f.damage,0,1e6);}for(const w of C.weapons)n(b.weaponCD[w.id],-1,1e5);
    }s.carry=s.carry??s.battle?.carry??0;n(s.carry,0,DT+.00001);return s;
  }
  return {DT,W,create,start,stats,spawn,damage,aoe,choose,skill,tick,run,cost,upgrade,equip,offline,restore,badges};
});
