'use strict';const assert=require('node:assert/strict'),C=require('./content.js'),E=require('./engine.js');const checks=[];
function test(name,fn){fn();checks.push(name);}
test('repeat enemy really creates new entities',()=>{const s=E.create();E.start(s);s.battle.spawnCD=100;const e=E.spawn(s,'repeat',{x:200,y:200});e.cd=0;E.tick(s);assert.equal(s.battle.enemies.length,3);});
test('source continues spawning until silenced',()=>{const s=E.create();E.start(s);s.battle.spawnCD=100;const e=E.spawn(s,'source',{x:200,y:200});e.cd=0;E.tick(s);assert.equal(s.battle.enemies.length,4);e.cd=0;e.silence=4;E.tick(s);assert.equal(s.battle.enemies.length,4);});
test('verify spends collected context and breaks the shield',()=>{const s=E.create();E.start(s);const e=E.spawn(s,'shield',{x:500,y:450});s.battle.context=30;assert(E.skill(s,'verify'));assert.equal(e.shield,0);assert.equal(s.battle.context,5);assert(!E.skill(s,'verify'));});
test('cool lowers pressure and provides persistent slowdown',()=>{const s=E.create();E.start(s);s.battle.pressure=70;assert(E.skill(s,'cool'));assert.equal(s.battle.pressure,48);assert(s.battle.fields.some(f=>f.type==='cool'));});
test('manual movement overrides automatic movement without disabling it',()=>{const s=E.create();E.start(s);const x=s.battle.p.x;E.run(s,.5,{x:1,y:0});assert(s.battle.p.x>x+50);assert(s.auto);});
test('pause cannot earn time or currency',()=>{const s=E.create();E.start(s);s.battle.phase='paused';const before=s.coins;E.run(s,30);assert.equal(s.battle.time,0);assert.equal(s.coins,before);});
test('offline training requires a real cleared stage and never unlocks one',()=>{const s=E.create();assert.equal(E.offline(s,3600).reward,0);s.records[0]={time:100,reward:100,stars:1};const r=E.offline(s,90000);assert.equal(r.time,28800);assert.equal(r.reward,10080);assert.equal(s.highest,0);});
test('ongoing combat survives roundtrip and gives identical future',()=>{const s=E.create();E.start(s);E.run(s,20);const b=E.restore(JSON.stringify(s));E.run(s,20);E.run(b,20);assert.deepEqual(s,b);});
test('fractional frame time survives automatic stage transitions',()=>{const a=E.create();E.start(a);const b=E.restore(JSON.stringify(a));E.run(a,210.013);for(let i=0;i<3000;i++)E.run(b,.07);E.run(b,.013);assert.equal(a.highest,b.highest);assert.deepEqual(a.battle,b.battle);assert.equal(a.coins,b.coins);assert(Math.abs(a.carry-b.carry)<1e-7);});
test('invalid save version, numbers and equipment are rejected',()=>{const s=E.create();assert.throws(()=>E.restore({...s,version:10}));assert.throws(()=>E.restore({...s,coins:NaN}));assert.throws(()=>E.restore({...s,weapons:['unknown']}));});
test('fixed upgrades and four-slot equipment are enforced',()=>{const s=E.create();s.coins=10000;assert(!E.upgrade(s,'beam',true));assert(E.upgrade(s,'paper',true));assert.equal(s.levels.paper,2);assert(!E.equip(s,'beam'));});
test('changing priority changes the chosen target',()=>{const s=E.create();E.start(s);const near=E.spawn(s,'noise',{x:550,y:450}),source=E.spawn(s,'source',{x:650,y:450});s.policy='near';assert.equal(E.choose(s),near);s.policy='source';assert.equal(E.choose(s),source);});
test('six bosses have different opinion mechanics',()=>{for(let map=0;map<6;map++){const s=E.create();E.start(s);s.autoSkill=false;s.battle.map=map;s.battle.spawnCD=100;const boss=E.spawn(s,'boss',{x:600,y:450},true);boss.cd=0;E.tick(s);if(map===0)assert(s.battle.enemies.some(e=>e.kind==='repeat'));if(map===1)assert(s.battle.enemies.some(e=>e.kind==='source'));if(map===2)assert(boss.shield>0);if(map===3)assert(s.battle.pressure>23);if(map===4)assert(s.battle.enemies.some(e=>e.kind==='speaker'));if(map===5)assert(s.battle.fields.some(f=>f.type==='warning'));}});
test('malformed nested combat data is rejected before import',()=>{const s=E.create();E.start(s);const a=JSON.parse(JSON.stringify(s));delete a.battle.p.dx;assert.throws(()=>E.restore(a));const b=JSON.parse(JSON.stringify(s));b.records=null;assert.throws(()=>E.restore(b));});
test('periodic opinion surges create a real crowd without exceeding budgets',()=>{const s=E.create();E.start(s);s.battle.time=11.99;s.battle.spawnCD=100;E.tick(s);assert.equal(s.battle.enemies.length,16);assert(s.battle.events.some(e=>e.type==='surge'));E.run(s,100);assert(s.battle.enemies.length<=170);assert(s.battle.bullets.length<=300);});
const play=E.create();E.start(play);E.run(play,120);E.restore(JSON.stringify(play));console.log(JSON.stringify({passed:checks.length,checks,first120s:{stage:play.battle.stage,phase:play.battle.phase,kills:play.stats.kills,wins:play.stats.wins,losses:play.stats.losses,coins:play.coins,entities:play.battle.enemies.length,hp:play.battle.p.hp}},null,2));
