'use strict';
const assert=require('node:assert/strict');
const C=require('./content.js'),E=require('./engine.js');
const report=[];
function test(name,fn){fn();report.push(name);}
function battle(stage,policy='balanced',level=0){const s=E.create();s.highest=48;s.stage=stage;for(const id of ['attack','vitality'])s.research[id]=level;E.setPolicy(s,policy);E.launch(s,stage);return s;}
function settle(s,max=240){for(let i=0;i<max/E.DT&&!s.battle.result;i++)E.run(s,E.DT);return {result:s.battle.result,time:s.battle.elapsed,hp:s.battle.heroHP,captures:s.battle.captures,destroyed:s.battle.destroyed};}
test('cut relay removes downstream supply for both owners',()=>{const s=E.create();s.battle.nodes[3].owner='ally';E.power(s);assert.equal(s.battle.nodes[3].power,1);assert.equal(s.battle.nodes[4].power,1);s.battle.nodes[2].owner='dead';s.battle.nodes[2].hp=0;E.power(s);assert.equal(s.battle.nodes[3].power,0);assert.equal(s.battle.nodes[4].power,0);});
test('captured source feeds only reachable allied consumers',()=>{const s=E.create();s.battle.nodes[1].owner='ally';s.battle.nodes[3].owner='ally';E.power(s);assert.equal(s.battle.nodes[3].power,1);assert.equal(s.battle.nodes[4].power,0);});
test('finite shared source output causes an observable bottleneck',()=>{const s=battle(1);s.battle.nodes[2].owner='dead';s.battle.nodes[2].hp=0;E.power(s);assert.equal(s.battle.nodes[6].power,0);assert.equal(s.battle.nodes[5].power,1);assert.equal(s.battle.nodes[7].power,1);s.battle.nodes[2].owner='enemy';s.battle.nodes[2].hp=1;s.battle.edges.push([1,6]);E.power(s);assert(s.battle.nodes[5].power<1);});
test('capacity is paid on capture and insufficient capacity destroys instead',()=>{const s=E.create();for(const n of s.battle.nodes)n.cooldown=500;for(const id of [3,1,4]){s.battle.nodes[id].hp=.01;assert(E.select(s,id,'capture'));s.battle.attackCD=0;E.run(s,.25);}assert.equal(s.battle.nodes[3].owner,'ally');assert.equal(s.battle.nodes[1].owner,'ally');assert.equal(E.used(s),3);assert.equal(s.battle.nodes[4].owner,'dead');assert(s.journal.includes('容量不足，已改为拆解'));});
test('ownership reverses actual gun target rather than adding a policy multiplier',()=>{const enemy=E.create(),ally=E.create();for(const s of [enemy,ally]){s.battle.attackCD=500;for(const n of s.battle.nodes)n.cooldown=500;s.battle.nodes[3].cooldown=0;}ally.battle.nodes[3].owner='ally';const before=ally.battle.nodes[4].hp;E.run(enemy,.25);E.run(ally,.25);assert(enemy.battle.heroHP<enemy.battle.heroMax);assert.equal(ally.battle.heroHP,ally.battle.heroMax);assert(ally.battle.nodes[4].hp<before);});
test('save restore preserves ongoing combat and future outcomes',()=>{const a=battle(5,'commandeer',3);E.run(a,11.5);const b=E.restore(JSON.stringify(a));E.run(a,310);E.run(b,310);assert.deepEqual(a,b);});
test('chunked away time equals continuous elapsed time',()=>{const a=battle(3,'shelter',2),b=E.restore(JSON.stringify(a));E.run(a,480);for(let i=0;i<1920;i++)E.run(b,.25);assert.deepEqual(a,b);});
test('pause prevents elapsed time, rewards and attacks',()=>{const s=E.create();s.playing=false;const b=JSON.stringify(s);E.run(s,7200);assert.equal(JSON.stringify(s),b);});
test('invalid save cannot become a valid imported state',()=>{const s=E.create();assert.throws(()=>E.restore({...s,version:99}));assert.throws(()=>E.restore({...s,credits:Infinity}));const raw=E.snapshot(s);raw.battle.edges.push([0,3]);assert.throws(()=>E.restore(raw));});
test('progression only unlocks accessible stages and research',()=>{const s=E.create();assert.equal(E.launch(s,8),false);assert.equal(E.launch(s,0,'trial',0),false);s.credits=10000;assert.equal(E.upgrade(s,'capacity'),false);assert(E.upgrade(s,'attack'));assert.equal(s.stats.studies,1);});
test('content includes planned campaign, systems and narrative',()=>{assert.equal(C.stages.length,48);assert.equal(C.trials.length,6);assert.equal(C.research.length,12);assert.equal(C.modules.length,8);assert.equal(C.heroes.length,3);assert.equal(C.achievements.length,16);assert.equal(C.chapters.length,12);for(const layout of C.layouts){assert.equal(layout.nodes[0][0],'core');for(const [a,b]of layout.edges)assert(layout.nodes[a]&&layout.nodes[b]);}});
const comparisons=C.layouts.map((l,i)=>({body:l.name,policies:Object.fromEntries(C.policies.map(p=>[p.id,settle(battle(i,p.id,2))]))}));
console.log(JSON.stringify({passed:report.length,checks:report,comparisons},null,2));
