(()=>{'use strict';
const D=VELOCITY_DATA,C=VelocityCore,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=localStorage}catch{storage={getItem(){throw Error('storage unavailable')},setItem(){throw Error('storage unavailable')},removeItem(){throw Error('storage unavailable')}}}const store=new VelocitySave.Store(storage,()=>{$('storage-warning').hidden=false}),profile=store.profile,settings=profile.settings,renderer=new VelocityRenderer($('arena'),settings);
let selectedMap=D.tracks.some(t=>t.id===profile.selection.map)?profile.selection.map:null,mapFilter=-1,game=null,car=profile.selection.car,menu='',signature='',lastSave=0,noticeUntil=0,last=performance.now(),hudAt=0;
const keys=new Set(),held=new Map(),joy={id:null,x:0,y:0},colors={draft:'#c1ff35',rail:'#47e6f2',drift:'#aa55ff',survive:'#ff568d'};
const lessons=[['01 / 转向','左右拖动摇杆，或按 A / D。前进由自动油门负责，转向以车身为基准。'],['02 / 漂移蓄电','保持转向并按住「漂移」或 SHIFT，漂移距离积累超过 35。电量增加，热量也会上升。'],['03 / 追入尾流','松开漂移，靠近领航员的后方车道。青色连接蓄满变绿，需要跟随约 1 秒。'],['04 / 劫走车速','连接变绿后点「换速」或 J。只交换双方当前车速，车辆位置保持连续。'],['05 / 铺下快线','点「铺轨」或 K，在前方留下共享加速轨，然后驶入它。对手也能使用。'],['06 / 氮气喷射','点大号「氮气喷射」或 SPACE。真实加速，消耗电量，增加热量。']];
class Audio{
 unlock(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.engine=this.ctx.createOscillator();this.engine.type='sawtooth';this.eg=this.ctx.createGain();this.eg.gain.value=0;this.filter=this.ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=500;this.engine.connect(this.filter).connect(this.eg).connect(this.ctx.destination);this.engine.start();this.next=0;this.beat=0}this.ctx.resume()}catch{}}
 tone(f,d=.12,type='triangle',v=.04,end=f){if(!this.ctx||!settings.sound)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+d+.02)}
 sfx(s){if(s.type==='swap'){this.tone(200,.25,'square',.025,950)}if(['nitro','railHit','slingshot'].includes(s.type))this.tone(140,.15,'sawtooth',.035,800);if(s.type==='hurt')this.tone(90,.15,'sawtooth',.05,25);if(['upgrade','raceClear','lap'].includes(s.type)){this.tone(440,.12);setTimeout(()=>this.tone(660,.17),80)}if(s.type==='pickup')this.tone(1100,.05,'sine',.02)}
 update(){if(!this.ctx)return;const on=game?.phase==='playing'&&settings.sound&&!document.hidden;this.eg.gain.setTargetAtTime(on?.008:0,this.ctx.currentTime,.12);this.engine.frequency.setTargetAtTime(45+(game?.p.v||0)*.32,this.ctx.currentTime,.1);if(!on||!settings.music||this.ctx.currentTime<this.next)return;this.next=this.ctx.currentTime+.24;this.beat++;const b=[55,55,82,55,65,65,73,82][Math.floor(this.beat/4)%8];if(this.beat%2===0)this.tone(b,.18,'triangle',.025);if(this.beat%4===0)this.tone(120,.06,'sine',.025,40);if(this.beat%8===6)this.tone(b*8,.08,'triangle',.012)}
}const sound=new Audio();
function notify(s){$('notice').textContent=s;noticeUntil=performance.now()+2600;$('notice').classList.add('show')}
function clearInput(){keys.clear();held.clear();joy.id=null;joy.x=joy.y=0;$('stick').style.transform='translate(0,0)';document.querySelectorAll('.action.held').forEach(b=>b.classList.remove('held'))}
function checkpoint(){if(game)store.checkpoint(game);lastSave=performance.now()}
function lobby(){clearInput();game=null;menu='';signature='';$('modal').hidden=true;$('hud').hidden=true;$('lobby').hidden=false;refreshLobby()}
function refreshLobby(){profile.selection={car,city:+document.getElementById('city').value,difficulty:+document.getElementById('difficulty').value,endless:document.getElementById('endless').checked,map:selectedMap};store.save();document.documentElement.style.setProperty('--hero',D.cars[car].color);$('cars').innerHTML=D.cars.map((v,i)=>`<button data-car="${i}" class="${car===i?'selected':''}" style="--hero:${v.color}">0${i+1} / ${v.name}</button>`).join('');const v=D.cars[car];$('car-info').innerHTML=`<b>${v.alias}</b>　车体 ${v.hp} / 车速 ${v.speed}<br>${v.desc}`;$('city-info').textContent=D.cities[+$('city').value].desc;$('wallet').textContent=`◇ ${Math.floor(profile.wallet)}`;const g=C.Game.restore(store.run());$('continue').hidden=!g;if(g)$('continue').textContent=`续接第 ${g.stage} 站 ↻`;if($('track-picker'))$('track-picker').textContent='首站赛道 · '+(D.tracks.find(t=>t.id===selectedMap)?.name||'随机 · 24 张赛道')+'　↗'}
$('city').innerHTML=D.cities.map((v,i)=>`<option value="${i}">${v.name}</option>`).join('');$('difficulty').innerHTML=D.difficulties.map((v,i)=>`<option value="${i}">${v.name}</option>`).join('');$('city').onchange=()=>{selectedMap=null;refreshLobby()};$('cars').onclick=e=>{const b=e.target.closest('[data-car]');if(b){car=+b.dataset.car;refreshLobby()}};
const mapButton=document.createElement('button');mapButton.id='track-picker';mapButton.className='track-picker';$('city-info').after(mapButton);mapButton.onclick=()=>{sound.unlock();mapFilter=-1;showMaps()};
$('city').value=profile.selection.city;$('difficulty').value=profile.selection.difficulty;$('endless').checked=profile.selection.endless;
$('difficulty').onchange=$('endless').onchange=()=>{profile.selection={car,city:+$('city').value,difficulty:+$('difficulty').value,endless:$('endless').checked,map:selectedMap};store.save()};
function showMaps(){const list=D.tracks.filter(t=>mapFilter<0||t.city===mapFilter);open('maps','赛道图鉴 / 24 张地图','选择首站赛道；后续六站赛事将轮换赛道。同一巡游会优先使用没跑过的地图。','<div class="map-filters">'+[['全部 · 24',-1],...D.cities.map((c,i)=>[c.name+' · 8',i])].map(([name,id])=>`<button data-filter="${id}" class="${mapFilter===id?'selected':''}">${name}</button>`).join('')+'</div><div class="map-grid">'+list.map(t=>{const track=new C.Track('preview',t.city,'safe',false,t.id),points=track.points.map(p=>`${(p.x/2800*160).toFixed(1)},${(p.y/2250*110).toFixed(1)}`).join(' ');return`<button class="map-choice ${selectedMap===t.id?'selected':''}" data-map="${t.id}" style="--accent:${D.cities[t.city].color}"><svg viewBox="0 0 160 110" aria-label="${t.name}路线预览"><polygon points="${points}" fill="none" stroke="#485367" stroke-width="12" stroke-linejoin="round"/><polygon points="${points}" fill="none" stroke="${D.cities[t.city].color}" stroke-width="1.5" stroke-linejoin="round"/></svg><small>${D.cities[t.city].name} · ${t.type}</small><b>${t.name}</b><p>${t.desc}</p></button>`}).join('')+'</div>','MAP ATLAS');$('modal-body').onclick=e=>{const filter=e.target.closest('[data-filter]'),b=e.target.closest('[data-map]');if(filter){mapFilter=+filter.dataset.filter;showMaps()}else if(b){selectedMap=b.dataset.map;$('city').value=D.tracks.find(t=>t.id===selectedMap).city;refreshLobby();close()}};footer([['随机首站',()=>{selectedMap=null;refreshLobby();close()}],['返回',close,true]])}
function start(training=false,resumed=null,options=null){sound.unlock();clearInput();game=resumed||new C.Game(options||{car,city:+$('city').value,difficulty:+$('difficulty').value,endless:$('endless').checked,map:selectedMap,training,meta:training?{}:profile.meta,seed:profile.seed||undefined});renderer.reset(game);menu='';signature='';$('lobby').hidden=true;$('hud').hidden=false;$('modal').hidden=true;document.documentElement.style.setProperty('--hero',game.carData.color);$('portrait').textContent='0'+(game.car+1);checkpoint();sync(true);updateHud();if(!training)notify('前 3 晋级 · 决赛前 2 且领先首领。尾流蓄满后拉出车道换速！')}
$('start').onclick=()=>{if(C.Game.restore(store.run())){open('replace','开始新赛事？','新赛事会替换尚未完成的赛事存档。永久研究和记录继续保留。','<p class="guide">点击「续接赛事」可回到上一站。</p>','NEW GRID');footer([['返回',close],['启动新赛事',()=>start(),true]])}else start()};$('training').onclick=()=>start(true);$('continue').onclick=()=>{const g=C.Game.restore(store.run());if(g)start(false,g);else{store.remove(VelocitySave.keys.RUN);refreshLobby()}};
function open(id,title,sub,body,kicker='VELOCITY SYSTEM',closable=true){menu=id;clearInput();$('modal').hidden=false;$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-sub').textContent=sub;$('modal-body').innerHTML=body;$('modal-body').onclick=null;$('modal-body').onchange=null;$('modal-footer').innerHTML='';$('close').hidden=!closable;setTimeout(()=>{($('modal-body').querySelector('button:not(:disabled)')||$('modal-footer').querySelector('button')||(!$('close').hidden&&$('close')))?.focus({preventScroll:true})},0)}
function footer(items){$('modal-footer').innerHTML='';for(const [text,action,primary]of items){const b=document.createElement('button');b.textContent=text;if(primary)b.className='primary';b.onclick=()=>{sound.unlock();action()};$('modal-footer').appendChild(b)}}
function close(){if(game){menu='';if(['paused','upgrade','garage','event','route','result','trainingDone'].includes(game.phase)){sync(true);return}}$('modal').hidden=true;menu=''}$('close').onclick=close;
const stat=(v,s)=>`<div class="stat"><b>${v}</b><span>${s}</span></div>`,time=t=>Number.isFinite(t)?`${Math.floor(t/60)}:${(t%60).toFixed(2).padStart(5,'0')}`:'—';
function upgradeCard(id){const u=D.upgrades.find(u=>u.id===id);return`<button class="choice ${u.requires?'advanced':''}" data-upgrade="${id}" style="--accent:${colors[u.group]}"><div class="glyph">${u.glyph}</div><span class="group">${D.groups[u.group]}${u.requires?' / 高阶':''}</span><b>${u.name}</b><p>${u.desc}</p><span class="level">${game.up(id)} → ${game.up(id)+1} / ${u.max}</span></button>`}
function sync(force=false){if(!game)return;const sig=[game.phase,game.options.join(),game.eventChoices.join(),game.routeChoices.join(),game.tutorialStep,game.pending,game.coins,game.shopUsed.join()].join('|');if(!force&&sig===signature)return;signature=sig;
 if(['playing','countdown'].includes(game.phase)){menu='';$('modal').hidden=true;updateTutorial();return}clearInput();
 if(game.phase==='paused'){showPause();return}
 if(game.phase==='upgrade'){open('upgrade','改写引擎 / 三选一',`LV.${game.level} · 剩余 ${game.pending} 次选择 · 赛事暂停`,'<div class="cards">'+game.options.map(upgradeCard).join('')+'</div>','BUILD YOUR ADVANTAGE',false);$('modal-body').onclick=e=>{const b=e.target.closest('[data-upgrade]');if(b&&game.selectUpgrade(b.dataset.upgrade)){checkpoint();sync(true)}};footer([[`刷新 · 剩余 ${game.rerolls}`,()=>{if(game.reroll()){checkpoint();sync(true)}}]]);$('modal-footer').firstChild.disabled=game.rerolls<=0;return}
 if(game.phase==='event'){open('event','地下合约 / 选择代价','改动会持续到本局结束。奖励与代价都立即生效。','<div class="cards">'+game.eventChoices.map(id=>{const v=D.events.find(v=>v.id===id);return`<button class="choice" data-event="${id}"><div class="glyph">${v.glyph}</div><span class="group">CITY CONTRACT</span><b>${v.name}</b><p>${v.gain}</p><span class="bad level">${v.cost}</span></button>`}).join('')+'</div>','RISK / REWARD',false);$('modal-body').onclick=e=>{const b=e.target.closest('[data-event]');if(b&&game.chooseEvent(b.dataset.event)){checkpoint();sync(true)}};return}
 if(game.phase==='garage'){const items=[['free','车库例行保养','修复 18% 车体',0],['repair','应急维修','修复 45% 车体',40],['kit','装载维修包','+1 维修次数，上限 5',50],['upgrade','选购改件','一次改件三选一',100],['battery','充电站','电量 +60，带入下一站',35],['coolant','冷却套餐','热量归零，下站起步 2 秒护盾',25],['reroll','候选凭证','改件刷新次数 +2',40]];open('garage','维修区 / 准备下一站',`维修币 ◇ ${Math.floor(game.coins)} · 车体 ${Math.ceil(game.p.hp)} / ${game.maxHp} · 电量 ${Math.round(game.p.energy)} · 每种服务每站限购一次`,'<div class="shop-grid">'+items.map(([id,name,desc,cost])=>`<button data-buy="${id}" ${game.shopUsed.includes(id)||game.coins<cost||id==='kit'&&game.p.heals>=5?'disabled':''}><b>${name}</b><p>${desc}</p><small>${game.shopUsed.includes(id)?'已使用':cost?'◇ '+cost:'免费领取'}</small></button>`).join('')+'</div>','PIT LANE',false);$('modal-body').onclick=e=>{const b=e.target.closest('[data-buy]');if(b&&game.buy(b.dataset.buy)){checkpoint();sync(true)}};footer([['当前构筑',showBag],['选择下一条路线 →',()=>{game.offerRoutes();checkpoint();sync(true)},true]]);return}
 if(game.phase==='route'){open('route','路线分岔 / 第 '+(game.stage+1)+' 站',`下一街区：${D.cities[(game.startCity+Math.floor(game.stage/2))%3].name} · 路线改变真实赛道宽度、长度与障碍`,'<div class="cards">'+game.routeChoices.map(id=>{const r=D.routes.find(r=>r.id===id);return`<button class="choice" data-route="${id}"><div class="glyph">${r.glyph}</div><span class="group">NEXT GRID</span><b>${r.name}</b><p>${r.desc}</p></button>`}).join('')+'</div>','THE ROAD IS YOURS',false);$('modal-body').onclick=e=>{const b=e.target.closest('[data-route]');if(b&&game.chooseRoute(b.dataset.route)){renderer.reset(game);checkpoint();sync(true)}};return}
 if(game.phase==='trainingDone'){if(game.won){profile.tutorial=true;store.save()}open('trainingDone',game.won?'驾校毕业 / 准备夺速':'训练已结束',game.won?'已完成六步驾驶教学。正式赛事的对手会抢线、铺轨和封锁。':'可以随时再进驾校练习。','<p class="guide">训练不结算奖励，不覆盖正式赛事存档。<br>比赛先跟入尾流，电量充足后选择喷射或共享路轨；漂移的收益要与热量平衡。</p>','DRIVING SCHOOL',false);footer([['返回大厅',lobby,true],['重新训练',()=>start(true)]]);return}
 if(game.phase==='result'){checkpoint();open('result',game.won?'劫速冠军 / 街区归你':'赛事封存 / 再起引擎',`${game.reason} · ${game.carData.name} · ${D.difficulties[game.difficulty].name} · 种子 ${game.seed}`,`<div class="stats">${stat(game.records.length,'已完赛站数')}${stat(game.stats.swaps,'换速次数')}${stat(game.stats.otherRails,'对手使用路轨')}${stat(game.reward,'结算研究碎片')}</div><div class="guide">${game.records.map(r=>`第 ${r.stage} 站 · ${D.cities[r.city].name} · 第 ${r.place} 名 · ${time(r.time)} · ${D.routes.find(v=>v.id===r.route).name}`).join('<br>')||'未完成本站'}<p>漂移 ${Math.round(game.stats.drift)} 米 · 超车 ${game.stats.overtakes} · 高阶改件 ${game.stats.advanced} · 最佳圈 ${time(game.stats.bestLap||null)}</p></div>`,'FINISH LINE',false);const o={car:game.car,city:game.startCity,difficulty:game.difficulty,endless:game.endless,map:game.firstMap,meta:profile.meta,seed:game.seed};footer([['查看构筑',showBag],['回到大厅',lobby],['同种子再赛',()=>start(false,null,o),true]]);return}
}
function updateTutorial(){const show=!!game?.training&&game.phase==='playing';$('tutorial').hidden=!show;if(show){const l=lessons[game.tutorialStep];if(l)$('tutorial').innerHTML=`<b>${l[0]}</b><span>${l[1]}</span><small>教学 ${game.tutorialStep+1} / 6 · 无正式奖励 · 车体与电量受到保护</small>`}}
function showPause(){open('paused',game.training?'驾校暂停':'引擎怠速 / 已暂停',`第 ${game.stage} 站 · 种子 ${game.seed} · 已保存当前赛事进度`,'<div class="guide">尾流连接变绿后，拉开横向距离再交换车速，可以减少碰撞。<br>离开页面会自动暂停；读取存档保留原赛道、车辆、改件和商店状态。</div>','PARK / RESUME',false);footer([['设置',showSettings],['当前构筑',showBag],['保存回大厅',()=>{checkpoint();lobby()}],['封存赛事',()=>{open('bank','封存本次赛事？','按已获得的成绩结算研究碎片；本次赛事无法继续。','<p class="guide">如需稍后继续，请选择「保存回大厅」。</p>','BANK THE RUN');footer([['继续暂停',showPause],['封存',()=>{game.finish(false,'主动封存');checkpoint();sync(true)},true]])}],['继续比赛',()=>{game.resume();clearInput();checkpoint();sync(true)},true]])}
function pause(){if(game?.pause()){checkpoint();sync(true)}}$('pause').onclick=pause;$('bag').onclick=()=>{if(game){if(['playing','countdown'].includes(game.phase))game.pause();checkpoint();showBag()}};
function back(){menu='';if(game)sync(true);else close()}
function showBag(){if(!game)return;open('bag','车载改件 / 当前构筑',`最高基础速度 ${Math.round(game.maxSpeed)} · 抓地 ${game.grip.toFixed(2)} · 最大车体 ${game.maxHp} · 修理包 ${game.p.heals}`,'<div class="build-grid">'+Object.entries(game.build).map(([id,lv])=>{const v=D.upgrades.find(v=>v.id===id);return`<div style="border-left:2px solid ${colors[v.group]}">${v.glyph} ${v.name} ×${lv}<small>${v.desc}</small></div>`}).join('')+'</div><p class="guide">'+(Object.keys(game.build).length?'':'尚未安装改件。漂移、超车、拾取紫色资料和完赛可获得选择。')+'</p><p class="guide">高阶配方：尾流天线 2 + 劫速离合 2 → 连锁劫速；宽幅磁场 2 + 路轨卷轴 2 → 私有快线；过路抽成 2 + 能量托管 2 → 路权税务；液冷循环 2 + 漂移回收 2 → 冷焰引擎；侧向抓地 2 + 高压电机 2 → 出弯弹弓；活性车壳 2 + 自愈底盘 2 → 不死底盘。</p>','ONBOARD BUILD');footer([['返回',back,true]])}
function showSettings(){open('settings','驾驶设置','自动油门默认开启。转向以车身为基准；镜头跟随开关决定是否旋转画面。','<div class="settings">'+[['sound','引擎与音效'],['music','电子节拍'],['vibrate','支持设备的振动反馈'],['auto','自动油门'],['assist','回中辅助'],['motion','追车透视镜头（关闭为高视角）']].map(([id,name])=>`<label>${name}<input type="checkbox" data-setting="${id}" ${settings[id]?'checked':''}></label>`).join('')+`<label>画面质量<select data-setting="quality"><option value="high" ${settings.quality==='high'?'selected':''}>高 · 细节与雨幕</option><option value="low" ${settings.quality==='low'?'selected':''}>省电</option></select></label></div><div class="seed-row"><label for="seed">下次新赛事种子</label><input id="seed" maxlength="32" value="${esc(profile.seed)}" placeholder="留空随机"><button id="save-seed">保存</button></div><p class="muted">相同种子固定赛道及候选随机序列；驾驶行为会影响后续随机进度。</p>`,'DRIVING OPTIONS');$('modal-body').onchange=e=>{const id=e.target.dataset.setting;if(id){settings[id]=e.target.type==='checkbox'?e.target.checked:e.target.value;store.save();renderer.resize();sound.unlock();updateHud()}};$('save-seed').onclick=()=>{profile.seed=$('seed').value.trim();store.save();notify('种子已保存，下次新赛事生效')};footer([['返回',back,true]])}
function showMeta(){open('meta','改装研究所',`研究碎片 ◇ ${Math.floor(profile.wallet)} · 研究只影响下次正式赛事`,'<div class="meta-grid">'+D.meta.map(m=>{const lv=profile.meta[m.id],cost=Math.round(m.cost*(1+lv*.65));return`<div class="row-card"><b>${m.name} · ${lv} / ${m.max}</b><p>${m.desc}</p><button data-meta="${m.id}" ${lv>=m.max||profile.wallet<cost?'disabled':''}>${lv>=m.max?'研发完成':'研发 ◇ '+cost}</button></div>`}).join('')+'</div>','PERMANENT RESEARCH');$('modal-body').onclick=e=>{const b=e.target.closest('[data-meta]');if(b&&store.upgrade(b.dataset.meta)){showMeta();refreshLobby()}};footer([['返回',back,true]])}
function showRecords(){const s=profile.stats;open('records','车手档案 / 赛道留痕','只统计正式赛事；成就需点击领取。','<div class="stats">'+stat(s.runs,'赛事结算')+stat(s.wins,'夺冠')+stat(s.swaps,'换速')+stat(time(profile.bestLap||null),'最佳圈')+'</div><p class="guide">车系冠军：'+D.cars.map(v=>v.name+' '+(profile.cars[v.id]||0)).join(' / ')+'<br>冠军巡游街区：'+(profile.cities.map(i=>D.cities[i].name).join('、')||'尚未夺冠')+'</p><div class="meta-grid">'+D.achievements.map(a=>`<div class="row-card ${profile.claimed.includes(a.id)?'completed':''}"><b>${a.name}</b><p>${Math.min(a.target,Math.floor(s[a.stat]))} / ${a.target} · 奖励 ◇ ${a.reward}</p><button data-claim="${a.id}" ${profile.claimed.includes(a.id)||s[a.stat]<a.target?'disabled':''}>${profile.claimed.includes(a.id)?'已领取':'领取奖励'}</button></div>`).join('')+'</div>','DRIVER ARCHIVE');$('modal-body').onclick=e=>{const b=e.target.closest('[data-claim]');if(b&&store.claim(b.dataset.claim)){showRecords();refreshLobby()}};footer([['返回',back,true]])}
function showGuide(){open('guide','街区规则 / 玩法研究','3D 赛车肉鸽：驾驶、速度转移与共享路权构成同一个决策。',`<div class="guide"><p><b>先跟，后偷，再超。</b> 对手前方 20–230 米、横向接近时进入尾流，蓄满绿色连接即可换速。拉出尾流后还有 1.4 秒窗口。交换的是当前速度，位置和圈数连续；目标更慢时也会让你减速。</p><p><b>电量去哪？</b> 漂移、尾流和自然恢复积蓄电量。氮气消耗 25 电量、升温 22；路轨基础消耗 45；护盾消耗 35。漂移必须同时转向且速度超过 150。热量超过 95 会损速，松开漂移或装液冷散热。</p><p><b>路轨属于整条街。</b> 你在前方铺下共享轨面，每辆车每圈可使用一次。AI 会真实加速；你可以借路线把其他车的通行变成自己的维修币和电量。</p><p><b>六站锦标赛。</b> 七辆车同场，每站两圈，决赛三圈。前五站前 3 晋级；决赛需前 2 并领先首领。每两站切换街区，偶数站遇到首领。先看封锁预警，再决定换道、刹车或开盾。</p><p><b>构筑与路线。</b> 24 种改件，6 种高阶配方。资料、超车和漂移提供经验，完赛保证一次选择。站间买改件、维修与补给，再选真实不同的窄捷径、技术线或安全线。无尽巡游每六站进入更强一轮。</p><p><b>研究参考。</b> <a href="https://store.steampowered.com/app/3088700/Driving_Rogue/" target="_blank" rel="noopener">Driving Rogue</a> 的漂移连击与交通穿行、<a href="https://store.steampowered.com/app/3078120/Reality_Drift/" target="_blank" rel="noopener">Reality Drift</a> 公布的路线与赛车构筑（尚未发售）、<a href="https://theknightsofu.com/projects/death-roads-tournament-all-stars/" target="_blank" rel="noopener">Death Roads</a> 的车辆牌组策略。这里采用「尾流后交换即时车速」和「双方都能使用的玩家铺轨」的组合；未作全球首创判断。</p><p>电脑：A/D 或 ←/→ 转向，W 油门，S 刹车，SHIFT 漂移，J 换速，K 铺轨，SPACE 喷射，U 护盾，H 维修，P/ESC 暂停。手机：左摇杆转向，右侧按钮可按住漂移/刹车并同时驾驶。</p></div>`,'DRIVING / BUILD / ROUTE');footer([['返回',back,true]])}
document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{sound.unlock();({meta:showMeta,records:showRecords,guide:showGuide,settings:showSettings})[b.dataset.menu]()});
$('sound').onclick=()=>{settings.sound=!settings.sound;store.save();sound.unlock();updateHud()};$('auto').onclick=()=>{settings.auto=!settings.auto;store.save();updateHud()};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('shell').requestFullscreen()}catch{notify('此浏览器无法开启全屏，可使用系统横屏游玩')}};
function action(id){sound.unlock();if(!game||game.phase!=='playing')return;if(!game[id]())notify(({swap:'需要绿色尾流连接，并等冷却结束',rail:'铺轨需要电量，或等待冷却',nitro:'喷射需要电量，或等待冷却',shield:'护盾需要 35 电量，或等待冷却',repair:'需要维修包且车体未满'})[id]);checkpoint();sync()}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action)}));
document.querySelectorAll('[data-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(game?.phase!=='playing')return;sound.unlock();held.set(e.pointerId,b.dataset.hold);b.setPointerCapture(e.pointerId);b.classList.add('held')});const release=e=>{held.delete(e.pointerId);b.classList.toggle('held',[...held.values()].includes(b.dataset.hold))};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release)});
const joystick=$('joystick');function moveJoy(e){const r=joystick.getBoundingClientRect(),radius=r.width*.35;joy.x=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/radius));joy.y=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/radius));$('stick').style.transform=`translate(${joy.x*radius}px,${joy.y*radius}px)`}
joystick.addEventListener('pointerdown',e=>{if(game?.phase!=='playing'||joy.id!==null)return;e.preventDefault();sound.unlock();joy.id=e.pointerId;joystick.setPointerCapture(e.pointerId);moveJoy(e)});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joy.id)moveJoy(e)});const endJoy=e=>{if(e.pointerId===joy.id){joy.id=null;joy.x=joy.y=0;$('stick').style.transform='translate(0,0)'}};joystick.addEventListener('pointerup',endJoy);joystick.addEventListener('pointercancel',endJoy);joystick.addEventListener('lostpointercapture',endJoy);
addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const k=e.key.toLowerCase();if([' ','arrowleft','arrowright','arrowup','arrowdown','shift'].includes(k))e.preventDefault();if(e.repeat)return;if(k==='escape'||k==='p'){if(menu==='paused'){game.resume();checkpoint();sync(true)}else if(menu)close();else pause();return}if(menu||game?.phase!=='playing')return;keys.add(k);const a={j:'swap',k:'rail',' ':'nitro',u:'shield',h:'repair'}[k];if(a)action(a)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
addEventListener('blur',()=>{clearInput();if(game?.pause()){checkpoint();sync(true)}});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(game?.pause())sync(true);checkpoint()}});addEventListener('pagehide',checkpoint);
function updateHud(){if(!game)return;const p=game.p;$('hp-label').textContent=`车体 ${Math.ceil(p.hp)} / ${game.maxHp}`;$('hp-bar').style.width=p.hp/game.maxHp*100+'%';$('energy-bar').style.width=p.energy+'%';$('energy-label').textContent=`电量 ${Math.floor(p.energy)} / 100　维修包 ${p.heals}`;$('stage-label').textContent=`${D.cities[game.city].name} · ${game.training?'驾校':'第 '+game.stage+' 站'}`;$('lap-label').textContent=`${game.bossRace?'首领赛 · ':''}${D.tracks.find(t=>t.id===game.layout)?.name||"练习环"} · 圈 ${Math.min(game.laps,p.lap+1)} / ${game.laps} · ${time(game.raceTime)}`;$('distance-bar').style.width=Math.max(0,p.s/game.goal*100)+'%';$('xp-bar').style.width=game.xp/game.xpNeed*100+'%';$('level').textContent=`LV.${game.level} / ◇ ${Math.floor(game.coins)}`;$('rank').textContent=game.rank();$('rank-info').textContent=game.training?'驾校练习':game.localStage===6?'决赛 · 前 2 且领先首领':'位 / 7 · 前 3 晋级';$('speed').textContent=Math.round(p.v);$('heat-bar').style.width=Math.min(100,p.heat)+'%';$('heat-label').textContent=`热量 ${Math.round(p.heat)}${p.heat>95?' · 过热损速':p.drifting?' · 漂移蓄电':''}`;$('heat-label').classList.toggle('bad',p.heat>95);const e=game.rivals.find(e=>e.id===game.link.id);$('preview').textContent=e?`${e.name} · 连接 ${Math.round(game.link.charge*100)}% · 换速 ${e.v-p.v>=0?'+':''}${Math.round(e.v-p.v)} KM/H`:'跟入对手尾流 → 蓄满后换速';$('auto').textContent='自动油门 '+(settings.auto?'ON':'OFF');$('sound').textContent=settings.sound?'♪':'♩';$('countdown').hidden=game.phase!=='countdown';$('countdown').textContent=Math.ceil(game.countdown)||'GO';
 const details={swap:[p.swapCd,5,game.link.charge>=1?'连接就绪':'连接 '+Math.round(game.link.charge*100)+'%'],rail:[p.railCd,3.5,game.railCost()+' 电'],shield:[p.shieldCd,12,'35 电'],nitro:[p.nitroCd,1,(game.up('coldFire')&&p.heat>55?10:25)+' 电'],repair:[0,1,p.heals+' 次']};for(const b of document.querySelectorAll('[data-action]')){const [cd,max,label]=details[b.dataset.action];b.style.setProperty('--fill',Math.min(100,cd/max*100)+'%');b.querySelector('small').textContent=cd>0?cd.toFixed(1)+'s':label;b.classList.toggle('ready',b.dataset.action==='swap'&&game.link.charge>=1&&cd===0)}updateTutorial()}
function frame(now){const dt=Math.min(.04,Math.max(0,(now-last)/1000));last=now;if(game){const previous=game.phase;if(!menu&&['playing','countdown'].includes(game.phase)){const steer=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);game.update(dt,{steer:steer||joy.x,throttle:settings.auto||keys.has('w')||keys.has('arrowup')||joy.y<-.5,brake:keys.has('s')||keys.has('arrowdown')||joy.y>.6||[...held.values()].includes('brake'),drift:keys.has('shift')||[...held.values()].includes('drift'),assist:settings.assist?1:0})}const signals=game.drain();renderer.handle(signals,game);signals.forEach(s=>{sound.sfx(s);if(s.type==='swap')notify(`劫速 ${s.gain>=0?'+':''}${Math.round(s.gain)} KM/H`);if(s.type==='bossSkill')notify(s.text);if(s.type==='hurt'&&settings.vibrate)navigator.vibrate?.(25);if(s.type==='raceClear')notify(`第 ${s.place} 名晋级，获得改件与维修币`);if(s.type==='phoenix')notify('不死底盘启动 · 本局仅一次')});renderer.draw(game,dt);if(now-hudAt>80){updateHud();hudAt=now}if(previous!==game.phase){checkpoint();sync(true)}else if(!menu||['upgrade','garage','event','route'].includes(menu))sync();if(!game.training&&now-lastSave>5000)checkpoint()}sound.update();if(noticeUntil&&now>noticeUntil){$('notice').classList.remove('show');noticeUntil=0}requestAnimationFrame(frame)}
refreshLobby();requestAnimationFrame(frame);
})();
