import * as T from 'three';
import {GLTFLoader} from './vendor/examples/jsm/loaders/GLTFLoader.js';
import {mergeGeometries} from './vendor/examples/jsm/utils/BufferGeometryUtils.js';
const S=.04,assets=[],loader=new GLTFLoader(),$=id=>document.getElementById(id);
const standard=(color,opts={})=>new T.MeshStandardMaterial({color,roughness:.65,...opts}),basic=(color,opts={})=>new T.MeshBasicMaterial({color,...opts});
const box=new T.BoxGeometry(1,1,1),v3=(x,y,z)=>new T.Vector3(x,y,z);
function carAsset(root){root.updateMatrixWorld(true);const groups=new Map();root.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.clone().applyMatrix4(o.matrixWorld).toNonIndexed();g.deleteAttribute('tangent');g.deleteAttribute('uv1');g.deleteAttribute('uv');const wheel=/wheel/i.test(o.name),p=new T.Vector3().setFromMatrixPosition(o.matrixWorld),key=(wheel?`wheel:${p.x>0?'F':'R'}:${p.z>0?'L':'R'}`:'body')+'|'+o.material.name;const entry=groups.get(key)||{geo:[],mat:o.material,wheel,p};entry.geo.push(g);groups.set(key,entry)});const result=new T.Group(),wheels=new Map();for(const [key,a]of groups){const geometry=mergeGeometries(a.geo);a.geo.forEach(g=>g.dispose());if(!geometry)throw new Error('模型几何合并失败');const mesh=new T.Mesh(geometry,a.mat);mesh.castShadow=true;mesh.receiveShadow=true;if(a.wheel){const k=key.split('|')[0];let group=wheels.get(k);if(!group){group=new T.Group();group.position.set(a.p.x>0?1.43:-1.45,.43,a.p.z>0?.92:-.92);wheels.set(k,group);result.add(group)}geometry.translate(-group.position.x,-group.position.y,-group.position.z);group.add(mesh)}else result.add(mesh)}result.scale.setScalar(.55);return result}
class Renderer{
 constructor(canvas,settings){this.canvas=canvas;this.settings=settings;this.w=canvas.clientWidth;this.h=canvas.clientHeight;this.t=0;this.fx=[];this.skids=[];this.mapKey='';this.scene=new T.Scene();this.scene.background=new T.Color('#171d2e');this.scene.fog=new T.FogExp2('#171d2e',.013);this.gl=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.gl.outputColorSpace=T.SRGBColorSpace;this.gl.toneMapping=T.ACESFilmicToneMapping;this.gl.toneMappingExposure=1.4;this.gl.shadowMap.enabled=true;this.gl.shadowMap.type=T.PCFShadowMap;this.camera=new T.PerspectiveCamera(52,this.w/this.h,.1,220);this.aim=v3(0,0,0);this.heading=0;this.scene.add(new T.HemisphereLight('#c5ddff','#292033',2.4));this.sun=new T.DirectionalLight('#c5d4ff',3);this.sun.position.set(15,28,-15);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);this.sun.shadow.camera.left=-28;this.sun.shadow.camera.right=28;this.sun.shadow.camera.top=28;this.sun.shadow.camera.bottom=-28;this.sun.shadow.normalBias=.03;this.scene.add(this.sun,this.sun.target);this.rim=new T.DirectionalLight('#aa55ff',1.3);this.rim.position.set(-10,8,10);this.scene.add(this.rim);
  this.static=new T.Group();this.dynamic=new T.Group();this.effects=new T.Group();this.scene.add(this.static,this.dynamic,this.effects);this.vehicles=new Map();this.items=new Map();this.overlay=document.createElement('canvas');this.overlay.id='race-overlay';this.overlay.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';canvas.after(this.overlay);this.c=this.overlay.getContext('2d');this.resize();addEventListener('resize',()=>this.resize());canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();window.dispatchEvent(new Event('blur'));$('notice').textContent='3D 图形上下文丢失，赛事已暂停并保存。请刷新续接。';$('notice').classList.add('show')})
 }
 resize(){this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;const ratio=Math.min(devicePixelRatio||1,this.settings.quality==='high'?1.6:1);this.gl.setPixelRatio(ratio);this.gl.setSize(this.w,this.h,false);this.camera.aspect=this.w/this.h;this.camera.updateProjectionMatrix();this.gl.shadowMap.enabled=this.settings.quality==='high';this.overlay.width=this.w*ratio;this.overlay.height=this.h*ratio;this.dpr=ratio}
 reset(g){this.mapKey='';this.fx=[];this.heading=g.track.at(g.p.s).angle;this.initial=true;this.lastSkid=null}
 mergeStatic(){
  this.static.updateMatrixWorld(true);const groups=new Map(),meshes=[];
  this.static.traverse(o=>{if(!o.isMesh||o.isInstancedMesh)return;const m=o.material,key=[m.type,m.color?.getHex(),m.emissive?.getHex(),m.emissiveIntensity,m.metalness,m.roughness,m.side,m.transparent,m.opacity,m.map?.uuid].join('|');let a=groups.get(key);if(!a){a={material:m,geometries:[],cast:false,receive:false};groups.set(key,a)}const geometry=o.geometry.clone().applyMatrix4(o.matrixWorld),geo=geometry.index?geometry.toNonIndexed():geometry;if(geo!==geometry)geometry.dispose();a.geometries.push(geo);a.cast||=o.castShadow;a.receive||=o.receiveShadow;meshes.push(o)});
  for(const o of meshes){o.removeFromParent();o.geometry.dispose()}const retained=new Set([...groups.values()].map(a=>a.material));for(const o of meshes)if(!retained.has(o.material))o.material.dispose();
  for(const a of groups.values()){const geometry=mergeGeometries(a.geometries);a.geometries.forEach(g=>g.dispose());if(!geometry)throw new Error('赛道几何合并失败');const m=new T.Mesh(geometry,a.material);m.castShadow=a.cast;m.receiveShadow=a.receive;this.static.add(m)}
 }
 clear(group){group.traverse(o=>{if(o.geometry&&!o.userData.asset)o.geometry.dispose();if(o.material&&(!o.userData.asset||o.userData.ownMaterial)){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.map?.dispose();m.dispose()})}});group.clear()}
 mesh(geometry,material,group=this.static){const m=new T.Mesh(geometry,material);group.add(m);return m}
 cuboid(pos,size,material,group=this.static){const m=this.mesh(box.clone(),material,group);m.position.copy(pos);m.scale.copy(size);m.castShadow=true;m.receiveShadow=true;return m}
 strip(g,start,length,lane,width,material,y=.035,group=this.static,segments=32){const verts=[],uv=[],idx=[];for(let i=0;i<=segments;i++){for(const d of [-width/2,width/2]){const p=g.track.at(start+length*i/segments,lane+d);verts.push(p.x*S,y,p.y*S);uv.push((d+width/2)/width,i/segments)}}for(let i=0;i<segments;i++){const n=i*2;idx.push(n,n+1,n+2,n+1,n+3,n+2)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setIndex(idx);geo.computeVertexNormals();const m=this.mesh(geo,material,group);m.receiveShadow=true;return m}
 texture(text,color){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#151722';x.fillRect(0,0,512,128);x.strokeStyle=color;x.lineWidth=6;x.strokeRect(4,4,504,120);x.fillStyle=color;x.textAlign='center';x.font='italic bold 49px sans-serif';x.fillText(text,256,79);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
 buildMap(g){this.clear(this.static);this.clear(this.dynamic);this.clear(this.effects);this.vehicles.clear();this.items.clear();this.skids=[];this.mapKey=g.seed+'-'+g.stage+'-'+g.route;const theme=VELOCITY_DATA.cities[g.city],color=theme.color;this.scene.background.set(['#192232','#251b32','#142733'][g.city]);this.scene.fog.color.copy(this.scene.background);
  const floor=this.mesh(new T.PlaneGeometry(170,150),standard(['#18212c','#221b2c','#14232d'][g.city]));floor.rotation.x=-Math.PI/2;floor.position.set(52,-.08,42);floor.receiveShadow=true;
  this.strip(g,0,g.track.length,0,g.track.width*2+36,standard('#121724'),0,this.static,336);this.strip(g,0,g.track.length,0,g.track.width*2,standard(g.city===2?'#303c45':'#333741',{metalness:g.city===2?.35:.15,roughness:g.city===2?.3:.74}),.025,this.static,336);
  for(const lane of [-g.track.width,g.track.width]){this.strip(g,0,g.track.length,lane,9,basic(color),.05,this.static,336);for(let s=0;s<g.track.length;s+=60){const p=g.track.at(s,lane+Math.sign(lane)*13);const rail=this.cuboid(v3(p.x*S,.46,p.y*S),v3(2.05,.9,.28),standard('#526171'));rail.rotation.y=-p.angle;const cap=this.cuboid(v3(p.x*S,.92,p.y*S),v3(2.06,.05,.3),basic(Math.floor(s/60)%2?color:'#aab8c6'));cap.rotation.y=-p.angle}}
  for(const lane of [-45,45])for(let s=0;s<g.track.length;s+=60)this.strip(g,s,22,lane,2.2,basic('#b4c0ce'),.052,this.static,2);
  for(let lane=-g.track.width;lane<g.track.width;lane+=13)for(let j=-1;j<=1;j++)this.strip(g,j*13,13,lane+6.5,13,basic((Math.floor(lane/13)+j)%2?'#fafafa':'#171c24'),.06,this.static,1);
  let rng=VelocityCore.hash(g.seed+'3d'+g.stage),rand=()=>{rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296};const buildings=[],windows=[];
  for(let i=0;i<150;i++){const x=3+rand()*105,z=3+rand()*84;let distance=Infinity;for(let j=0;j<g.track.points.length;j+=5){const p=g.track.points[j];distance=Math.min(distance,Math.hypot(x-p.x*S,z-p.y*S))}const w=2+rand()*4,d=2+rand()*4;if(distance<g.track.width*S+Math.max(w,d)*.7+2)continue;const height=3+rand()*14;buildings.push({x,z,w,d,height});for(let y=1;y<height-1;y+=1.7)for(let k=-w/2+.5;k<w/2;k+=1.2)windows.push({x:x+k,y,z:z-d/2-.01})}
  const mat=standard(['#344355','#45334e','#28474e'][g.city]),inst=new T.InstancedMesh(box.clone(),mat,buildings.length),dummy=new T.Object3D();buildings.forEach((b,i)=>{dummy.position.set(b.x,b.height/2,b.z);dummy.scale.set(b.w,b.height,b.d);dummy.rotation.set(0,0,0);dummy.updateMatrix();inst.setMatrixAt(i,dummy.matrix)});inst.castShadow=true;inst.receiveShadow=true;this.static.add(inst);
  const lights=new T.InstancedMesh(box.clone(),basic(color),windows.length);windows.forEach((b,i)=>{dummy.position.set(b.x,b.y,b.z);dummy.scale.set(.42,.65,.03);dummy.updateMatrix();lights.setMatrixAt(i,dummy.matrix)});this.static.add(lights);
  for(let i=0;i<buildings.length;i+=4){const b=buildings[i];this.cuboid(v3(b.x,b.height+.04,b.z),v3(b.w,.08,b.d),basic(color));}
  for(let i=0;i<8;i++){const p=g.track.at(i*g.track.length/8,g.track.width+35);const sign=this.mesh(new T.PlaneGeometry(5,1.25),basic('#ffffff',{map:this.texture(['VELOCITY','HEIST ⇄','DRIFT / CHARGE','SHARE THE ROAD'][i%4],color),side:T.FrontSide}));sign.position.set(p.x*S,3.3,p.y*S);sign.rotation.y=-p.angle-Math.PI/2;this.cuboid(v3(p.x*S,1.6,p.y*S),v3(.12,3.2,.12),standard('#56677b'))}
  for(let s=0;s<g.track.length;s+=260){const p=g.track.at(s,-g.track.width-25);this.cuboid(v3(p.x*S,2,p.y*S),v3(.14,4,.14),standard('#73838d'));this.cuboid(v3(p.x*S,4.05,p.y*S),v3(.8,.08,.35),basic('#d9ebff'))}
  if(g.city===1){for(let i=0;i<4;i++){const p=g.track.at((i+.5)*g.track.length/4,g.track.width+65);const crane=new T.Group();this.static.add(crane);crane.position.set(p.x*S,0,p.y*S);this.cuboid(v3(0,6,0),v3(.4,12,.4),standard('#cc9642'),crane);this.cuboid(v3(0,11,0),v3(12,.3,.3),standard('#cc9642'),crane);}}
  for(const h of g.hazards){const p=g.track.at(h.s,h.lane);if(h.type==='oil'){const m=this.mesh(new T.CircleGeometry(1,20),standard('#080b18',{metalness:.5,roughness:.08}));m.rotation.x=-Math.PI/2;m.position.set(p.x*S,.06,p.y*S);m.scale.set(1.25,.8,1)}else{const m=this.cuboid(v3(p.x*S,.6,p.y*S),v3(1.2,1.2,1.7),standard('#e99843'));m.rotation.y=-p.angle;for(let i=-1;i<=1;i++){const b=this.cuboid(v3(p.x*S,.9,p.y*S),v3(.14,.14,1.71),basic('#222631'));b.rotation.y=-p.angle;b.position.x+=Math.cos(p.angle)*i*.4;b.position.z+=Math.sin(p.angle)*i*.4}}}
  for(const item of g.pickups){const p=g.track.at(item.s,item.lane),col={data:'#aa55ff',coin:'#c1ff35',energy:'#47e6f2',heal:'#ff568d'}[item.type];const m=this.mesh(new T.OctahedronGeometry(.48),standard(col,{emissive:col,emissiveIntensity:.55,metalness:.4,roughness:.2}),this.dynamic);m.position.set(p.x*S,.75,p.y*S);this.items.set(item.id,m)}
  this.mergeStatic();this.performanceStarted=performance.now();this.frameCount=0;console.info('Velocity3D track',g.layout,'static meshes',this.static.children.filter(o=>o.isMesh).length,'Blender GLB models',assets.length);
  for(const e of [...g.rivals,g.p]){const player=e.id==='player',model=player?g.car:e.type==='heavy'?1:e.type==='drifter'?2:0,clone=assets[model].clone(true);clone.traverse(o=>{if(o.isMesh){o.userData.asset=true;if(/Paint|Accent/.test(o.material.name)){o.material=o.material.clone();o.userData.ownMaterial=true;o.material.color.set(player?g.carData.color:e.color)}}});const root=new T.Group();root.add(clone);this.dynamic.add(root);const shield=this.mesh(new T.SphereGeometry(1.55,20,12),basic('#47e6f2',{transparent:true,opacity:.14,wireframe:true,depthWrite:false}),root);shield.position.y=.65;const flame=this.mesh(new T.ConeGeometry(.48,2.6,9),basic('#47e6f2',{transparent:true,opacity:.85}),root);flame.rotation.z=-Math.PI/2;flame.position.set(-1.9,.28,0);const glow=this.mesh(new T.CircleGeometry(1.7,20),basic(player?g.carData.color:e.color,{transparent:true,opacity:.09,depthWrite:false}),root);glow.rotation.x=-Math.PI/2;glow.position.y=.04;glow.scale.y=.6;this.vehicles.set(e.id,{root,clone,shield,flame,wheels:clone.children.filter(o=>o.type==='Group')});}
  this.railLayer=new T.Group();this.warnLayer=new T.Group();this.dynamic.add(this.railLayer,this.warnLayer);this.railMeshes=new Map();this.warnMeshes=new Map();const linegeo=new T.BufferGeometry().setFromPoints([v3(0,0,0),v3(0,0,0)]);this.linkLine=new T.Line(linegeo,new T.LineBasicMaterial({color:'#47e6f2'}));this.dynamic.add(this.linkLine);
  // A bounded particle system is updated in place, keeping long runs stable.
  const rainCount=260;this.rainArray=new Float32Array(rainCount*3);for(let i=0;i<rainCount;i++){this.rainArray[i*3]=(rand()-.5)*35;this.rainArray[i*3+1]=rand()*20;this.rainArray[i*3+2]=(rand()-.5)*35}const rg=new T.BufferGeometry();rg.setAttribute('position',new T.BufferAttribute(this.rainArray,3));this.rain=new T.Points(rg,new T.PointsMaterial({color:'#b6e9ff',size:.05,transparent:true,opacity:.6}));this.dynamic.add(this.rain);
 }
 burst(g,s,lane,color){const p=g.track.at(s,lane);for(let i=0;i<9;i++){const m=this.mesh(new T.BoxGeometry(.08,.08,.25),basic(color),this.effects),a=Math.random()*Math.PI*2;m.position.set(p.x*S,.45,p.y*S);this.fx.push({mesh:m,v:v3(Math.cos(a)*4,1+Math.random()*3,Math.sin(a)*4),life:.6})}while(this.fx.length>90){const f=this.fx.shift();this.effects.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose()}}
 handle(signals,g){for(const s of signals){if(s.type==='stage')this.mapKey='';if(s.type==='collision')this.burst(g,s.s,s.lane,'#ffb54e');if(['swap','nitro','smallBurst','boostCombo','perfectStart','slingshot','phoenix'].includes(s.type))this.burst(g,g.p.s,g.p.lane,s.type==='swap'?'#c1ff35':g.carData.color);if(s.type==='hurt'&&this.settings.motion)this.shake=.18}}
 draw(g,dt){if(this.mapKey!==g.seed+'-'+g.stage+'-'+g.route)this.buildMap(g);this.t+=dt;const player=g.track.at(g.p.s,g.p.lane),playing=g.phase==='playing';for(const e of [...g.rivals,g.p]){const o=this.vehicles.get(e.id),p=g.track.at(e.s,e.lane);o.root.position.set(p.x*S,.03,p.y*S);o.root.rotation.y=-p.angle-(e.yaw||0);o.clone.rotation.x=e.id==='player'?-(e.latV||0)*.0015:0;o.shield.visible=e.id==='player'&&e.shield>0;o.flame.visible=e.boost>0||e.railBoost>0||e.smallBoost>0||e.comboBoost>0;o.flame.material.color.set(e.comboBoost>0?'#d19aff':e.smallBoost>0?'#96efff':'#47e6f2');o.flame.scale.y=.7+Math.random()*.5;for(const w of o.wheels)if(playing)w.rotation.z-=e.v*S*dt/.22;}
  for(const item of g.pickups){const m=this.items.get(item.id);m.visible=!item.used.includes(Math.floor(g.p.s/g.track.length));m.rotation.y+=dt;m.position.y=.8+Math.sin(this.t*3+item.id)*.12}
  const ids=new Set(g.rails.map(r=>r.id));for(const [id,m]of this.railMeshes)if(!ids.has(id)){this.railLayer.remove(m);m.geometry.dispose();m.material.dispose();this.railMeshes.delete(id)}for(const r of g.rails){let m=this.railMeshes.get(r.id);if(!m){m=this.strip(g,r.s,r.length,r.lane,r.width,basic(r.owner==='player'?'#47e6f2':'#aa55ff',{transparent:true,opacity:.4,side:T.DoubleSide,depthWrite:false}),.09,this.railLayer,18);this.railMeshes.set(r.id,m)}m.material.opacity=.24+Math.sin(this.t*8)*.08;}
  const warnIds=new Set(g.warnings);for(const [w,m]of this.warnMeshes)if(!warnIds.has(w)){this.warnLayer.remove(m);m.geometry.dispose();m.material.dispose();this.warnMeshes.delete(w)}for(const w of g.warnings){let m=this.warnMeshes.get(w);if(!m){m=this.strip(g,w.s-50,100,w.lane,w.width,basic('#ff459a',{transparent:true,opacity:.35,side:T.DoubleSide}),.1,this.warnLayer,8);this.warnMeshes.set(w,m)}m.material.opacity=w.active?.5:.18+Math.sin(this.t*12)*.12;}
  const target=g.rivals.find(e=>e.id===g.link.id);this.linkLine.visible=!!target;if(target){const p=g.track.at(target.s,target.lane),array=this.linkLine.geometry.attributes.position.array;array.set([player.x*S,.9,player.y*S,p.x*S,.9,p.y*S]);this.linkLine.geometry.attributes.position.needsUpdate=true;this.linkLine.geometry.computeBoundingSphere();this.linkLine.material.color.set(g.link.charge>=1?'#c1ff35':'#47e6f2')}
  if(playing&&g.p.drifting&&this.t>(this.sparkAt||0)){this.sparkAt=this.t+(this.settings.quality==='high'?.2:.4);this.burst(g,g.p.s-24,g.p.lane,g.p.driftCharge>=100?'#b797ff':g.p.nitroCharge>50?'#77ddff':'#ffd775')}
  if(playing&&g.p.drifting){const a=g.track.at(g.p.s-24,g.p.lane);if(this.lastSkid){for(const lateral of [-.38,.38]){const geo=new T.BufferGeometry().setFromPoints([v3(this.lastSkid.x*S+lateral,.08,this.lastSkid.y*S),v3(a.x*S+lateral,.08,a.y*S)]),m=new T.Line(geo,new T.LineBasicMaterial({color:'#111620'}));this.effects.add(m);this.skids.push(m)}while(this.skids.length>280){const m=this.skids.shift();this.effects.remove(m);m.geometry.dispose();m.material.dispose()}}this.lastSkid=a}else this.lastSkid=null;
  for(const f of this.fx){f.life-=dt;f.mesh.position.addScaledVector(f.v,dt);f.v.y-=dt*6}for(const f of this.fx.filter(f=>f.life<=0)){this.effects.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose()}this.fx=this.fx.filter(f=>f.life>0);
  this.rain.visible=g.city===2&&this.settings.quality==='high';if(this.rain.visible){this.rain.position.set(player.x*S,0,player.y*S);for(let i=0;i<this.rainArray.length;i+=3){this.rainArray[i+1]-=dt*14;if(this.rainArray[i+1]<0)this.rainArray[i+1]=20}this.rain.geometry.attributes.position.needsUpdate=true}
  // Perspective chase camera with look-ahead, and an alternate high overview camera.
  this.heading+=VelocityCore.angleDiff(player.angle,this.heading)*Math.min(1,dt*4);const forward=v3(Math.cos(this.heading),0,Math.sin(this.heading)),pos=v3(player.x*S,0,player.y*S),portrait=this.w<700;const desired=this.settings.motion?pos.clone().addScaledVector(forward,-(portrait?8.8:8.5)).add(v3(0,portrait?6.5:4.2,0)):pos.clone().add(v3(-7,22,10));const look=this.settings.motion?pos.clone().addScaledVector(forward,portrait?7:10):pos.clone();if(this.initial){this.camera.position.copy(desired);this.aim.copy(look);this.initial=false}else{this.camera.position.lerp(desired,Math.min(1,dt*7));this.aim.lerp(look,Math.min(1,dt*8))}this.shake=Math.max(0,(this.shake||0)-dt*.7);if(this.shake){this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.z+=(Math.random()-.5)*this.shake}this.camera.lookAt(this.aim);const fov=60+Math.min(8,g.p.v/50)+(g.p.boost>0||g.p.smallBoost>0?7:0)+(g.p.comboBoost>0?4:0);this.camera.fov+=(fov-this.camera.fov)*Math.min(1,dt*5);this.camera.updateProjectionMatrix();this.sun.position.copy(pos).add(v3(15,28,-15));this.sun.target.position.copy(pos);this.rim.position.copy(pos).add(v3(-10,8,10));this.gl.render(this.scene,this.camera);this.radar(g);if(++this.frameCount===240)console.info('Velocity3D measured FPS',Math.round(240000/(performance.now()-this.performanceStarted)),'draw calls',this.gl.info.render.calls,'triangles',this.gl.info.render.triangles);
 }
 radar(g){const c=this.c;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.clearRect(0,0,this.w,this.h);
  if(this.settings.motion&&(g.p.boost>0||g.p.smallBoost>0||g.p.comboBoost>0)){c.strokeStyle=g.p.comboBoost>0?'#c5a4ff66':'#b4e8ff55';c.lineWidth=1.5;for(let i=0;i<22;i++){const a=i*Math.PI*2/22,phase=(this.t*1.8+i*.137)%1,rx=this.w*.5,ry=this.h*.45,inner=.7+phase*.1,outer=.82+phase*.15;c.beginPath();c.moveTo(rx+Math.cos(a)*rx*inner,ry+Math.sin(a)*ry*inner);c.lineTo(rx+Math.cos(a)*rx*outer,ry+Math.sin(a)*ry*outer);c.stroke()}}
  const w=this.h<500?96:this.w<700?80:120,h=w*.78,x=this.h<500?20:this.w-w-15,y=this.h<500?132:this.w<700?210:190;c.fillStyle='#101622d9';c.fillRect(x,y,w,h);c.strokeStyle='#ffffff30';c.strokeRect(x,y,w,h);c.beginPath();g.track.points.forEach((p,i)=>{if(i%4)return;const a=x+p.x/2800*w,b=y+p.y/2250*h;if(i===0)c.moveTo(a,b);else c.lineTo(a,b)});c.closePath();c.strokeStyle='#b2c1cd88';c.lineWidth=2;c.stroke();for(const e of [...g.rivals,g.p]){const p=g.track.at(e.s,e.lane);c.beginPath();c.arc(x+p.x/2800*w,y+p.y/2250*h,e.id==='player'?3:2,0,6.28);c.fillStyle=e.id==='player'?g.carData.color:e.boss?'#ff568d':'#c3c3d3';c.fill()}if(this.w>=700&&this.h>500){c.font='10px monospace';c.textAlign='left';g.standings().slice(0,4).forEach((e,i)=>{c.fillStyle=e.id==='player'?g.carData.color:'#d2d4e2';c.fillText((i+1)+' '+(e.id==='player'?g.carData.name:e.name),x,y+h+18+i*16)})}if(g.training){const target=g.rivals[0];if(target){const p=g.track.at(target.s,target.lane),v=v3(p.x*S,1.5,p.y*S).project(this.camera);if(v.z<1){c.fillStyle='#c1ff35';c.textAlign='center';c.font='bold 12px sans-serif';c.fillText('领航员',(v.x*.5+.5)*this.w,(-v.y*.5+.5)*this.h-10)}}}}
}
try{
 $('start').disabled=true;$('training').disabled=true;$('classic-start').disabled=true;$('classic-continue').disabled=true;$('classic-records').disabled=true;$('start').textContent='加载 Blender 车模…';
 const loaded=await Promise.all(VELOCITY_DATA.cars.map(v=>loader.loadAsync(new URL('./models/'+v.id+'.glb',import.meta.url).href)));
 loaded.forEach(v=>assets.push(carAsset(v.scene)));window.VelocityRenderer=Renderer;
 // Verify WebGL2 before presenting an enabled start button.
 const canvas=$('arena'),probe=canvas.getContext('webgl2');if(!probe)throw new Error('浏览器缺少 WebGL2');
 await import('./app.js?v=20261001-classic3');
 $('start').disabled=false;$('training').disabled=false;$('classic-start').disabled=false;$('classic-continue').disabled=false;$('classic-records').disabled=false;$('start').innerHTML='六站巡游 <span>↗</span>';
}catch(e){console.error(e);$('start').textContent='3D 加载失败 · 刷新重试';$('start').disabled=false;$('start').onclick=()=>location.reload();$('storage-warning').hidden=false;$('storage-warning').textContent='3D 初始化失败：'+e.message+'。请通过网站或本地 HTTP 服务打开，并使用支持 WebGL2 的浏览器。'}
